### PR TITLE
getFontStylesForCharacter & getPrefixStyleForCharacter fixes

### PR DESCRIPTION
**Pull request by c0b41**
## Summary

text element throwing startsWith function error.

## Testing Instructions

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
Heya, thanks a lot for your PR!

Could you perhaps share steps to reproduce the original error?

**Comment by c0b41** [comment]
@swissspidy I am working on standalone version web-stories-wp, but some reason text preset throwing error.

https://streamable.com/4cg6ml

**Comment by c0b41** [comment]
@swissspidy  I am not sure why styles coming inline array :/ console

**Comment by swissspidy** [comment]
> @swissspidy I am not sure why styles coming inline array :/ 

Perhaps @barklund knows the answer to that. Sounds like there's some incorrect state after inserting the preset. We should fix that rather than just adding `flatMap` everywhere. Now since it works fine in the plugin version, perhaps it's an issue specifically with your fork?

Your work on a standalone editor sounds very interesting by the way! It's something we want to pursue as well eventually, so I am curious to learn more about your approach.

**Comment by c0b41** [comment]
My fork curently sync main branch, so i am not sure why this happening, i will try to find the real problem.

My cms and editor working great, some of things need to change for this repo for standalone version

- relative path import needs to be change example animation, i18n components imports
- wordpress media picker big blocker, standalone version
- i18n need to change more react way (but current version work some litty hack `@wordpress/i18n` )
- assets paths need to be change more elegant way, for example yarn workspace or lerna

**Pull request closed without merging**
