### PR TITLE
Emit warnings for missing JSDoc comments

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

EmitS warnings for missing JSDoc comments

## Relevant Technical Choices

* Makes `eslint-plugin-jsdoc` usage explicit  
   Before it was implicit via the WordPress ESLint plugin
* Improve jsdoc in tests folder for demonstration purposes
* Uses TypeScript mode for JSDoc comments  
   This makes it easier to eventually adopt TypeScript (#1715)

## User-facing changes

N/A

## Testing Instructions

Run linter

---

See #1714

### CODE REVIEW

**Comment by spacedmonkey** [comment]
There are 855 problems (0 errors, 855 warnings) in the linter here. Are we going to fix these now?

**Comment by swissspidy** [comment]
@spacedmonkey Where are there _errors_? I only see _warnings_, and yes they are meant to be fixed - slowly, in multiple PRs, until there are zero warnings left.

**Comment by spacedmonkey** [comment]
I meant warning yes. 

But it mind of breaks github, as it can only highligh changes on 50 lines. Do you think that is a problem?

**Comment by spacedmonkey** [comment]
Could we generate js docs, in an IDE. Even if they dont have comments? I know phpstorm can generate phpdocs...

**Comment by swissspidy** [comment]
Ah, you mean the limit of 50 annotations per PR? Yeah that might cause more important messages (errors) to be hidden.

We could skip warnings from being output on GitHub, no big deal. An alternative would be only enabling these warnings for one area of the code base at the time.

> Could we generate js docs, in an IDE. Even if they dont have comments? I know phpstorm can generate phpdocs...

Yes and no.

Auto-generated JSDoc annotations are basically like not having any annotations at all. Especially because the IDE can't add type information (because we don't have  any types).

Also, JSDoc comments become more useful if they have clear descriptions.

Auto-generated comments can certainly help _initially_, but all this can only really be done manually.

**Review by spacedmonkey — APPROVED** [review]
LGTM

**Review by cvolzke4 — APPROVED** [review]
I notice this is suggesting JSDoc comments on every function, even functions that are private to the file, which may be overkill.

I think we should be careful to avoid comments that mostly repeat the code it's trying to document. If the code is self-explanatory and there's really nothing to document about, and a comment is just redundant and adds unnecessary clutter to the code.

go/java-practices/comments#what_for

**Comment by swissspidy** [comment]
> I notice this is suggesting JSDoc comments on every function, even functions that are private to the file, which may be overkill.

Good point. Just realized  the ESLint plugin supports a `publicOnly` option. Definitely something we can add.

> I think we should be careful to avoid comments that mostly repeat the code it's trying to document. If the code is self-explanatory and there's really nothing to document about, and a comment is just redundant and adds unnecessary clutter to the code.

Absolutely. One thing that I want to note is that this change here paves the way for more easily introducing TypeScript in the future. That's because TypeScript can use the JSDoc information for the type checking. So once we have correct types in JSDoc everywhere, switching to TS will be a breeze because we've already dealt with the types.

**Pull request merged**
