### PR TITLE
Autosaves: Delete local backup after auto-saving to DB

### PR DESCRIPTION
**Pull request by miina**
## Summary
This addresses an issue with local auto-saving where local backup is not removed after auto-saving to database happens.

## To-do

- [x] Remove local backup when a story is auto-saved

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a new Story and publish.
2. Add some element
3. Wait for the local backup to be stored.
4. Now wait until the DB auto-saving happens
5. Verify that the local backup is removed once it happens.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Partially addresses #12547

### CODE REVIEW

**Review by spacedmonkey — APPROVED** [review]
Seems to work in my testing. I did not see the two messages anymore.

**Comment by kkalarickal** [comment]
@miina @swissspidy -- i tried to test this via `12578 branch` on storie-qa server. But somehow there was only one autosave call made. So I could not see the session stored backup being deleted.

After making some changes to a published story, I could see the `wp_stories_autosave_story_20665` backup created in session storage.

However, there were no autosave calls made and so I could not check if the local backup was deleted.

**Comment by kkalarickal** [comment]
Pls advice if I should check this fix  in another branch.

**Comment by miina** [comment]
@kkalarickal I've updated the PR to `main` and tested in the QA environment -- more than one autosave happens now, perhaps the PR was out of date and did not include the fix for the previous bug where only one autosave happened. Please test again on the same branch.

**Comment by kkalarickal** [comment]
Thanks @miina .

I gave it another go after loading `12578 branch` on stories-qa. Now I can see the multiple autosaves happening, and if I open the same story in another browser instance, I can see that the new version is saved on disk.

However,  I am NOT seeing the `wp_stories_autosave_story_20665` key from session storage being deleted.

So the following test case is failing:
1. Open a previously published story
2. Make some changes to the story (add some pages, or update the title)
3. Wait for `wp_stories_autosave_story_NNNN` key to be created in session storage - to indicate a backup has been taken
4. Wait some more time for the `https://stories-qa-wordpress-amp.pantheonsite.io/wp-json/web-stories/v1/web-story/20665/autosaves/?_locale=user` call to be made - to indicate that autosave was done.

EXPECTED the local session storage key is deleted when autosave runs
OBSERVED the local session storage key remains even if use goes to dashboard

**Comment by miina** [comment]
@kkalarickal I was just testing both locally and in QA and it works when following exactly the same steps 😕

1. Open a previously published story
2. Make some changes to the story (I added a text element)
3. Wait for wp_stories_autosave_story_NNNN key to be created in session storage - to indicate a backup has been taken
4. Wait some more time for the call to be made - to indicate that autosave was done. 
5. See the `wp_stories_autosave_story_NNNN` is deleted

I tested with [this story in the QA env](https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=20320&action=edit#page=%25227bead3ce-9b80-46fa-84bc-3908e7f374dc%2522) although it shouldn't make a difference 

Not sure what we're doing differently 🤔

**Comment by kkalarickal** [comment]
Thanks @miina ... i will double check on another instance and confirm the fix.

**Comment by swissspidy** [comment]
I can confirm that the change works for me.

@kkalarickal Any updates, does it work for you on your end?

Try use the ZIP file from https://github.com/GoogleForCreators/web-stories-wp/pull/12578#issuecomment-1297293959 on a site just in case, just to ensure you're using the latest version.

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
Yesterday I tried with `12578 branch` on another test server instance by changing version via the web-stories tester - but I could NOT see the session key `wp_stories_autosave_story_NNNN` being deleted.

Thanks for the link to the ZIP file @swissspidy - when I load it on my test server and try the steps outlined by @miina I am not seeing any autosave calls after the first one.

Sorry, but I am unable to confirm this fix. Its probably something to do with my env/test steps. Since you are seeing the expected outcome, I recommend we merge this and I can test it out in the release candidate.

Cc: @bmattb

**Comment by swissspidy** [comment]
> but I could NOT see the session key wp_stories_autosave_story_NNNN being deleted.

Can you confirm you **do** see it being deleted now? Or still no?

> I am not seeing any autosave calls after the first one.

Well, did you make any new changes after the first autosave? We don't do any autosaves if there were no new changes, so it's expected to not see any if you don't make any changes.

**Comment by miina** [comment]
> Well, did you make any new changes after the first autosave? We don't do any autosaves if there were no new changes, so it's expected to not see any if you don't make any changes.

It should be possible to test this specific fix with just one autosave as well since the local backup is happening earlier in the QA environment, AFAIK. So the first autosave should already delete the local backup.

**Comment by kkalarickal** [comment]
Thanks for the suggestions @miina @swissspidy - I restested this from scratch and was able to verify the fix for 12578: i.e. local session backup is deleted when there is an autosave event

To do this, I had to first trigger a take over of the story while it was being edited via another browser session/login.

So the first user had the editor open to the story and had made changes which resulted in a local session key backup.

When the second user took over the story, there was an autosave event seen in the first user's session and that resulted in the local session backup key being deleted.

(in turn, the second user got a "restore from autosave version" message etc.).

I feel the 12578 branch that I tested with has some issue with the autosave not triggering .. i did make changes in the story off and on, with the hope that in 30 sec I would get the locla backup updated, and within 1 min or so, an autosave event would trigger.
But when I used `12578 branch` I was only able to see the local back up being updated, not the autosave event.. When I switched to `main branch` I was able to see the subsequent autosave events (but ofcourse, the deletion of the local session backup was not done).

Thank you for helping me go through this testing. I feel the 12578 change is working. I am not sure why the regular autosave is not triggering though.

**Comment by merapi** [comment]
For me, it removes the local backup after an autosave, but then creates it again - it shouldn't, right? there are no new changes.
Check from 1:15.

https://user-images.githubusercontent.com/21036224/200660306-1af0b08e-62bb-4699-8bcf-99d383ce202f.mov

**Comment by miina** [comment]
> For me, it removes the local backup after an autosave, but then creates it again - it shouldn't, right? there are no new changes.
> Check from 1:15.

And then it probably removes it again after auto-save happens.

Yep, there are no new changes since the autosave, however, there are new changes compared to the last saved story, so it would create a backup again, I guess.

Might be good to create a separate issue for that.

**Comment by swissspidy** [comment]
Yes we're seeing the same thing. That indeed shouldn't happen, it's strange. Especially since there's a `hasNewChanges` check in there.

**Comment by swissspidy** [comment]
> Might be good to create a separate issue for that.

💯

**Comment by miina** [comment]
> Yes we're seeing the same thing. That indeed shouldn't happen, it's strange. Especially since there's a `hasNewChanges` check in there.

`hasNewChanges` means having new changes compared to the last Save only. We're not tracking new changes based on the last autosave anywhere currently.

**Comment by kkalarickal** [comment]
Esactly @merapi . Thanks to some debugging commands that @swissspidy added, I am able to confirm that the local session key is in getting deleted, but there is another save local key event right after that which sort of restores it back into the browser.

- make changes
- store local autosave 206
- perform autosave
- delete local autosave 206
- store local autosave 206
- make changes
- store local autosave 206
- make changes
- store local autosave 206
- perform autosave
- delete local autosave 206
- store local autosave 206

so that last store local autosave happens after the delete and it sort of restores the session key back into the browser

**Comment by merapi** [comment]
> And then it probably removes it again after auto-save happens.

If I don't change anything there is no more autosave and it stays like that.

**Comment by swissspidy** [comment]
> > Yes we're seeing the same thing. That indeed shouldn't happen, it's strange. Especially since there's a `hasNewChanges` check in there.
> 
> `hasNewChanges` means having new changes compared to the last Save only. We're not tracking new changes based on the last autosave anywhere currently.

Ah, right, makes sense. Thanks for clarifying/reminding!

**Comment by swissspidy** [comment]
Merging this one for now :)

**Pull request merged**
