### PR TITLE
Adds images for two new ad templates.

### PR DESCRIPTION
**Pull request by divyarajmasani**
* Adds images for the new ad templates.
  * App Install
  * Annual Clothing Sale.

### CODE REVIEW

**Comment by swissspidy** [comment]
@divyarajmasani Please make sure the files are tracked in Git LFS (I just fixed the ones from yesterday). Refer to the documentation in `./docs` if unclear.

Also, can we perhaps keep the `ad-template` prefix on the directories? Makes it easier to distinguish from story templates.

**Comment by divyarajmasani** [comment]
> @divyarajmasani Please make sure the files are tracked in Git LFS (I just fixed the ones from yesterday). Refer to the documentation in `./docs` if unclear.
> 

Yes, One question for already committed files, i'll be running `git lfs migrate` and since our `.gitattributes` already has required config, I won't need to run it with import correct?

> Also, can we perhaps keep the `ad-template` prefix on the directories? Makes it easier to distinguish from story templates.

Will update the branch.

**Comment by swissspidy** [comment]
> > @divyarajmasani Please make sure the files are tracked in Git LFS (I just fixed the ones from yesterday). Refer to the documentation in `./docs` if unclear.
> 
> Yes, One question for already committed files, i'll be running `git lfs migrate` and since our `.gitattributes` already has required config, I won't need to run it with import correct?

Yeah `git lfs migrate import` and then maybe `git lfs push` should do the trick. But the pre-push Git hooks should warn you about that.

**Comment by divyarajmasani** [comment]
Updated to use `Git LFS`, 

Ran `migrate` and `push` the new files to LFS.

**Comment by swissspidy** [comment]
Did you push changes in this PR as well? Don't see any commits, and when going to "Files changed" it still shows the actual files, no indication of LFS

**Comment by divyarajmasani** [comment]
> Did you push changes in this PR as well? Don't see any commits, and when going to "Files changed" it still shows the actual files, no indication of LFS

There were some merge conflicts on my local branch, after resolving it I've squashed few commits and force pushed it to the branch, now the files show `Git LFS` tag.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
