### PR TITLE
Update original selectmenu with new custom dropdown

### PR DESCRIPTION
**Pull request by ndev1991**
Summary
Use new custom dropdown instead of default select box.

- [X] Design panel text style panel and font panel
- [X] Document panel select boxes to custom dropdown

Address issue #255  (Part of) :)
PS: I think font panel should be removed.

### CODE REVIEW

**Comment by miina** [comment]
> PS: I think font panel should be removed.

Font panel is removed within #412, it's just taking time to get merged.

**Comment by miina** [comment]
Should this be rebased against `shared-component/dropdown` instead? Currently, it seems to include both PR-s. Not clear which changes come from this PR only.

**Comment by miina** [comment]
Should `mask` panel also get the new dropdown? Even though doesn't seem like it's in the design at all, so perhaps not relevant.

Are you keeping the old `select` component for some specific reason?

**Comment by ndev1991** [comment]
Not needed. We can merged to original dropdown PR. #453

**Pull request closed without merging**
