### PR TITLE
REST API: Prime attachment caches all at once

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Discovered while working on other things. Instead of loading term and meta one at a time in the REST API, prime all caches in one go. This remove over half queries on editor. 

#### Before
Screenshot 2022-04-19 at 14 59 37

#### After
Screenshot 2022-04-19 at 14 59 50

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by spacedmonkey** [comment]
> Is it somehow possible to test the performance aspect of this at all, i.e. that the prime_post_caches method is being called and has an affect? Perhaps by comparing wpdb::get_num_queries() or something?

I thought about that, but what regression would that be testing? After we implement this functionality when will that number will hopefully never change. What is the point of run this test every time we make a php change? Does that test add value?

**Comment by swissspidy** [comment]
It's less about the exact number of queries but more about verifying that this change actually does prime the cache. So that we don't accidentally regress this again in the future.

**Comment by spacedmonkey** [comment]
> It's less about the exact number of queries but more about verifying that this change actually does prime the cache. So that we don't accidentally regress this again in the future.

But then we are testing `_prime_post_cache`? The logic we are creating, is just to get the ids that need to be primed, which tests already prove work. Once those ids are passed to `_prime_post_cache` it takes over.

**Comment by swissspidy** [comment]
Perhaps more testing that `_prime_post_cache` is called

I was just thinking that it would be too easy to introduce a regression here and wondering how we can prevent that.

If there's no good way to do that in WP then that's fine by me.

**Comment by spacedmonkey** [comment]
> If there's no good way to do that in WP then that's fine by me.

I can't find a good way to get test. Any query count maybe broken by newer versions of WP, as they may run another query. 
We know the ids that are being passed to the function, that is the best we can do.

**Review by swissspidy — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
