### PR TITLE
Media: Fix issue where images from the WP media modal are broken

### LINKED ISSUE #4023: Uploaded Image/Video Appears as Broken In Canvas
Activated PR#4012 - Win10/Chrome

- started new story
- selected Upload from Media section
- Browsed to local folder and selected Image
- image loads in Media Gallery tab
- Selected "Insert into page"
- Image appears as broken on canvas

Video: https://drive.google.com/file/d/1fcyqu3uZ5ymOWryZ_UPsN5xKWzsZKh5R/view

### PR DESCRIPTION
**Pull request by diegovar**
## Summary

Fixes the issue where images added from the WP media gallery don't display (due to the `sizes` missing source_url).

## Relevant Technical Choices

The getResourceFromMediaPicker was passing the `sizes` object directly from the picker, which uses `url` instead of the expected `source_url`.

## Testing Instructions

This should fix #4023 so following the steps outlined there should suffice.

---

Fixes #4023

### CODE REVIEW

**Review by joannag6 — APPROVED** [review]
This didn't fail any tests?

**Comment by diegovar** [comment]
> This didn't fail any tests?

This is the flow where you open the WP media gallery and select an image from there. Doesn't seem like it. I'll investigate how hard it is to add a test, but I'd like to merge this as this is a pretty bad breakage.

**Comment by joannag6** [comment]
Maybe open another bug / PR to add a test for this?

**Comment by swissspidy** [comment]
Actually, there is an E2E test for this, but it apparently doesn't catch this issue. Opened #4052 to improve that.

However, might be worth adding unit tests for all the `getResourceFrom*` functions or something. Leaving that up to you. But shouldn't rely only on the E2E test.

**Pull request merged**
