### PR TITLE
Template Updates: Wellbeing

### LINKED ISSUE #6976: Template Updates: Wellbeing
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 |  Logo updated to fly in; remove animation on image. **Headline to fly in**  |  For all frames, only use 3 blob shapes to create less shape in library.  |
| 2 | Quote mark update to Fly in; **Byline to fly in** | N/A |
| 3 |  Text area updated to fly in; remove animation on learn more. **Headline to fly in**   |  Combine arrow shape.  |
| 4 |  Remove animation on headline; Update circles to Pulse.  | Combine arrow shapes? Increase tappable shapes. (this image has branding in it, is that ok? has this always been here?) |
| 5 | Remove animation on learn more; text area updated to Fly in. **Headline to fly in**  | Combine arrow shape (same arrow as wellbeing 3)  |
| 6 |  All text updated to fly in; remove animation on white rectangle.  | N/A  |
| 7 | **Text and Number to fly in**  | N/A  |
| 8 | Text area updated to fly in; remove animation on learn more. **Headline and number to fly in**  | Combine arrow shape (same as wellness 3); Move yellow shape to the right;   |
| 9 |  All updated to fly in.  | move blue shape down a little.  |
| 10 | Remove animation on headline; update images and text next to them to fly in. | N/A  |
 
See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Part of 1.7 release is updating existing templates to avoid custom animations and unnecessary prepublish checklist suggestions.

## Summary

Wellbeing Template revisions 
- remove custom animations and replace them with effects available in editor 
- add arrows and cta circle as stickers
- adjust blob shapes as directed 

## Relevant Technical Choices

Used my own judgement for what direction everything should fly in. 

## To-do

- [x] Design Review

## User-facing changes

See figma for revised template: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7357%3A546501
List of changes can be found here: https://github.com/google/web-stories-wp/issues/6976

**Before**

https://user-images.githubusercontent.com/10720454/114105754-39edfa80-9882-11eb-8288-a355157f51ef.mp4

**After**

https://user-images.githubusercontent.com/10720454/114104162-3442e580-987f-11eb-8363-dcbaebe41657.mp4

## Testing Instructions

Use the wellbeing template from dashboard/explore templates and see that the template has been updated in line with Figma. There should be no more custom animations and PPC suggestion about clickable link element size should be resolved on page 4.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6976

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
Everything looks good. I'm still seeing some unsupported rotation animations on the blobs on page 1 & 2. Are those meant to be kept?

**Review by samwhale — APPROVED** [review]
This looks great, just a couple of questions:

1. Should this background animation be removed?

2. I think the arrow sticker here needs to be white
Screen Shot 2021-04-12 at 12 05 21 PM

**Comment by BrittanyIRL** [comment]
> This looks great, just a couple of questions:
> 
> 1. Should this background animation be removed?
> 
Yes! Those should be gone now, i missed a few of 'em earlier. 

> 
> 2. I think the arrow sticker here needs to be white
> Screen Shot 2021-04-12 at 12 05 21 PM

It should be white now: 
Screen Shot 2021-04-12 at 3 45 05 PM

**Comment by ivayloklissarov** [comment]
Small fixes to do:

Overall
- All animation durations are too quick. Let's change all of them to 2000ms

Page 1
- Remove logo animation
Screen Shot 2021-04-13 at 4 20 09 PM

Page 8
- Remove animation from number 3
Screen Shot 2021-04-13 at 4 18 36 PM

Page 9
- Remove animation from title and numbers
Screen Shot 2021-04-13 at 4 18 45 PM

**Comment by BrittanyIRL** [comment]
Thanks! 

> Overall
> 
> * All animation durations are too quick. Let's change all of them to 2000ms

Updated! 

> Page 1
> 
> * Remove logo animation

wellbeing page 1

> Page 8
> 
> * Remove animation from number 3
> 

wellbeing page 8

> Page 9
> 
> * Remove animation from title and numbers

wellbeing page 9

**Comment by BrittanyIRL** [comment]
(Percy's having issues right now and won't let us log in, the visual diff that it is catching is an intentional update of the template).

**Pull request merged**
