### PR TITLE
Implemented new filter for categories and tags to story block

### PR DESCRIPTION
**Pull request by WebediaDev**
## Context

Two more filters are to be added to the story block (latest stories).

## Summary

It would be nice to have support to the custom taxonomies “web_story_category” and "web_story_tag" for story block.
The displayed stories should be limited to the selected categories/tags.

See also:
https://wordpress.org/support/topic/feature-new-block-type-to-support-categories/

## Relevant Technical Choices

The component /packages/stories-block/src/block/components/authorSelection.js was used as a model and two more components (categorySelection.js & tagSelection.js) were added. The block attributes and the PHP method `get_query_args` were adjusted accordingly .

## To-do

The components authorSelection.js, categorySelection.js and tagSelection.js are very similary.
Maybe it would be a good idea to unify them in the future.

Translations for two new phrases:
- __('Tags', 'web-stories')
- __('Categories', 'web-stories')

## User-facing changes

In the story block (latest stories), two additional filters for categories and keywords have been added below the filter for authors.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Compile sources and modify plugin.
2. Select story block with variation "latest stories".
3. Select a category/tag similar to the author filter.

The block should display the filtered stories in Gutenberg and after saving on frontend.

### Does this PR have a security-related impact?

No.

### Does this PR change what data or activity we track or use?

No.

### Does this PR have a legal-related impact?

No.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

### CODE REVIEW

**Comment by swissspidy** [comment]
Oh wow, thanks a lot for your contribution! Just note that we cannot accept it just yet because of the missing CLA.

Also, ideally this implementation is **taxonomy-agnostic** and not hardcoded to the `web_story_category` and `web_story_tag` taxonomies. There are publishers which add custom taxonomies and would want to use those too for filtering. Take the Query Loop block as an example.

Some relevant code there:

https://github.com/WordPress/gutenberg/blob/ce37fe9ee88bfb4afba26126b8bde8a95ee5000e/packages/block-library/src/query/utils.js#L113-L133

https://github.com/WordPress/gutenberg/blob/ce37fe9ee88bfb4afba26126b8bde8a95ee5000e/packages/block-library/src/query/edit/inspector-controls/taxonomy-controls.js#L36-L125

Then there will be no duplicated components and no issues with translatable labels or anything.

**Comment by WebediaDev** [comment]
Hello again, I have agreed the Google CLA.

**Comment by swissspidy** [comment]
Thanks. Would you also be interested in helping to make this taxonomy-agnostic? If not, we might be able to take over from here

**Comment by WebediaDev** [comment]
Currently I do not have resources/time to help with the taxonomy issue.

**Comment by swissspidy** [comment]
I'm closing this for now since this would need to be written in a taxonomy-agnostic way. We'll keep track of your helpful work though in #8897 so that we can hopefully build upon it when we start working on this feature. Thanks again for your contribution!

**Pull request closed without merging**
