### PR TITLE
Block: Fix carousel width & whitespace issues

### LINKED ISSUE #12170: Block: carousel layout responsiveness issues
## Bug Description

Most notably on Firefox on smaller screens, the Glider track width calculation is quite off, causing white space to appear at the beginning of the carousel.

## Steps to Reproduce

1. Add Web Stories block with carousel layout, make sure there are plenty of stories in it
2. View in Firefox w/ small viewport
3. Notice huge gap

## Screenshots

Screenshot 2022-08-29 at 11 45 40

## Additional Context

- Plugin Version: 1.24.0
- WordPress Version: 6.0.1
- Operating System: macOS
- Browser: Firefox

### LINKED ISSUE #12563: Block: Broken carousel layout
## Bug Description

Small regression from #12469 when using a carousel layout

## Screenshots

Screenshot 2022-10-31 at 10 02 25

## Additional Context

- Plugin Version: 1.26.0
- WordPress Version: 6.0
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

This PR fixes two issues:

First, the Glider track width calculation was quite off, causing white space to appear at the beginning of the carousel. Noticeable mostly on Firefox, but also on Chrome.

## Summary

Fixes a regression with the carousel layout in v1.26.0.

Also avoids unnecessary whitespace at the beginning of the carousel

## User-facing changes

**Whitespace issue**

See: https://www.youtube.com/watch?v=dCpdV3PurC0

**Width issue**

Before:

Screenshot 2022-10-31 at 10 02 25

After:

Screenshot 2022-10-31 at 10 05 42

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a new Web Stories block to a post, make sure there are plenty of stories in it.
2. Use the grid carousel and circle carousel layout options
3. View in Firefox w/ small viewport (+ large ones to ensure backwards compat)
4. Previous gap should be fixed
5. Carousel should be displayed properly in full width

For completeness sake, also test other layout options to see if there are no regressions.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12563
Fixes #12170

### CODE REVIEW

**Comment by spacedmonkey** [comment]
So this is a revert of - https://github.com/GoogleForCreators/web-stories-wp/pull/12469? What about this issue?

How about lowering the min width? Would this help the issue?

**Comment by spacedmonkey** [comment]
Maybe just add min width of in carousel is set.

**Review by spacedmonkey — APPROVED** [review]

**Comment by kkalarickal** [comment]
Confirmed the issue in `main branch`

And the fix in `12564 branch`

**Comment by kkalarickal** [comment]
Further test conducted:
- changed the portrait/landscape orientation of the circle carousel
- added other types of carousels (box, grid, list) to confirm there are no regressions
- tested on Firefox/Chrome
- changed the circle size for the circular carousel
- increased the number of stories in the circle carousel

**Pull request merged**
