### PR TITLE
Bugfix: Link URLs default to https instead of http

### LINKED ISSUE #6261: Link URLs default to http instead of https
## Bug Description

When using the Link feature on a object within the editor, the URL displayed and used by the system is always defaulting to http and not https as we would now expect in 2021

## Expected Behaviour

I would think that any automagic URL prepending would default to https not http

## Steps to Reproduce

1. Select an object to add a link to in the editor
2. Enter a URL such as google.com
3. Watch as the the data entered in the "web address" field is prepended with the incorrect protocol

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #6469: Redesign: Update layer style panel
## Feature Description
See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A157584)

- [x] Update the input

## Additional Context
Screenshot 2021-02-22 at 12 44 31

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### LINKED ISSUE #6494: Redesign: Generic URL input field component
## Feature Description

See [Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A198519)

- [ ] Move URL input to design-system (including the URL parsing logic)
- [ ] Update storybook
- [ ] Use in element link panel
- [ ] Use in page attachment panel
- [ ] Default to `https://` rather than `http://` (#6261)

Note: this is just for the URL input separately.

## Additional Context
Screenshot 2021-02-23 at 19 15 27

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Two tickets here:
- #6494: 'move link input to design system'. IMO this isn't necessary because we already have the base input in the design system. Any formatting and special functionality can be added external to the input.
- #6261: 'set default to `https` instead of `http`

## Summary

Fixes default for url prefix to `https`

## Relevant Technical Choices

I don't believe we need to move the `LinkInput` to the design system. It's built off of the base `Input` component. If you disagree let me know and I'd be happy to move it. Brought it up in slack here too: https://xwp.slack.com/archives/CCCAUAH6F/p1616087809013300

## To-do

none

## User-facing changes

`https` is now the default prefix when parsing a url.

|Before|After|
|--|--|
|old-url-input|new-url-input|

## Testing Instructions

1. Look in storybook under Stories Editor -> Form -> Link. The link input should prefix a string like `test.com` with `https://`.
2. Try in the editor too in the permalink panel.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Look in storybook under Stories Editor -> Form -> Link. The link input should prefix a string like `test.com` with `https://`.
2. Try in the editor too in the permalink panel.

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6494 
Fixes #6261

### CODE REVIEW

**Review by miina — APPROVED** [review]
LGTM!

This Karma test also needs updating now: `should add protocol automatically on blurring`.

**Review by BrittanyIRL — APPROVED** [review]
👍

**Review by embarks — APPROVED** [review]

**Review by maxyinger — APPROVED** [review]

**Comment by swissspidy** [comment]
@csossi This one has been sitting in ready-for-QA for 3 weeks now. Any chance you could help bring this over the finish line? Thanks.

@samwhale FYI there are now some merge conflicts.

**Review by swissspidy — APPROVED** [review]
Did QA myself now. Looks good.

**Pull request merged**
