### PR TITLE
Dashboard: Updated Entertainment template to 9:16

### LINKED ISSUE #2474: Templates: Update Entertainment templates to 9:16
Use this Figma doc to apply 9:16 updates to the existing `Entertainment` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR applies the 9:16 ratio updates to the Entertainment template.

## To-do

The ratio change in design means the preview story cards will have to be updated from 2:3 to 9:16 which will happen in another PR.

## User-facing changes

The Entertainment templates has multiple tweaks and layout updates.

## Testing Instructions

1.) Go to "Explore Templates"
2.) Click on the "Entertainment" template.
3.) Click on each page in the detail view and make sure they look good like the updated designs found in this [Figma doc](https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61).

Fixes #2474

### CODE REVIEW

**Comment by dvoytenko** [comment]
@mariano-formidable few questions here.

1. Are we still not using `migrate` for templates? I thought we got that in already... Or are you just trying to upgrade them?
2. Are you using some tool to upgrade? I believe @swissspidy had some outline of auto-converter for our templates.
3. Nit, but to clarify: we are still on 2:3 and will remain so, I believe. 9:16 is the fullbleed aspect ratio and it's also unchanged. So aspect ratio is the same. Only the max x/y data units have changed.

**Comment by mariano-formidable** [comment]
> @mariano-formidable few questions here.
> 
> 1. Are we still not using `migrate` for templates? I thought we got that in already... Or are you just trying to upgrade them?
> 2. Are you using some tool to upgrade? I believe @swissspidy had some outline of auto-converter for our templates.
> 3. Nit, but to clarify: we are still on 2:3 and will remain so, I believe. 9:16 is the fullbleed aspect ratio and it's also unchanged. So aspect ratio is the same. Only the max x/y data units have changed.

Oh, this is PR is _not_ about migrating to the latest version.  That is already being done automatically.

This PR is to update (not upgrade) the layout of the Entertainment templates based on new design updates that Sam made.  However, she forgot to take into account the 2:3 safe-zone viewable area so she's going to do another round of design tweaks for us to apply to this (and the other templates too).

And yes, I think we all got confused with the aspect ratio because the new design updates were specifically for 9:16, but now I think we're all on the same page to support the 2:3 design as the default.

**Comment by dvoytenko** [comment]
> And yes, I think we all got confused with the aspect ratio because the new design updates were specifically for 9:16, but now I think we're all on the same page to support the 2:3 design as the default.

Yes, safe-vs-fullbleed zones are pretty confusing. Feel free to ping me on Slack if you need to discuss. In a nutshell, the rules are:

1. A 2:3 safe container is placed and centered inside a 9:16 fullbleed container. The safe container is thus as wide as the fullbleed conainer, but shorter. So it's centered vertically only.
2. The UnitsProvider is set to the size of the 2:3 safe container.
3. Then display elements should do the rest themselves.
4. 9:16 should have overflow:hidden. 2:3 should have overflow:visible.

**Comment by mariano-formidable** [comment]
Duplicate, this work is being addressed by this [PR](https://github.com/google/web-stories-wp/pull/2603)

**Pull request closed without merging**
