### PR TITLE
Jetpack: Metadata Duplication

### LINKED ISSUE #4913: Jetpack: Metadata Duplication
## Feature Description

This is a follow-up to #3092

While that one works great, it results in duplicate Open Graph tags being printed because Jetpack does not remove existing ones.

Seems like they'd need to do this:

```php
$instance = Google\Web_Stories\get_plugin_instance()->discovery;
\remove_action( 'web_stories_story_head', [ $instance, 'print_open_graph_metadata' ] );
\remove_action( 'web_stories_story_head', [ $instance, 'print_twitter_metadata' ] );
```

Not sure if they're open to do this.

Alternatively we remove those two actions if we detect Jetpack.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

If jetpack plugin remove web stories own metadata. 

## Relevant Technical Choices

It felt cleaner to do the removal of web stories meta data, in this plugin and not in jetpack. 

I had to do some clever workaround with filter and actions priorities to get this working. 

## Testing Instructions

---

Fixes #4913

### CODE REVIEW

**Comment by swissspidy** [comment]
> It felt cleaner to do the removal of web stories meta data, in this plugin and not in jetpack.

I don't think I agree with that. I had a follow-up to https://github.com/Automattic/jetpack/pull/17399 in mind that does this in `functions.opengraph.php`:

```diff
-add_action( 'web_stories_story_head', 'jetpack_og_tags' );
+add_action( 'web_stories_story_head', 'jetpack_og_tags' );
+remove_action( 'web_stories_story_head', array( Google\Web_Stories\get_plugin_instance()->discovery, 'print_open_graph_metadata' ) );
+remove_action( 'web_stories_story_head', array( Google\Web_Stories\get_plugin_instance()->discovery, 'print_twitter_metadata' ) );
```

That seems quite clean?

**Comment by spacedmonkey** [comment]
> I don't think I agree with that. I had a follow-up to Automattic/jetpack#17399 in mind that does this in functions.opengraph.php:

We are at an impasse it seems. I personally believe that we should have keep control of the integration on our side, giving us more control and making it easier for us to refactor later. What for example would happen, if we wanted to remove this method or move it to another class? It means that every time we change something, creating a PR to jetpack. Also, what happens, if we do change something and the user do not update the jetpack plugin. 

A cleaner solution might be adding this to our plugin 
```           
        if ( apply_filters( 'web_stories_enable_open_graph', true ) ) {
		add_action( 'web_stories_story_head', [ $this, 'print_open_graph_metadata' ] );
		add_action( 'web_stories_story_head', [ $this, 'print_twitter_metadata' ] );
        }
```

Thoughts?

**Comment by swissspidy** [comment]
> A cleaner solution might be adding this to our plugin

Indeed that might be cleaner! 👍

**Comment by spacedmonkey** [comment]
Closing this in favour of https://github.com/google/web-stories-wp/pull/5312

**Pull request closed without merging**
