### PR TITLE
Fix PHP-CSS-Parser patching

### LINKED ISSUE #5081: AMP Sanitization breaks gradients (again)
## Bug Description

This is essentially #4529, but now the other way around:

When _not_ using the AMP plugin, gradients will be stripped on the frontend.

The reason is a bug in PHP-CSS-Parser, which the AMP plugin solves by patching the package.

Since we cannot just let the AMP plugin deal with the patches because of https://github.com/cweagans/composer-patches/issues/315, we copied all the patches to our repo.

However, the `patches` section was accidentally omitted.

But even with that set I'm currently getting issues with patches not applying cleanly.

So this needs some investigation.

## Expected Behaviour

PHP-CSS-Parser patches should be applied cleanly.

## Steps to Reproduce

1. Apply gradient to element
1. Notice that gradient disappears on frontend.

Workaround: install AMP plugin.

## Additional Context

- Plugin Version: 1.1.0
- Operating System: macOS
- Browser: Chrome 86

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Fixes broken CSS gradients.

## Relevant Technical Choices

Originally, I simply wanted to use `"enable-patching": true`, but that doesn't work because of https://github.com/cweagans/composer-patches/issues/315

(cc @westonruter maybe the Composer patches in the plugin could use patches from GitHub instead of locally provided ones?)

Then, I wanted to do `"enable-patching": false` and simply provide `"patches": { ... }` myself, but that didn't work - `enable-patching` is ignored when patches are provided.

So the correct way is to provide `patches-ignore` to ignore the AMP plugin's patches in favor of our own patches declaration.

Next, I learned that `patches/php-css-parser-pull-185.patch` cannot be applied for some reason (`Could not apply patch! Skipping. The error was: Cannot apply patch patches/php-css-parser-pull-185.patch`).

Since that patch doesn't seem critical for us, I simply removed it from the patches list.

**Aside:**

I wanted to use version 1.7 of the `cweagans/composer-patches` as it has a different structure and Composer 2 support, but the AMP plugin requires 1.6.x, so that doesn't work.

## User-facing changes

Gradients are back!

## Testing Instructions

1. Apply gradient to element
1. Notice that gradient no longer disappears on frontend.

---

Fixes #5081

### CODE REVIEW

**Comment by westonruter** [comment]
> maybe the Composer patches in the plugin could use patches from GitHub instead of locally provided ones?

The reason for this I recall is to guard against a situation where the repo fork gets deleted or the branch is removed.

**Comment by swissspidy** [comment]
> > maybe the Composer patches in the plugin could use patches from GitHub instead of locally provided ones?
> 
> The reason for this I recall is to guard against a situation where the repo fork gets deleted or the branch is removed.

Ah, interesting. Not sure about the fork-getting-deleted part, a URL like `https://github.com/wp-media/wp-rocket/pull/3245.patch` still works even though my branch does not exist anymore. And I bet it still works when I delete my fork.

**Comment by westonruter** [comment]
Is the thinking that using a remote patch file will facilitate keeping it updated?

cc @pierlon

**Comment by swissspidy** [comment]
> Is the thinking that using a remote patch file will facilitate keeping it updated?

That, and it would help work around https://github.com/cweagans/composer-patches/issues/315 because we'd no longer have to copy the patches from the amp-wp repo to this one.

**Comment by westonruter** [comment]
Got it. @pierlon What do you think about going back to using remote patches?

**Comment by pierlon** [comment]
The patches currently employed by the amp-wp are from currently open PRs, so if we were to use remote patches there is a possibility of them being remotely updated if someone were to push to the relevant forked repo.

Alternatively, maybe we could create a PR on amp-wp with those patches and then use that as the remote patch. Thoughts @swissspidy  @westonruter?

**Comment by westonruter** [comment]
> Ah, interesting. Not sure about the fork-getting-deleted part, a URL like `https://github.com/wp-media/wp-rocket/pull/3245.patch` still works even though my branch does not exist anymore. And I bet it still works when I delete my fork.

@pierlon apparently the patch URLs persist even after the PR is closed and even when the fork is deleted, per Pascal above.

**Comment by pierlon** [comment]
Right but it would be possible to push commits to the PR while it's open, thus updating the referenced remote patch. The example Pascal referred to (`https://github.com/wp-media/wp-rocket/pull/3245.patch`) would be an exception since the PR has already been merged.

**Comment by westonruter** [comment]
On one hand that is a good thing since it means it would be easy to update the patch (as in the case of a conflict). On the other hand, this means that the version is not explicitly indicated in the `composer.json`. 

We could mitigate this by linking to the patch for a specific commit, rather than a PR. For example: https://github.com/wp-media/wp-rocket/commit/1b47bb97f9e7acdaaf8b66f44391fe2481a7293e.patch

For example, for your PR: https://github.com/sabberworm/PHP-CSS-Parser/pull/193. Instead of linking to <https://github.com/sabberworm/PHP-CSS-Parser/pull/193.patch>, we could instead link to: https://github.com/sabberworm/PHP-CSS-Parser/compare/d9d0190c2c29946aac93375ca05df2d48329d6d7%5E...0ff0e38629b5ba96ae3b8368385974b1ebee9acb.patch

This includes the same commits in your PR: https://github.com/sabberworm/PHP-CSS-Parser/compare/d9d0190c2c29946aac93375ca05df2d48329d6d7%5E...0ff0e38629b5ba96ae3b8368385974b1ebee9acb

So then if the PR gets updated, then we'd need to update the commit hashes in the `composer.json`.

**Comment by pierlon** [comment]
> Instead of linking to https://github.com/sabberworm/PHP-CSS-Parser/pull/193.patch, we could instead link to: https://github.com/sabberworm/PHP-CSS-Parser/compare/d9d0190c2c29946aac93375ca05df2d48329d6d7%5E...0ff0e38629b5ba96ae3b8368385974b1ebee9acb.patch

Hmm yea that makes sense. In that case I'm on board with using remote patches then.

**Comment by pierlon** [comment]
@swissspidy `cweagans/composer-patches` will be updated to v1.7.0 in https://github.com/ampproject/amp-wp/pull/5554 and I've opened a PR to switch to using patches from GitHub in https://github.com/ampproject/amp-wp/pull/5556.

**Comment by spacedmonkey** [comment]
As https://github.com/ampproject/amp-wp/pull/5556 has been merged, I think we are safe to merge. 

I will approve after merge conflict is resolved.

**Comment by swissspidy** [comment]
@spacedmonkey conflicts resolved!

**Review by spacedmonkey — APPROVED** [review]
👍

**Pull request merged**
