### PR TITLE
Change "Remove as background" to "Detach from background"

### LINKED ISSUE #1915: Update Verbiage from Remove As Background to Detach From Background
## Acceptance Criteria
1. Update Verbiage from Remove As Background to Detach From Background

### PR DESCRIPTION
**Pull request by miina**
## Testing Instructions

1. Add an image
2. Set as background
3. Verify that the button that was previously "Remove as background" now says "Detach from background"

---

Fixes #1915

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]
LGTM!

**Comment by swissspidy** [comment]
Don't think we need additional QA for such a simple fix. I just tested it and it works as expected 👍

**Comment by barklund** [comment]
Didn't any tests (unit or karma) refer to this button by text or accessible name? Well, that's clearly a missed opportunity for testing there. I guess I only tested _setting_ background in a few files - never _removing_ using this detach button.

**Comment by miina** [comment]
Apparently no, there were no tests related to the text. I actually just assumed that something else was used for testing this button (since there are tests for background). Should have double-checked!

**Pull request merged**
