### PR TITLE
Story Ad Tool: Ad assets for new ad template

### PR DESCRIPTION
**Pull request by divyarajmasani**
Adds a single GIF for new ad template being added to the ad creation tool.

PR for the Ad Template: https://github.com/rtCamp/web-stories-ad-tool/pull/41

### CODE REVIEW

**Comment by swissspidy** [comment]
Can we convert this to a video instead? It's quite a large GIF (800KB)

**Comment by divyarajmasani** [comment]
> Can we convert this to a video instead? It's quite a large GIF (800KB)

Let me confirm why the GIF was used with the design team and will update here accordingly.

**Comment by divyarajmasani** [comment]
@swissspidy 

They tried video prior to using GIF, but the issue was that with video the story was showing `equalizer` icon at the bottom right corner. And that's what design didn't want to show as it's just simple images and no audio.

I believe I we have the ability to set `noaudio` attributed on the videos in editor this icon won't be shown as per the docs.
> https://github.com/ampproject/amphtml/blob/main/extensions/amp-video/amp-video.md#noaudio

But, right now we do not have that options in editor.

**Comment by swissspidy** [comment]
Got it. Yeah this is something we're planning on adding in #7730 and #7885.

For the story ad tool, we should just go ahead and implement this already. Should be trivial to do.

Basically, the video resource in the templates JSON file could have an `isMuted` property, and then `video/output.js` would set `noaudio` accordingly.

We can then later backport this enhancement to this repository.

**Comment by divyarajmasani** [comment]
> For the story ad tool, we should just go ahead and implement this already. Should be trivial to do.

Sure, I'll take this back to engineering. Thank you for pointers for the implementation.

**Comment by divyarajmasani** [comment]
@swissspidy 
Removed `.gif` and added optimised video instead for the ad template.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
