### PR TITLE
Static Site: Add Template Poster Assets 

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

We're updating the dashboard's explore templates view to use screenshots instead of load every template as a story. 

## Summary

- Follow up from #8693  
- Adds screenshots for every page of every template 

## Relevant Technical Choices

screenshots are stored in each template subdirectory of images by page number. 

## User-facing changes

None

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Partially addresses #8373

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]

**Review by samwhale — APPROVED** [review]

**Comment by swissspidy** [comment]
@BrittanyIRL @choumx Should we perhaps only serve these images as WebP?

For example `12-hours-in-barceolona/posters/4.png` in this PR is 1.3MB big. When converted to WebP it's only 129KB - that's a 90% reduction!

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL @choumx Should we perhaps only serve these images as WebP?
> 
> For example `12-hours-in-barceolona/posters/4.png` in this PR is 1.3MB big. When converted to WebP it's only 129KB - that's a 90% reduction!

I like that idea, but i think we still need the `png` version as well because WebP is still not completely supported (we ran into this with the helpcenter) https://caniuse.com/webp

**Comment by BrittanyIRL** [comment]
> > @BrittanyIRL @choumx Should we perhaps only serve these images as WebP?
> > For example `12-hours-in-barceolona/posters/4.png` in this PR is 1.3MB big. When converted to WebP it's only 129KB - that's a 90% reduction!
> 
> I like that idea, but i think we still need the `png` version as well because WebP is still not completely supported (we ran into this with the helpcenter) https://caniuse.com/webp

Alright :) Added WebP as a follow up PR here: https://github.com/google/web-stories-wp/pull/8737 - I just can't bring myself to have a PR with a diff over 1k files changed, that's just hard to swallow (as it is it's so big). 😱

**Comment by swissspidy** [comment]
@BrittanyIRL Just for reference, do you recall the issues with the Help Center?

WebP is supported by all browsers we officially support, for Safari it just means on newer OS versions, but I'd say that's negligible.

Adding WebP versions in addition to PNG is of course the safest route

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Just for reference, do you recall the issues with the Help Center?

ok so it was actually `webm` (which makes more sense given the nature of the help center) https://github.com/google/web-stories-wp/pull/6371/files. Totally on me for moving a little too quickly here. 

the png is probably overkill, i'll happily admit my misstep. 

I can clean out the pngs if we want to clear space in our assets and just use webm - see about converting the screenshots automatically too. I just want to move on the dashboard side of things at the same time, which merging this enabled me to do.

**Comment by dreamofabear** [comment]
Assuming GA's operating system reporting is correct, over 90% of our Mac users are on Catalina or older. So I think we need a fallback.

> For example 12-hours-in-barceolona/posters/4.png in this PR is 1.3MB big

The fallback for this and photo-type images (vs. icons) should probably be JPEG.

**Comment by swissspidy** [comment]
If we want WebP with fallback to either PNG or JPEG depending on the image type that‘s gonna complicate things a little bit. Basically have to store the file names in the metadata.

**Comment by BrittanyIRL** [comment]
> If we want WebP with fallback to either PNG or JPEG depending on the imsge type that‘s gonna complicate things a little bit. Basically have to store the file names in the metadata.

Let's follow up with the fallback to keep this "5 point" issue from truly exploding. I'll make a ticket later today.

**Comment by BrittanyIRL** [comment]
Ok, came back around to this - was doing too many things at the same time this week. 

Fallback is handled in #8747 
https://github.com/google/web-stories-wp/blob/5d815d2b5d886f8ef55c57cce5790a186c668c45/packages/dashboard/src/app/views/exploreTemplates/content/templateGridItem.js#L76-L80

**Pull request merged**
