### PR TITLE
Call `setup_new_site()` upon plugin activation

### LINKED ISSUE #7488: Site Setup logic not run uon plugin activation
## Bug Description

Upon plugin activation, we used to run our own `setup_new_site()` function to ensure capabilities were added and that the database upgrader runs.

However, that since to have gone missing in 1.6.0.

## Expected Behaviour

Capabilities should be added upon plugin registration, database upgrader should run

## Steps to Reproduce

1. Install plugin on fresh site
2. Notice that "Stories" admin menu is not visible due to lack of capabilities

## Additional Context

- Plugin Version: 1.6.0 / 1.7.0-rc.1
- WordPress Version: 5.7
- Operating System: macOS
- Browser: Chrome

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Site setup logic was not being run during plugin activation

## Summary

Adds back the `setup_new_site()` call we had here previously.

## To-do

* Investigate why e2e tests didn't catch this.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Install plugin on a fresh site (locally, or Jurassic Ninja or similar)
2. Activate plugin
3. Verify the "Stories" admin menu item is visible
4. Verify the DB upgrader did run by checking the DB version in `wp_options` / `wp-admin/options.php`

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7488

### CODE REVIEW

**Review by spacedmonkey — APPROVED** [review]
👍

**Comment by spacedmonkey** [comment]
Wow, I don't know how I missed this. Instead of needing this function, I have these two todos. 

https://github.com/google/web-stories-wp/blob/ee98d46ddfec1c1224ca450980e3d896aa8c4678/includes/namespace.php#L47

https://github.com/google/web-stories-wp/blob/ee98d46ddfec1c1224ca450980e3d896aa8c4678/includes/namespace.php#L53

I will create a follow up ticket. Sorry I didn't do this earlier.

**Comment by spacedmonkey** [comment]
Seems like i already did some of this work.

https://github.com/google/web-stories-wp/blob/ee98d46ddfec1c1224ca450980e3d896aa8c4678/includes/Database_Upgrader.php#L104-L112

https://github.com/google/web-stories-wp/blob/ee98d46ddfec1c1224ca450980e3d896aa8c4678/includes/User/Capabilities.php#L40-L48

**Comment by spacedmonkey** [comment]
Looking at this closely,  I think that this would be a better solution.

**Comment by swissspidy** [comment]
We need something simple now; #7494 can be looked at after release

**Comment by swissspidy** [comment]
> Seems like i already did some of this work.
> 
> https://github.com/google/web-stories-wp/blob/ee98d46ddfec1c1224ca450980e3d896aa8c4678/includes/Database_Upgrader.php#L104-L112

Only runs on `admin_init`, so never executed in a WP-CLI context.

> https://github.com/google/web-stories-wp/blob/ee98d46ddfec1c1224ca450980e3d896aa8c4678/includes/User/Capabilities.php#L40-L48

Not a service, so this method will never be run

**Pull request merged**
