### PR TITLE
Remove currently on-by-default flags

### PR DESCRIPTION
**Pull request by diegovar**
## Summary

Remove features that are currently default: true in the fixture, so that we properly test it.

## To-do

It's not ideal that the source of truth of which features are on is scattered across Experiments.php, the fixture and many tests (search for uses of FlagsProvider). Ideally they should be centralized in such a way that the PHP and JS flags are autogenerated from the same source (a json file?)

### CODE REVIEW

**Comment by swissspidy** [comment]
> It's not ideal that the source of truth of which features are on is scattered across Experiments.php, the fixture and many tests (search for uses of FlagsProvider). Ideally they should be centralized in such a way that the PHP and JS flags are autogenerated from the same source (a json file?)

Once a feature becomes on-by-default, we should just remove the flag everywhere, no?

**Comment by diegovar** [comment]
> > It's not ideal that the source of truth of which features are on is scattered across Experiments.php, the fixture and many tests (search for uses of FlagsProvider). Ideally they should be centralized in such a way that the PHP and JS flags are autogenerated from the same source (a json file?)
> 
> Once a feature becomes on-by-default, we should just remove the flag everywhere, no?

Good point. In server land you usually leave them around for a while to easily disable them if it breaks users, but in our case that doesn't happen.

**Comment by diegovar** [comment]
I've modified this PR to remove them completely.

**Comment by swissspidy** [comment]
> In server land you usually leave them around for a while to easily disable them if it breaks users, but in our case that doesn't happen.

I suppose we could leave them around until the next planned release, and then remove them before doing the release.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
