### PR TITLE
Quick Action Menus: Remove Newly Redundant Actions

### LINKED ISSUE #10639: UI Simplification: Floating menu: Remove duplicate items from quick-action menu
## Feature Description

Remove duplicate items from quick-action menu:

- From text element, remove: Change Color; Edit Text
- From shape element, remove: Change Color
- From video, remove: Trim

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

New floating menus make some of the quick actions redundant. 

## Summary

Remove duplicated actions from quick actions menu where needed now that we have the floating element menu. These are: Text element (change color, edit text), Shape element (change color), Video element (trim).

## Relevant Technical Choices

This is just removing code. 

## User-facing changes

| Menu | This Branch | Main | 
| -- | --- | --- | 
| Text Element | Screen Shot 2022-03-03 at 9 59 34 AM |  Screen Shot 2022-03-03 at 11 46 48 AM |
| Shape Element | Screen Shot 2022-03-03 at 9 59 45 AM | Screen Shot 2022-03-03 at 11 46 55 AM | 
| (local) Video |  Screen Shot 2022-03-03 at 11 47 21 AM | Screen Shot 2022-03-03 at 11 46 40 AM |

## Testing Instructions

Verify that the following quick actions are removed: 

- Text element: Change Color; Edit Text
- Shape element: Change Color
- Video element: Trim

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10639

### CODE REVIEW

**Review by BrookeGraham — COMMENTED** [review]
Should we also remove `Replace Media` on the video?

**Comment by BrittanyIRL** [comment]
> Should we also remove `Replace Media` on the video?

Oh good catch. That wasn't listed in the ticket so I ignored it. 

@barklund is this an exception or should replace media also be removed from quick action?

**Review by BrookeGraham — APPROVED** [review]
🧹

**Review by maxyinger — APPROVED** [review]

**Review by samwhale — APPROVED** [review]

**Comment by BrittanyIRL** [comment]
> > Should we also remove `Replace Media` on the video?
> 
> Oh good catch. That wasn't listed in the ticket so I ignored it.
> 
> @barklund is this an exception or should replace media also be removed from quick action?

Discussed with Amy and Miina briefly and I'm not going to add that here because it creates a weird inconsistency between background media quick action menu and foreground media floating menu that should be discussed a bit more before anything gets updated.

**Pull request merged**
