### PR TITLE
Use spaces instead of tabs for indentation

### PR DESCRIPTION
**Pull request by wassgha**
Since tabs don't play well with the Github code review interface

### CODE REVIEW

**Comment by swissspidy** [comment]
Interesting. I don‘t think we‘ve had any such issues with reviews & tabs in the past. Curious to hear everyone‘s opinion.

Personally I don‘t have a strong opinion, as the linter takes care of everything anyway. Although I‘d probably like to keep tabs at least for PHP files.

**Comment by wassgha** [comment]
> Interesting. I don‘t think we‘ve had any such issues with reviews & tabs in the past. Curious to hear everyone‘s opinion.
> 
> Personally I don‘t have a string opinion, as the linter takes care of everything anyway. Although I‘d probably like to keep tabs at least for PHP files.

This PR only affects javascript btw, I don't have a strong opinion either but the code review looks a bit annoying with tabs (especially in JSX) so I'm following what `amphtml` is using in terms of spacing.

**Comment by barklund** [comment]
Hm, I don't feel strongly one way or the other about it, but I don't see any issues with using tabs at all.

> Since tabs don't play well with the Github code review interface

In what way do you feel this is a problem? Lines do become quite long with 4-5 tab-based indents of course, but it's rarely an issue IMO.

**Comment by wassgha** [comment]
> In what way do you feel this is a problem? Lines do become quite long with 4-5 tab-based indents of course, but it's rarely an issue IMO.

It gets a little messy on smaller resolution displays, here's an example from Dima's PR
Screen Shot 2020-01-28 at 6 07 57 PM

**Comment by swissspidy** [comment]
Apparently one can append ?ts=2 or ?ts=4 to the URL to change the tab-size.

Also, GitHub seems to adhere to indent_size in the editorconfig. Perhaps just tweaking that is enough?

**Comment by wassgha** [comment]
Wouldn't that cause new files to have a different indent size than existing
files?

**Comment by cramforce** [comment]
Let's follow our other repositories and put in prettier instead of arguing about styling.

**Comment by barklund** [comment]
> Let's follow our other repositories and put in prettier instead of arguing about styling.

Yeah, that's a lot less controversial for sure 😜.

(again, I don't really care, I just want to know the reasons why)

**Comment by swissspidy** [comment]
Opened #156 to explore leveraging Prettier. Config might need some tweaking here and there, but otherwise works fine.

**Comment by wassgha** [comment]
+1 for prettier, closing this

**Pull request closed without merging**
