### PR TITLE
E2E Tests: Add Percy coverage for dropdown on dashboard

### LINKED ISSUE #10789: E2E Tests: Percy coverage for dropdowns/tooltips on settings page
## Task Description

Taking this out of #10392

Let's take 1 Percy snapshot after scrolling on the Settings page and opening a dropdown (e.g. the Monetization dropdown).

This is in response to a regression that occurred that was solved in #10539. Helps catch incorrect positioning of dropdown menu in the future.

### PR DESCRIPTION
**Pull request by timarney**
## Context

Adds a test and snapshot for the dropdown on the dashboard.

160495707-e9c960b2-fc4a-40af-b15a-dafd1974c042

Originally this was a follow up for https://github.com/GoogleForCreators/web-stories-wp/issues/10392 but given the location at the bottom of the page for the `Monetization dropdown` ... Percy was failing to capture an accurate snapshot see https://github.com/GoogleForCreators/web-stories-wp/pull/11076#issuecomment-1078868861

## Summary

Adds snapshot of `sort option dropdown`

## Relevant Technical Choices

Noting: This also bump Percy CLI to the latest version

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Automated test --- ensure the Percy snapshot is captured properly

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10789

### CODE REVIEW

**Comment by swissspidy** [comment]
Hmm on the Percy snapshot I don't actually see the dropdown:

image

We might need to wait for the dropdown to appear first before taking the snapshot.

Something like

```js
await expect(page).toMatchElement('li', { text: 'Google AdSense' });
```

**Comment by timarney** [comment]
Looks like it jumps up to the Video Optimization section
160097052-c1953437-c9fe-428e-b301-217acf7da565


Screen Shot 2022-03-25 at 6 11 29 AM


I'll take a deeper look.

**Comment by swissspidy** [comment]
> Looks like it jumps up to the Video Optimization section

Oh wow I totally missed that 😅 

Maybe in issue with Chromium? Or just how Percy creates the snapshots?

If it's the former, then this would make writing reliable tests harder.
If it's the latter, then taking this snapshot is a bit useless because it's never accurate.

**Comment by timarney** [comment]
I'll see using my local Percy token...

-- I did notice I'm missing the `await` on the snapshot.

**Comment by timarney** [comment]
Will see what the latest push looks like --- but another local run I can see the dropdown in the custom font area.  Doesn't look like this is going to be accurate.

custom-fonts

**Comment by timarney** [comment]
Local run --- Firefox 

e9fd0559e5f2b70b7fd572dc884ab45fe8fd36f871d718aaf96ea3a6479c553c

**Comment by timarney** [comment]
@swissspidy --- same results.  

Trying one more commit with a bump to Percy version

https://percy.io/google/web-stories-wp-e2e/builds/16820482/changed/945569067?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600

Looks like this isn't going to be worth adding.

**Comment by spacedmonkey** [comment]
Is the issue around screen size and scrolling. Before the screenshot, could be scroll the drop before taking the screenshot?

**Comment by swissspidy** [comment]
> Looks like this isn't going to be worth adding.

I fear so too 😞 

I'll take another look on Monday when we can decide whether to close this as a wontfix or not.

**Comment by timarney** [comment]
@spacedmonkey 

> Is the issue around screen size and scrolling. Before the screenshot, could be scroll the drop before taking the screenshot?

Not sure what your asking

There is code higher up that should handle scrolling to the element before the click 

```
// Small trick to ensure we scroll to this input.
    const monetizationDropdown = await page.$(monetizationDropdownSelector);
    await monetizationDropdown.focus();
```

**Comment by spacedmonkey** [comment]
Screenshot 2022-03-25 at 14 53 23

@timarney This red box is the size of the viewable screen in the tests. However, the screenshot, shows all the rendered markup. You can see this is the size of the screen, by the sidebar not reaching the end of the screenshot. 

We setup screen size here. 

https://github.com/GoogleForCreators/web-stories-wp/blob/90ca2edffaf12f1c9c4082b310d57eaf17d2addd/packages/e2e-tests/src/config/bootstrap.js#L129-L135

Puppeteer is clicking on a dropdown, that is off screen, which is why we are seeing this error. 

Either we click on a dropdown that is on screen by scrolling to ensure it is visual or we change the size of the screen.

**Comment by timarney** [comment]
Tried scrolling to the bottom --- works fine for a puppeteer snapshot but can't seem to get a Percy snapshot to do the same.

According to this it should be possible https://docs.percy.io/docs/capturing-lazy-loading-images

> If images are not rendering correctly in your snapshots, it's likely the page did not **scroll past the image (and did not trigger the intersection observer).**

Wondering if we can't scroll past that element enough.

**Puppeteer snapshot** --- just to verify I was indeed scrolling to the bottom of the page
Monetization Dropdown

**Comment by timarney** [comment]
Added a new Dashboard test with snapshot

Screen Shot 2022-03-28 at 8 29 36 AM

**Comment by swissspidy** [comment]
I suppose that works too!

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
