### PR TITLE
Updated template detail UI to new designs

### LINKED ISSUE #1279: Dashboard - Template Detail View - Update to new Design
## Feature Description

Update the existing template detail UI from this:
image

To this:
image

**Note**: Ignore the Next/Previous template controls and "Related Templates".

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by mariano-formidable**
Fixes #1279.

This PR updates our existing Template Detail UI to look closer to the new designs (we don't have figma mocks for the new design, so just eyeing it off the video):

This is our site:
image

This is a screenshot from the mock video:
image

Also, I wrote a new component called the `ColorList` and created a storybook page for it:
image

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
LGTM

**Review by carloskelly13 — APPROVED** [review]
This looks good. My only question is should we do a very light inset box shadow with a partial opacity to outline lighter colors? The yellow gets lost here for me and the contrast is borderline.

Screen Shot 2020-04-22 at 3 25 08 PM

**Review by BrittanyIRL — APPROVED** [review]
LGTM! Only nit is that I feel like the space between the page of the story in view and the text/colors is wider in the dashboard than the screenshot but i think the best path forward with those kinds of nits are to wait for the true mock ups so we can get it right.

**Comment by mariano-formidable** [comment]
> This looks good. My only question is should we do a very light inset box shadow with a partial opacity to outline lighter colors? The yellow gets lost here for me and the contrast is borderline.
> 
> Screen Shot 2020-04-22 at 3 25 08 PM

Yeah, I definitely think there are valid colors that might get lost in this design but even the mock designs show that yellow without a border.  I think once the first iteration of the UI is complete and Sam starts playing with the actual site data, there will be design tweaks that we can apply then. 
image

**Comment by mariano-formidable** [comment]
> LGTM! Only nit is that I feel like the space between the page of the story in view and the text/colors is wider in the dashboard than the screenshot but i think the best path forward with those kinds of nits are to wait for the true mock ups so we can get it right.

You know what, the original design did have a pretty big gap between them but the screenshot has things more evenly spaced soooo.. I'll see if I can do a quick fix-a-roo just because I think it might be a small tweak to get it working!

**Pull request merged**
