### PR TITLE
Media: Remove media frame on close

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

While working on https://github.com/GoogleForCreators/web-stories-wp/pull/11941. I discovered that wp media instance when the wp media instance is closed. This instance may use memory in the browser and requires resetting. Just use remove method. 

See

https://github.com/WordPress/gutenberg/blob/67a652439c3d2f7dd8623d24b0bd12b5aff053f5/packages/media-utils/src/components/media-upload/index.js#L342-L344

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
Any recommendations on how to verify this change? Should there be any changes in the DOM?

**Comment by spacedmonkey** [comment]
> Any recommendations on how to verify this change (testing instructions)? Should there be any changes in the DOM?

No dom change here. It is more about reseting state. One way to test this is to open a wp dialog, search for something and close it. Open again. 

Discovery this need while looking at [this](https://github.com/WordPress/gutenberg/blob/e6dd3b19d186c61fa8894dc8fdfb4fa716e3b010/packages/media-utils/src/components/media-upload/index.js#L342-L344).

**Comment by swissspidy** [comment]
> One way to test this is to open a wp dialog, search for something and close it. Open again.

I don't see a difference when doing that. What should be different?

**Comment by spacedmonkey** [comment]
> I don't see a difference when doing that. What should be different?

In my PR this, is no longer required. 

https://github.com/GoogleForCreators/web-stories-wp/blob/f2cf9b8505c535165b7d96e8a555f60762b40bc1/packages/wp-story-editor/src/components/mediaUpload/mediaPicker/useMediaPicker.js#L279-L284

As removing the the wp.media, means state is reset and no chance of state set in the first instance of using the dialog is not used.

**Comment by swissspidy** [comment]
I suppose that explains why there is no difference: there should be none.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
