### PR TITLE
Video Trimming: Avoid crash due to missing `tracks` property

### LINKED ISSUE #12471: Video Trimming: Crash due to missing `tracks` property
I am seeing a crash on a particular story with many amp elements in side the page. Unfortunately, I am not able to isolate the problem to a particular element or image file. I am filing this bug in case its useful to review the crash report and isolate the problem that way:

Steps:
1. Open this specific story: https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/post.php?post=20259&action=edit
2. Go to the 5th page .. which is a mp4 file full bleed with some more elements on top of it
3. Select the background, go to Styles panel and click on Trim

Crash reported in browser:

Contents of the crash report:

```
TypeError: Cannot read properties of undefined (reading 'map')

    at VideoTrim (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:38:394674)
    at VideoEdit (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:38:396159)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at EditElement (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:176:60491)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at PageArea (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:176:68734)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at WithOverlay (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:32063)
    at section
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at Layer (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:176:65127)
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at WithOverlay (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:32063)
    at EditLayerForElement (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:176:80909)
    at EditLayer (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:176:82190)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at CanvasElementDropzone (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:214:14029)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at UploadDropTarget (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:122:8350)
    at CanvasUploadDropTarget (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:214:13520)
    at section
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at EditLayerFocusManager (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:176:8588)
    at le (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:275510)
    at CanvasLayout (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:214:25796)
    at vee (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:214:27834)
    at ErrorBoundary (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:34385)
    at div
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at RichTextProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:38:344010)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at VideoTrimProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:214:31226)
    at Workspace (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:214:32714)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at MediaRecordingProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:152:2687)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at RightClickMenuProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:216:10282)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at UnitsProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:78771)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at CanvasProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:54:1592)
    at section
    at O (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:280377)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at WithOverlay (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:32063)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at SidebarProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:298:16280)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at HighlightsProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:124:9188)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at ChecklistCheckpointProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:118:1237)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at LayoutProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:81681)
    at Zue (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:298:18362)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at MetaBoxesProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:300:9262)
    at Cme
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at PageDataUrlProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:54:23628)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at PageCanvasProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:54:26004)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at HelpCenterProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:54:9657)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at DropTargetsProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:76408)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at TransformProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:19234)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at MediaProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:67170)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at FontProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:37265)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at CurrentUserProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:14587)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at TaxonomyProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:72245)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at StoryTriggersProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:10495)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at StoryProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:11560)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at SnackbarProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/9419.js?ver=8405f296c8a204eec0e2:17:48551)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at HistoryProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:38:2959741)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at Media3pApiProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:46:34843)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at APIProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:35166)
    at https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:287692
    at ConfigProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:34864)
    at ErrorBoundary (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:14:34385)
    at Fe (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:278466)
    at le (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/5369.js?ver=8405f296c8a204eec0e2:1:275510)
    at FlagsProvider (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/81.js?ver=8405f296c8a204eec0e2:1:239347)
    at StoryEditor (https://stories-qa-wordpress-amp.pantheonsite.io/wp-content/plugins/web-stories/assets/js/wp-story-editor.js?ver=8405f296c8a204eec0e2:54:36802)
```

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Set the default value of tracks in trim component to an empty array. This brings this compontent inline with others like [this](https://github.com/GoogleForCreators/web-stories-wp/blob/a6b1f03e13c7e43936a79fc35d859f912558b36c/packages/element-library/src/video/display.js#L43),  [this](https://github.com/GoogleForCreators/web-stories-wp/blob/025457645ca33da7fe6b2524bbcb340af93e82a6/packages/story-editor/src/components/panels/shared/media/audioPlayer.js#L79) and [this](https://github.com/GoogleForCreators/web-stories-wp/blob/21efe88f34a7c8bb4464389c0cc5186b785e2b0a/packages/story-editor/src/components/panels/shared/media/captionsPanelContent.js#L65).

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a story. 
2. Add video to canvas. 
3. Click trim video. 
4. See no error. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12471

### CODE REVIEW

**Comment by swissspidy** [comment]
As per the ticket, we should add a data migration.

**Comment by spacedmonkey** [comment]
> As per the ticket, we should add a data migration.
> 
> And of course ideally fix the root cause

This fix, fixes the problem. What is the point of adding a migration?

**Comment by swissspidy** [comment]
Looks like `tracks` is marked as optional on the `VideoElement` type, so I suppose this is expected.

In that case please fix the lint errors and then I think we can merge it.

**Review by swissspidy — APPROVED** [review]

**Review by timarney — APPROVED** [review]

**Comment by kkalarickal** [comment]
@swissspidy - I was not able to find the branch within the web-stories-tester that would allow me to test this fix in isolation on stories-qa test site. To confirm this was fixed, I also recreated the crash in another branch that did not have the merged code.

However, I noticed that the #12471 issue was closed. So i tested this crash by trimming the video on 5th page  of the specific story that I had mentioned in that ticket. And the crash did not occur.

Reporting this here since this ticket is sitting in Ready-for-QA although the fix seems to have been merged in main.

**Pull request merged**
