### PR TITLE
Dashboard: Applied design updates to Entertainment template

### LINKED ISSUE #2474: Templates: Update Entertainment templates to 9:16
Use this Figma doc to apply 9:16 updates to the existing `Entertainment` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR applies the new design update to the Entertainment template.

## User-facing changes

Layout and text sizes have been updated on the Entertainment template based off the recommendations found in this [figma design doc](https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61).

## Testing Instructions

1.) Go to "Explore Templates"
2.) Hover over the Entertainment template and click on "View".
3.) Take a look at each template page in the detail view for Entertainment. Make sure images are showing up and the layout appears as shown in the figma updates.

**NOTE:** `ent_page5_image1.jpg` has been updated but wordpress might cache the original image, so if on Page 5 if you don't see the new image depicted in the figma docs, clear the cache for this site and refresh and that should force the new image to load up.

---

Fixes #2474 

## Animations still work 🎉 

(If you set `enableAnimation` to `true` in `Dashboard.php`, you'll see that the animations still work under the new updates)

ent_anim_still_work

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
lgtm!

**Review by dmmulroy — APPROVED** [review]
Looks good 👍

**Review by BrittanyIRL — APPROVED** [review]
Template looks great! Two small grammar things 🙃 

nit: on page 7 this text blurb should be `one of our favorite songs` not `song`
> We’ll take your through the production process of one of our favorite song. 

Similarly, page 10 the plural of `Grammy` is actually `Grammys` (not Grammy's) which I think is why a lot of the time people will just write `Grammy Awards`.

**Comment by mariano-formidable** [comment]
> Template looks great! Two small grammar things 🙃
> 
> nit: on page 7 this text blurb should be `one of our favorite songs` not `song`
> 
> > We’ll take your through the production process of one of our favorite song.
> 
> Similarly, page 10 the plural of `Grammy` is actually `Grammys` (not Grammy's) which I think is why a lot of the time people will just write `Grammy Awards`.

Yay the typos existed in the original figma designs, I was blindly copying over like a robot :D I'll fix'em!!

**Pull request merged**
