### PR TITLE
Pre-Publish Checklist: Remove video optimization feature flag

### LINKED ISSUE #7322: Set PPC video optimization feature flag to true
This will be the last ticket to go through for the new video optimization experiment. Just set the experiment to `true` and use this as the QA step for the video optimization bulk.

## Acceptance criteria 
- Experiment set to true 
- Detailed QA steps for Claudio

### PR DESCRIPTION
**Pull request by embarks**
## Context
See https://github.com/google/web-stories-wp/pull/8176

### QA

- [x] This is a non-user-facing change and requires no QA

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?
no

### Does this PR change what data or activity we track or use?
no

### Does this PR have a legal-related impact?
no

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7322

### CODE REVIEW

**Comment by spacedmonkey** [comment]
This PR seems to have a merge conflict, please merge main and retest. 

Also noticed a couple of weird things about this PR. 

1. Optimizing video is a not a blocking PPC item. That is confusing, to allow an optimized version to be publish then fix after that. Fact if you publish and it ends up in lots of CDN caches? Feels like this should be blocking. 

2. See this video. The behaviour seems strange. The size of the video changes to fill the page and then is not updated after processing is finish. The quality reduces by a lot and it looks weird. Is this just me?

https://user-images.githubusercontent.com/237508/124463919-73ec7100-dd8b-11eb-8c30-d332dda48db0.mov

CC @swissspidy

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
This PR seems to have a merge conflict, please merge main and retest. 

Also noticed a couple of weird things about this PR. 

1. Optimizing video is a not a blocking PPC item. That is confusing, to allow an optimized version to be publish then fix after that. Fact if you publish and it ends up in lots of CDN caches? Feels like this should be blocking. 

2. See this video. The behaviour seems strange. The size of the video changes to fill the page and then is not updated after processing is finish. The quality reduces by a lot and it looks weird. Is this just me?

https://user-images.githubusercontent.com/237508/124463919-73ec7100-dd8b-11eb-8c30-d332dda48db0.mov

CC @swissspidy

**Comment by swissspidy** [comment]
> Optimizing video is a not a blocking PPC item. That is confusing, to allow an optimized version to be publish then fix after that. Fact if you publish and it ends up in lots of CDN caches? Feels like this should be blocking.

Video optimization has never been considered blocking so this is not changing anything. This sounds like a feature request that should be brought up with product.

> See this video. The behaviour seems strange. The size of the video changes to fill the page and then is not updated after processing is finish. The quality reduces by a lot and it looks weird. Is this just me?

Looks like a bug that should be fixed in a dedicated ticket. Could you create one?

**Comment by embarks** [comment]
@swissspidy @spacedmonkey with regards to the video dimensions changing. not related to the feature flag, but I think some issue in `useProcessVideo`:

```
      const onUploadProgress = ({ resource }) => {
        const oldResourceWithId = { ...resource, id: oldResource.id };
        // updateElementDimensions({
        //   id: oldResource.id,
        //   resource: oldResourceWithId,
        // });
        updateExistingElements({
          oldResource: oldResourceWithId,
        });
      };
```
when I comment out `updateElementDimensions` call, the resizing problem doesn't occur:


https://user-images.githubusercontent.com/41136059/124507292-5bc42400-dd82-11eb-94c7-a212b502a07c.mp4

**Comment by spacedmonkey** [comment]
Follow up ticket https://github.com/google/web-stories-wp/issues/8192

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
@googlebot I consent

**Pull request merged**
