### PR TITLE
Bump version to 1.2 and update readme.txt

### PR DESCRIPTION
**Pull request by dreamofabear**
#5633

### CODE REVIEW

**Comment by swissspidy** [comment]
Let‘s also add an upgrade notice in the readme

**Comment by dreamofabear** [comment]
> Let‘s also add an upgrade notice in the readme

What should we put there? Are there any backwards incompatibilities or gotchas?

**Review by barklund — APPROVED** [review]

**Review by carloskelly13 — APPROVED** [review]

**Comment by swissspidy** [comment]
> > Let‘s also add an upgrade notice in the readme
> 
> What should we put there? Are there any backwards incompatibilities or gotchas?

@choumx The upgrade notice is a short message displayed below the update notification in the WordPress admin and can be used to tell users what to expect from this release in 1-2 sentences.

----

NB: We've been following semver for the version numbers so far, so this would have needed to be tagged as 1.2.0, not 1.2.

**Comment by dreamofabear** [comment]
> The upgrade notice is a short message displayed below the update notification in the WordPress admin and can be used to tell users what to expect from this release in 1-2 sentences.

Yea, my quick Googling at the time showed it was meant for warnings but we can use it for a feature overview next time. 

> We've been following semver for the version numbers so far, so this would have needed to be tagged as 1.2.0, not 1.2.

Oops. SGTM, but does it buy us anything for product versioning? E.g. I think we plan to release borders feature in 1.2.1.

**Comment by swissspidy** [comment]
> Oops. SGTM, but does it buy us anything for product versioning? E.g. I think we plan to release borders feature in 1.2.1.

Technically a new feature like this would be a minor release, but borders are already in 1.2, or am I missing something? Seeing this on my site:

Screenshot 2020-12-14 at 23 17 51

**Pull request merged**
