### PR TITLE
Redesign: Video accessibility panel

### LINKED ISSUE #6466: Redesign: Update video accessibility panel
## Feature Description
See[ Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A157583)

- [ ] Use media picker from design system
- [ ] Update title input
- [ ] Use the regular input for now, until multiline is ready

## Additional Context
Screenshot 2021-02-22 at 12 24 30

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
- Removes Poster panel as a separate panel.
- Uses the redesigned TextArea for the poster alt.

## User-facing changes
| Before | After |
|-----|---------|
| Screenshot 2021-03-10 at 15 19 42 | Screenshot 2021-03-09 at 17 51 16 |

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add a video
2. Open the Video Accessibility panel and verify it looks as [in Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=742%3A22145) -- note that the Poster Title field is removed purposefully, the design needs an update.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6466

### CODE REVIEW

**Comment by barklund** [comment]
@miina, the diff is quite large for this one. Can you try to rebase or merge back with the original branch?

**Review by barklund — COMMENTED** [review]
Looks good, just would like to see the true diff before approving - maybe you snug a unicorn easter egg in there 🦄 🥚 !

**Comment by miina** [comment]
> @miina, the diff is quite large for this one. Can you try to rebase or merge back with the original branch?

😮 Oops!!! Not sure what happened here. 👀

**Review by barklund — APPROVED** [review]
🦒

**Pull request merged**
