### PR TITLE
Dashboard: Remove elements dependency

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

We do not render stories or templates in the dashboard anymore. We just display preview images. So there's no need for us to actually register elements.

## Summary

Removes dependencies on `elements` and `element-library` from the dashboard package.

This should improve bundles a bit.

## User-facing changes

N/A

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by miina** [comment]
Screenshot 2022-09-07 at 13 27 54

I wonder why the increase 🤔

**Comment by spacedmonkey** [comment]
> I wonder why the increase 🤔

Just looking at this myself. I think it because `assets/js/1303.js` was removed and now is part of the story editor package.

**Comment by spacedmonkey** [comment]
assets/js/wp-story-editor.js being 1.34MB seems like very big. I wonder if we should look into breaking this up. I am little bit worried about the editor loading.

**Review by spacedmonkey — APPROVED** [review]
Seems good to me. But I would like to follow up and look into the bundle size of the editor, which at 1.34mb seems a little large.

**Comment by swissspidy** [comment]
Dashboard and editor have a common bundle for shared code.

The main reason is the stickers package, which is a dependency of `element-library`.

With this PR, stickers are no longer included for the dashboard and thus no longer in the common bundle but only in the editor bundle.

So that all makes sense.

There is already a ticket to optimize the way stickers are included, see #11973 

See also #11972 for the masks package

**Pull request merged**
