### PR TITLE
Tests: Improve multisite compatibility and how capabilities are set

### LINKED ISSUE #4353: Test breaks in multisite
## Bug Description

When working on #4301 , I found that if I created a new site and switched to it in a test, many of the test would break for no reason. This breakable was unrelated to the change in hand. An example of these breakables could be found [here](https://github.com/google/web-stories-wp/runs/1072450694#step:12:43). 

## Expected Behaviour

New site can be created in unit tests and it just works.

## Steps to Reproduce

```
        /**
	 * @group ms-required
	 */
	public function test_init_sets_missing_options_multisite() {
		$blog_id = (int) self::factory()->blog->create();
		switch_to_blog( $blog_id );
		$this->assertSame( WEBSTORIES_DB_VERSION, get_option( \Google\Web_Stories\Database_Upgrader::OPTION ) );
		$this->assertSame( '0.0.0', get_option( \Google\Web_Stories\Database_Upgrader::PREVIOUS_OPTION ) );
		restore_current_blog();
	}
```

## Additional Context

- Plugin Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

This PR highlights there are some serious issues with WordPress unit testing. 

Things I found. 
- In multisite, the capabilities are not setup correctly. So over 20 tests fail without the correct capability. 
- There 3 tests that are validly failing in multisite :( 
- Capabilities should be removed when a site is delete on a multisite.

## Relevant Technical Choices

Added a helper to make sure that capability is there for all test users.
For now, skip broken tests and add todos
Added a callback to remove capability when site is deleted.
For some reason, some tests fail if permalinks are not set. 

## Testing Instructions

---

Fixes #4353

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@swissspidy I think I cracked this. Deleting roles when site is deleted fixes most of the issues. There are now a couple of other issues, but I think they are related to the test suite. I feel like these bugs we always there and their just didn't show before.

**Comment by spacedmonkey** [comment]
I think this is an issue with activation / setup of roles is not happening, after new site is created. I think this is an issue with the WP test suite. It how WP_Roles is setup a global and sites are reset in test suite. 

I can't esaily debug this, as the results locally, are different than in GHA. 

I get this locally 
```
There were 6 failures:

1) Google\Web_Stories\Tests\Dashboard::test_add_menu_page_user_without_permission
Failed asserting that 'admin_page_stories-dashboard' is false.

/Users/jonny/workspace/web-stories-wp/tests/phpunit/tests/Dashboard.php:57

2) Google\Web_Stories\Tests\Discovery::test_get_schemaorg_metadata
Failed asserting that an array has the key 'mainEntityOfPage'.

/Users/jonny/workspace/web-stories-wp/tests/phpunit/tests/Discovery.php:130

3) Google\Web_Stories\Tests\Discovery::test_print_open_graph_metadata
Failed asserting that '		<meta property="og:locale" content="en-US" />
		<meta property="og:type" content="article" />
		<meta property="og:title" content="" />
		<meta property="og:url" content="">
		<meta property="og:site_name" content="Test Blog">
		<meta property="og:description" content="" />
		' contains "article:published_time".

/Users/jonny/workspace/web-stories-wp/tests/phpunit/tests/Discovery.php:147

4) Google\Web_Stories\Tests\Discovery::test_print_twitter_metadata
Failed asserting that '		<meta name="twitter:card" content="summary_large_image" />
		' contains "twitter:image".

/Users/jonny/workspace/web-stories-wp/tests/phpunit/tests/Discovery.php:169

5) Google\Web_Stories\Tests\Story_Post_Type::test_filter_template_include
Failed asserting that 'current' contains "/Users/jonny/workspace/web-stories-wp/".

/Users/jonny/workspace/web-stories-wp/tests/phpunit/tests/Story_Post_Type.php:277

6) Google\Web_Stories\Tests\Story_Post_Type::test_show_admin_bar
Failed asserting that 'current' is false.

/Users/jonny/workspace/web-stories-wp/tests/phpunit/tests/Story_Post_Type.php:287

FAILURES!
Tests: 247, Assertions: 668, Failures: 6.
```

**Comment by spacedmonkey** [comment]
@swissspidy Can you check this out locally and see what you see when you ` npm run  test:php:multisite`

**Comment by spacedmonkey** [comment]
@swissspidy I like this solution. I thought about doing this, but thought it might be overkill. I am happy to merge this as is.

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
I'm still not super fond of it, but for now it seems to work.

**Pull request merged**
