### PR TITLE
Karma: Replace custom snapshot solution with Percy

### LINKED ISSUE #10332: Karma: Move percy uploads to separate job
## Task Description

Now that our Karma tests are running in a parallel job, it means that we're uploading Percy snapshots 4 times instead of once
Screenshot 2022-01-22 at 17 15 20

To fix this, we need to move the `Upload Percy snapshots` step to its own job that runs after the matrix job, passing around the snapshot files using `actions/upload-artifact`

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

Alternative to #10368

Figured that this might be a good opportunity to replace our custom snapshot handling with `@percy/puppeteer` and `@percy/cli` for easier maintenance.

## Summary

Fixes snapshot taking for Karma tests running in parallel

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10332

### CODE REVIEW

**Comment by swissspidy** [comment]
Percy URL for review: https://percy.io/google/web-stories-wp/builds/15273899/

At first glance I don't see any oddities with the screenshots.

**Review by BrittanyIRL — APPROVED** [review]
generated snapshots look good to me. I'm not the best person to approve the config code but it seems like it's working. 

Dashboard snapshots didn't run? Was that intentional?

**Comment by swissspidy** [comment]
> Dashboard snapshots didn't run? Was that intentional?

@BrittanyIRL We've never had snapshots for the dashboard, actually. Dunno why, but it would be a good enhancement

**Comment by BrittanyIRL** [comment]
> > Dashboard snapshots didn't run? Was that intentional?
> 
> @BrittanyIRL We've never had snapshots for the dashboard, actually. Dunno why, but it would be a good enhancement

i swear i saw them before 🙈 ! but yes, let's add them.

**Comment by swissspidy** [comment]
Ticket created: #10392

**Pull request merged**
