### PR TITLE
Limit popup inside viewport vertically

### PR DESCRIPTION
**Pull request by barklund**
Not sure if I like this though. @miina, @dvoytenko, WDYT?

Here's a demo video:

viewport

### CODE REVIEW

**Comment by miina** [comment]
@barklund I'm not sure either :) Perhaps it should display above the anchor field _IF_ there is room and _IF_ the room ended up below the anchor field? Could also check with Sam.

(Feel free to take over the original issue btw, would be great! I won't have availability before tomorrow morning)

**Comment by miina** [comment]
FI: Just checked that Gutenberg does something similar: switches between displaying above/below the anchor field depending on the room:
popup-g

**Comment by barklund** [comment]
Here's the same video without restricting the popup to the viewport. Note that at default position and this narrow window size (only 600px height visible in browser), the calendar starts partially outside the viewport. And you can't scroll while the cursor is over the calendar itself, as it lives in another layer on top of the actual scrollable layer. You have to move the cursor to the narrow non-calendar strip next to it (or above it) to scroll the full calendar into view.

nonviewport

**Comment by dvoytenko** [comment]
Alternative options here would be:

1. Have a blocking fullscreen screen that essentially kills scrolling for anything else.
2. No blocking screen, but close the popup if anything outside the popup is scrolled.
3. Ignore scrolling entirely.
4. Do what you're doing in this pull request.

IMHO we should chose the easiest now that's reasonably ok. To note on the animation you posted though: I believe the initial popup position once you open it the first time should be above the anchor element and never on top of it. Especially since we'll soon enough want to do auto-complete style dropdowns for font search.

**Comment by barklund** [comment]
> I believe the initial popup position once you open it the first time should be above the anchor element and never on top of it. Especially since we'll soon enough want to do auto-complete style dropdowns for font search.

That's not possible. My current viewport height is ~600 visible px (not unlikely for a small laptop) and with a popup of 370px height, if the anchor element is more or less centered, there's no space neither above or below, that would show the full element.

**Comment by dvoytenko** [comment]
> > I believe the initial popup position once you open it the first time should be above the anchor element and never on top of it. Especially since we'll soon enough want to do auto-complete style dropdowns for font search.
> 
> That's not possible. My current viewport height is ~600 visible px (not unlikely for a small laptop) and with a popup of 370px height, if the anchor element is more or less centered, there's no space neither above or below, that would show the full element.

May we should then look for where we have more space and force max height to whatever is available, even if it's less than 370px?

**Comment by dvoytenko** [comment]
Input with the `<datalist>` actually has a good model I think: https://output.jsbin.com/nexiqof/quiet

1. See top and bottom input: one starts up with the popup below and the other with the popup above.
2. If you scroll or resize the content, the popup just auto-closes.
3. For the second input: the popup starts above. But when you input something and the contents of the popup need less space, the popup repositions below. This part, IMHO, is very optional.

**Comment by swissspidy** [comment]
This needs to be rebased now that #986 has been merged.

**Comment by spacedmonkey** [comment]
> Input with the `<datalist>` actually has a good model I think: https://output.jsbin.com/nexiqof/quiet
> 
> 1. See top and bottom input: one starts up with the popup below and the other with the popup above.
> 2. If you scroll or resize the content, the popup just auto-closes.
> 3. For the second input: the popup starts above. But when you input something and the contents of the popup need less space, the popup repositions below. This part, IMHO, is very optional.

I think these same thought can be applied to the dropdown and #756 CC @ndev1991

**Comment by barklund** [comment]
@miina is this even still relevant?

**Comment by miina** [comment]
@barklund Looks like this will be superseded by #1060, will close for now.

**Pull request closed without merging**
