### PR TITLE
Add aria-label to buttons without labels

### PR DESCRIPTION
**Pull request by swissspidy**
See #742

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@swissspidy I think we should merge this. We can add more later.

**Comment by spacedmonkey** [comment]
Should we change [this](https://github.com/google/web-stories-wp/blob/fed0c8f0a2f953b792238a647a39de8081f1072b/assets/src/edit-story/elements/video/frame.js#L153) to aria-label? CC @swissspidy

**Comment by swissspidy** [comment]
Looks like it, yes

**Comment by swissspidy** [comment]
Closing as it's very much outdated.

**Pull request closed without merging**
