### PR TITLE
Links: Increase icon crop size from 32px to 96px

### LINKED ISSUE #9396: Increase link icon dimensions
## Feature Description

Right now we crop link icons and page attachment icons to 32x32px:

https://github.com/google/web-stories-wp/blob/7c1bec55dd799096afdefd79f0f47ab5052d72aa/packages/story-editor/src/components/form/linkIcon.js#L65-L68

But in the editor we display them at 54x54px, causing them to appear pixelated in the design panel:

Screen Shot 2021-10-12 at 4 23 50 PM

We could safely crop them to something larger like 96x96 to make them more crisp and future proof in case the icons ever need to be displayed in larger size.

### PR DESCRIPTION
**Pull request by hamza-arshad**
## Context

Increase cropped form link icon size

## Summary

When user selects an icon for the link, we used to cropped it to the size 32x32 which is blurry when we were displaying it as 54x54 icon on form. Now increased the size to 96x96 so that if in future, we want to display it even a little bigger than 54x54, won't be a problem.

## Relevant Technical Choices

N/A

## To-do

N/A

## User-facing changes

It doesn't affect any user facing functionality, but the image of icon will be displayed sharp rather than pixelated.

Before:
Screenshot 2021-10-13 at 10 06 21 PM

After:
Screenshot 2021-10-13 at 10 06 09 PM

Difference in Image: (right one is after the changes)
Screenshot 2021-10-13 at 10 06 26 PM

## Testing Instructions

This PR can be tested by following these steps:

1. Go to the story editor.
2. Add link to a layer and select the icon.
3. The form link Icon should appear sharp now instead of Pixelated.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9396

### CODE REVIEW

**Review by miina — APPROVED** [review]

**Comment by miina** [comment]
@hamza-arshad Could you please merge `main` into the PR? Looks like some Karma tests are failing, seemingly unrelated.

**Comment by hamza-arshad** [comment]
@miina done. and I think it passed all checks now.

**Comment by hamza-arshad** [comment]
@miina can you add label `hacktoberfest-accepted` to my PR? Only if it's feasible. Thanks.

**Comment by swissspidy** [comment]
I'm afraid we don't really participate in Hacktoberfest.

I'm also still not sure whether this approach with increasing the image size is really the best, as it dos lead to larger file sizes.

**Comment by hamza-arshad** [comment]
Hey - no worries about hacktoberfest.

**Comment by hamza-arshad** [comment]
About the best approach, I can be available for discussion, and we can decide how this can be improved.

**Review by swissspidy — APPROVED** [review]
Went back and forth on this one, but ultimately came to the conclusion that just increasing the crop params like this (and accepting larger file sizes) is acceptable and adding a second cropping to 32x32 for the frontend is not worth the added complexity.

**Pull request merged**
