### PR TITLE
Block: Fix stories selector styling issues

### LINKED ISSUE #12620: Block: Stories selector styling issues
## Bug Description

Reporting based on the pointer from @spacedmonkey regarding "[_Some of the styling in the block’s story editor is kind of wonky_](https://xwp.slack.com/archives/C013J2EGH8R/p1667478189974889)"

Basically, if user wants to add stories to the carousel, the selector overlay that appears is difficult to search for and navigate due to styling issues.

## Expected Behaviour

It should be easy for a user to search for, select and rearrange stories within the carousel stories selector overlay.

## Steps to Reproduce

1. As an editor or above, create a WP post and embed web story carousel block into it
2. Now pick a list type carousel and select stories to add to the list
3. An overlay opens that allows user to select stories
4. Find the issues listed above in that overlay.

## Additional Context

- Plugin Version: 1.27.0-alpha.0+f412972
- WordPress Version: 6.1
- Operating System: win10
- Browser: Chrome

### PR DESCRIPTION
**Pull request by timarney**
## Context

There are multiple styling issues with the story block selector i.e. see: https://github.com/GoogleForCreators/web-stories-wp/issues/12620#issue-1435487391

## Summary

Tested on Mac (Chrome, Firefox and Safari) -- not tested on Windows.

- Updates  Z-Index for dropdowns

|  Before | After  | 
|---|---|
|  z-index |  Screen Shot 2022-11-08 at 6 08 16 AM

- Fixes `Sort`  dropdown alignment 

Step 1 removing grid gap + updating select height

|  Before | After  | 
|---|---|
|  Screen Shot 2022-11-08 at 6 17 06 AM |  Screen Shot 2022-11-08 at 6 11 50 AM

Step 2 pushed select down using a 1px margin to align withe the other elements

|  Before | After  | 
|---|---|
| 1px-off  | aligned

- Updates Modal Content Area height  to reduce white space

|  Before | After  | 
|---|---|
|  before |  bottom-edge 

## Relevant Technical Choices

The code previously used `height: calc(100% - 110px);`

I tested with the height set to 100% without the calc --- this seemed fine but resulted in cut-off content see "published" date when the story has a longer title

cut-off

Adding a 20px margin accommodates for this which matches the 20px of padding

no-cutoff

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. As an editor or above, create a WP post and embed web story carousel block into it
2. Now pick a list type carousel and select stories to add to the list
3. An overlay opens that allows user to select stories
4. Note the styling updates from PR description above. 

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12620

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Screenshot 2022-11-09 at 13 03 43

Still seeing z-index issue.

**Comment by spacedmonkey** [comment]
Is it too cheeky to ask to add an e2e test with a screenshot? This part of the code is not well covered by tests and a screenshot would go a long way to see future regressions in this part of the code.

**Comment by spacedmonkey** [comment]
Other than flagged issue above, the issues are fixed. Good work.

**Comment by timarney** [comment]
@spacedmonkey --- have any more info on the "checkbox" z-index issue --- I haven't been able to re-produce yet.

select

**Comment by spacedmonkey** [comment]
Not doing anything special. 


https://user-images.githubusercontent.com/237508/200906601-177ad725-4c03-492c-9862-02b0aa68dae2.mov

**Comment by timarney** [comment]
@spacedmonkey --- okay I re-created so I can look into what's going on now ...  for some reason seeing different results with dev tools open vs closed.


https://user-images.githubusercontent.com/62242/200910075-a3acb8d6-c1c7-489f-aefe-4fa6fbaddbb3.mp4

**Comment by timarney** [comment]
@spacedmonkey - I pushed an update let me know if that does the trick.

**Review by spacedmonkey — APPROVED** [review]
Works well!

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
Verified this fix via https://stories-qa-wordpress-amp.pantheonsite.io/block-fix-stories-selector-styling-issues/

- now the z-index is updated to show the drop down properly (even when the story underneath is checked)


- grid gap and margins are updated


- verified the overall functionality of adding/rearranging/removing/publishing the list of stories (with different forms of display: box, circle, grid, list

**Comment by kkalarickal** [comment]
I tested this on window11 running Chrome/FIrefox/Opera/Edge

QA Notes: On firefox, the rearrange overlay did not allow me to move the stories by clicking on the cover image !! I could onlu rearrange when I dragged the title area ... 

Also, the search story function does not allow me to search for common terms. LIke I can filter from the stories, but it will only search for full titles from the drop down list. SO if there are three stories that have "test" in the title, I cannot seach for "title" and list all three !!

**Comment by timarney** [comment]
> the search story function does not allow me to search for common terms. LIke I can filter from the stories, but it will only search for full titles from the drop down list. SO if there are three stories that have "test" in the title, I cannot seach for "title" and list all three !!

Sounds like this could be looked at in a separate ticket

**Comment by swissspidy** [comment]
Yes, new tickets.

* #12703
* #12704

**Pull request merged**
