### PR TITLE
Floating Menu: Border Color Eyedropper Regression

### LINKED ISSUE #11216: Color picker from floating menu is not working as expected
## Bug Description

When I pick a color from floating menu after I selected a color on the right side (or left side) menu, under Style, the color doesn't change (color selected on Style menu prevails). I need to drag and drop the element so that the new color is set.

## Expected Behaviour

Color should be applied at the same second as it was selected.

## Steps to Reproduce

1. Open the editor
2. Add an image element
3. Add a border to the element
4. Click on the element and pick a color from Style menu - color is set
5. Click on the element and pick a color from floating menu - color is not set, unless user drags and drops the element (see video attached)

## Screenshots

https://images.zenhubusercontent.com/235435637/dde978ad-e7b3-4fbf-bd24-93b84c386a88/2022_04_07_16_30_24.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Felipe reported a regression here: #11216

## Summary

Wasn't seeing the same regression as @felipebochehin87  but a change in the borderWidthAndColor was overwritten which was hiding the eyedropper on the floating menu border color picker. 

## Relevant Technical Choices

Just putting the `borderWidthAndColor` color picker back to the props it needs for the eyedropper.  (see https://github.com/GoogleForCreators/web-stories-wp/pull/11075/files)

## User-facing changes

Be able to update border color from floating menu color picker with a swatch or the eyedropper or the slider and for it to stay in sync with the border color selected in the style panel. 

## Testing Instructions

(Bug reproduction steps copied from #11216)
1. Open the editor
2. Add an image element
3. Add a border to the element
4. Click on the element and pick a color from Style menu - color is set
5. Click on the element and pick a color from floating menu - color is not set, unless user drags and drops the element 

Selected color in floating menu and in sidepanel should remain in sync. 

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11216

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
👍 works for me

**Review by maxyinger — APPROVED** [review]

**Comment by BrookeGraham** [comment]
Rectangle shapes are still getting stale colors.
retangle color

**Review by BrookeGraham — CHANGES_REQUESTED** [review]
Some shapes are updating correctly, but not all 🤔

**Comment by BrittanyIRL** [comment]
@BrookeGraham would you look at this again? I went back to the initial solution and one thing we had to do was remove the `changedStyle` from the border color in the floating menu. This was added because it existed in the sidepanel implementation. It seems that just removing that from there as well fixes this inconsistency. At least I think it does?

**Review by BrookeGraham — APPROVED** [review]
Nice. All shapes, borders and text seem to be working now.

**Pull request merged**
