### PR TITLE
Dashboard: Theme Clean Up

### PR DESCRIPTION
**Pull request by BrittanyIRL**
# Overview
When we first started working on the dashboard we were trying to follow the theme pattern of edit-stories. The context of the two sides of the project are a bit different in what we're making though so we started doing our own thing and then the theme had several different patterns in it. This is a first pass/attempt at consolidating some of that. My hope is that as we get the new designs and implement them we can continue cleaning up. This just gives us a cleaner starting point for that. 

- Gutted px/em from theme and set units in styled components 
- gave borders an object since we repeat the same 2 (mostly) all over 
- gave font families an object for primary and secondary instead of having strings that say 'google sans' all over the place! 
- cleaned up the few spots where we had theme[style-attribute][component] to always be theme[component][style-attribute]. 

I still feel like a lot of the theme could be tightened up but am holding until we have our designs and know our patterns. I would love to see the font section tightened up so we have our headings and body and that the other components rely on those instead of everything having it's own. 

## Testing
- Run storybook and dashboard, see that styles are holding

### CODE REVIEW

**Review by carloskelly13 — CHANGES_REQUESTED** [review]
This looks good. One stylistic point is we don't actually need to do
```
font-size: ${({ theme }) => `${theme.fonts.body1.size}px`};
```

We can actually drop the inner ttl and make the unit as part of the outer one.

`font-size: ${({ theme }) => theme.fonts.body1.size}px;`

This would reduce the amount of interpolation and simplify it. Other than that, I think this is a great clean-up.

**Comment by BrittanyIRL** [comment]
> This looks good. One stylistic point is we don't actually need to do
> 
> ```
> font-size: ${({ theme }) => `${theme.fonts.body1.size}px`};
> ```
> 
> We can actually drop the inner ttl and make the unit as part of the outer one.
> 
> `font-size: ${({ theme }) => theme.fonts.body1.size}px;`
> 
> This would reduce the amount of interpolation and simplify it. Other than that, I think this is a great clean-up.

Good call, was just doing a find and replace of px and paying no attention to the rest of it, thanks for calling it out!

**Review by mariano-formidable — APPROVED** [review]
I agree with Carlos' comment, and once that's updated then it's good to merge.  Nice job cleaning things up!

**Review by carloskelly13 — APPROVED** [review]

**Review by swissspidy — COMMENTED** [review]
Nice changes here by the way 👍 sounds like something we should do in the editor part as well.

**Pull request merged**
