### PR TITLE
Improve Text Presets smart color performance

### LINKED ISSUE #8238: Enable feature: Text presets: smart color
## Feature Description
The feature "Text presets: smart color" is currently behind a feature flag. For more context: https://github.com/google/web-stories-wp/pull/8118#discussion_r665745831

- [x] Start the image generation when hovering on the library header generally (or at least more widely on the Text tab) instead of directly on the `+` quick-action icon, to get the image ready sooner.
- [x] Do color calculation when hovering on the preset.
- [x] Skip image generation if presets are added one after another (since it's placed below the previous, no need for new image)
- [ ] Add opt-in toggle for using the feature
- [ ] Mark the feature flag `true` by default.

## Additional Context
image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief
- Remove the feature flag (or better -- just mark `true` by default`).
- Do the color calculation already when hovering over the preset, we should already be able to get the information before the click is done.
- If possible, skip image generation if the preset is added below the previous since the area that's being used for calculation is not influenced by the previous text. This would improve the situation only for consecutively added text presets. We would need to move the previously added preset data ref higher up for it being accessible in the places needed.

- Generate the image when hovering anywhere on the text tab of the panel, not just the quick action item specifically.

### PR DESCRIPTION
**Pull request by miina**
## Context

Enabling the smart color feature is delayed due to performance reasons -- the insertion of an element is already lagging and this adds some additional latency.

## Summary
This PR does the following:

- Calculates the accessible color for the presets already when rendering, so when it's clicked on, the color is ready. Same for the position.
- If the preset is added below the previous preset, skips the canvas generation.

## User-facing changes
N/A

## Testing Instructions
N/A

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Partial for #8238

### CODE REVIEW

**Review by barklund — COMMENTED** [review]
I'm still experiencing quite a lag when clicking the text presets. When profiling, that lag is recorded at about 1s per click. It's less without profiling, but still significantly more than 50ms.

Not really sure if we can optimize this much more at this stage without drastically changing some things?

**Comment by miina** [comment]
> I'm still experiencing quite a lag when clicking the text presets.

@barklund Is this compared to the option without the auto-color logic? The idea of this PR is to reduce the lag added by the auto-color logic, not reduce the insertion lag which already exists without enabling the smart color experience.

**Comment by miina** [comment]
Btw, this PR is still not enabling the experiment by default, the feature still remains behind the feature flag.

Not sure indeed what else could be done.

**Review by barklund — APPROVED** [review]
It's still not fantastic, but it's better than before. I think most of our slow problems existed long before we added text magic. Let's send it to QA

**Comment by swissspidy** [comment]
Moved to QA column so it's actually on QA's radar :-)

Note that there are some merge conflicts now.

**Comment by merapi** [comment]
> It's still not fantastic, but it's better than before. I think most of our slow problems existed long before we added text magic. Let's send it to QA

I think most of the PRs that will improve it are still not merged to main. When that happens I will just post the pre/post difference somewhere here.

**Comment by miina** [comment]
@barklund This doesn't have any easily QA-eable changes, we could probably just merge once the checks pass, the text presets smart color feature (still behind a feature flag) has passed the QA already separately.

Thoughts?

**Pull request merged**
