### PR TITLE
Update several npm dependencies

### PR DESCRIPTION
**Pull request by swissspidy**
## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it
- [ ] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
No idea why those e2e tests fail... It's only the ones involving other users. 🙃 🤷

**Comment by swissspidy** [comment]
All e2e tests involving non-admin users are failing. I'm a bit at loss as why this happens. 

Looking at the artifacts, they seem to be stuck at the very beginning when trying to create a new story and typing the story title:

Quick-Edit-should-save-story-without-breaking-markup-2024-03-28T09-02-35

As if none of the `toClick()` or `page.type()` would work, but then why are they working for other users...?

Maybe there are some console errors that aren't being logged?

To reproduce:

```

# Build plugin
DISABLE_PREVENT=true DISABLE_QUICK_TIPS=true npm run build

# Spin up Docker environment
npm run env:start

# Run all tests...
npm run test:e2e

# or just a specific one...
npm run test:e2e packages/e2e-tests/src/specs/wordpress/quickEdit.js

# Or with headless disabled so you can see what's going on
PUPPETEER_HEADLESS=false npm run test:e2e
```

@AnuragVasanwala @Swanand01 maybe you have some ideas off the top of your head? Does `npm run test:e2e packages/e2e-tests/src/specs/wordpress/quickEdit.js` fail for you on this branch?

**Comment by AnuragVasanwala** [comment]
> Does `npm run test:e2e packages/e2e-tests/src/specs/wordpress/quickEdit.js` fail for you on this branch?

Yes, it does fail for us on this branch.

> @AnuragVasanwala @Swanand01 maybe you have some ideas off the top of your head?

We are trying to figure out what went wrong!

**Comment by swissspidy** [comment]
Closing this in favor of updating stuff individually, that will be easier to do.

**Pull request closed without merging**
