### PR TITLE
Remove custom `rest_preload_api_request` fork

### LINKED ISSUE #12622: Remove custom `rest_preload_api_request` function
## Task Description

Now that we bump our minimum requirement to WordPress 5.9, we no longer need our custom `rest_preload_api_request()` function since the issues it addresses were resolved in WP 5.7 and WP 5.9.

Needs some testing to ensure that the preloading still works 100%.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Remove custom `rest_preload_api_request` as not needed with WP 5.9 as min. 

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12622

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
So the e2e tests seem to be failing and from what I can see, the preloading is not actually working anymore.

Maybe still an issue with how core's function handles embeds or something.

**Comment by spacedmonkey** [comment]
@swissspidy Sadly, it is seems we were too early on this one. There is another tweak that was made to `rest_preload_api_request` function that is breaking preload. These lines. 

https://github.com/GoogleForCreators/web-stories-wp/blob/9be7522faeabc70a296444e49e512ed9ec5f1f83/includes/namespace.php#L211

**Comment by swissspidy** [comment]
Ah yes, the trailing slashes issue.

Wasn't that supposed to be fixed by https://core.trac.wordpress.org/ticket/51636?

**Comment by spacedmonkey** [comment]
> untrailingslashit

Sadly it seems like it was not :( We can't use that function from core then.

**Comment by spacedmonkey** [comment]
> > untrailingslashit
> 
> Sadly it seems like it was not :( We can't use that function from core then.

I will report upstream.

**Pull request closed without merging**
