### PR TITLE
Leverage Prettier

### PR DESCRIPTION
**Pull request by swissspidy**
See #144.

### CODE REVIEW

**Comment by swissspidy** [comment]
The code style with this Prettier config here is quite a big change from the current formatting. We might still want to keep spaces within brackets and things like that.

**Comment by wassgha** [comment]
> The code style with this Prettier config here is quite a big change from the current formatting. We might still want to keep spaces within brackets and things like that.

Is this ready?

**Comment by swissspidy** [comment]
I'd need to merge the latest changes & re-format everything first. And maybe tweak the config a little bit with the spacing, as mentioned. I can do that today though.

**Comment by wassgha** [comment]
Sounds good! No hurry :)) Have a great weekend!

**Comment by swissspidy** [comment]
Let‘s get at least 2-3 reviews on this

**Review by wassgha — APPROVED** [review]
The rules look good to me

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
@swissspidy I will approve it you fix conflicts.

**Comment by swissspidy** [comment]
Resolved conflicts once again

**Review by miina — APPROVED** [review]

**Comment by spacedmonkey** [comment]
@swissspidy Can you fix merge conflicts and merge. I want this merge ASAP to stop conflicts.

**Comment by swissspidy** [comment]
In a few hours after I land 👍

**Review by dvoytenko — APPROVED** [review]

**Pull request merged**
