### PR TITLE
Run tests against WordPress 6.1 RC

### LINKED ISSUE #12410: Run tests against WordPress 6.1 RC
We'd want to test against WordPress 6.1 as soon as the first RC is released, so we can track our progress on ensuring compatibility.

This should be in addition to running against latest.

### PR DESCRIPTION
**Pull request by timarney**
## Context

We'd want to test against WordPress 6.1 as soon as the first RC is released, so we can track our progress on ensuring compatibility.

This should be in addition to running against latest.

## Summary

Adds WP 6.1 RC 1 to workflow files

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12410

### CODE REVIEW

**Comment by swissspidy** [comment]
We should wait for the RC to be released first :-)

**Comment by spacedmonkey** [comment]
@timarney Not seeing test passing.

**Comment by swissspidy** [comment]
> @timarney Not seeing test passing.

Not surprising, e2e tests are also flaky on main, which is why I have been working on stabilization. See #12439 

But that‘s ok. This PR is for adding tests. Fixing bugs can be done in later PRs

**Review by swissspidy — APPROVED** [review]

**Comment by spacedmonkey** [comment]
That is not what I meant. Not running, is what I meant in this context. I guess it is not important now it is merged.

**Pull request merged**
