### PR TITLE
Template Updates: Cooking

### LINKED ISSUE #6970: Template Updates: Cooking
## Description 

April 6, 2021 - Updates from Figma since original creation of ticket are **BOLD**, please cross reference with figma.

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 |  Headline should be updated to editor "fly in" instead of custom "move". Border animation updated to fade in. **Oranges image to fade in (3000ms)** | change orange color to **#3A566E** |
| 2 | Quote should be fly in animation instead of custom "move"; fade in radishes; remove animation from background.  | Combine radish shapes; change background color to  **#3A566E** ; remove frame shape. |
| 3 |  Headline and text changed to fly in animation instead of custom "move"; frame shape to fly in; **Image to fade in (3000ms)** remove animation on persimmon on left; |  Combine persimmon shape; combine frame shape; combine arrow shape; increase view more font to 12px; change orange color to **#3A566E**; |
| 4 |  Headline and subheading should change to fly in animation instead of custom "move". Background color should fly in (double check this one); remove animation on veggies.  | Combine all the veggie shapes; combine frame shape; update orange color to #000; remove frame shape.  |
| 5 | headline and subheading should change to fly in animation instead of custom "move"; background animation should be removed; remove animation on everything else.  | Remove frame shape. |
| 6 | heading and text updated to fly in instead of custom move; fade in numbers; remove animation on image.  | **Remove** grid shape; combine arrow shape; increase "discover them" font to 12px; change orange color to  **#3A566E** **Text Updated** |
| 7 | frame should be updated to fade in; headline and text should fly in. **Image to fade in (3000ms)**  | **Remove** grid shape; combine arrow shape; increase learn more font to 12px; change orange color to  **#3A566E**. |
| 8 | frame should be updated to fade in; headline and text should fly in. **Image to fade in (3000ms)** | **Remove** grid shape; combine arrow shape; increase view more font to 12px; change orange color to  **#3A566E**. **Page went through some redesign - number is over text now.** |
| 9 |  Frame should be updated to fade in; headline should fly in, text should fly in. **Image to whoosh in (2000ms)**| **Remove** grid shape; change orange to  **#3A566E**. |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created
- - No more custom animations

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
Part of first round of template updates. updates recommended animations to current effects. Updates designs. New animation effects to be created before second round, then go over remaining unsupported animations and replace with thos.

## Summary
Updates recommended animations to current effects. Some design updates too. follows this doc:
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/6970

https://user-images.githubusercontent.com/41136059/114252958-cf5dbd00-995c-11eb-9ac3-f90527166755.mp4

Screen Shot 2021-04-09 at 5 56 22 PM

## Relevant Technical Choices
NA

## To-do

- [x] Design review

## User-facing changes
Updates cooking template with updates described in ticket:
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/6970

## Testing Instructions
View cooking template and see that these changes took place:
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/6970

### QA
Follow testing instructions above.

- [ ] This is a non-user-facing change and requires no QA

### UAT

- [x] UAT should use the same steps as above.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6970

### CODE REVIEW

**Comment by embarks** [comment]
@googlebot I consent.

**Review by samwhale — APPROVED** [review]
This is dope. Some questions:

1. Do these little lines need to be orange?

|Designs|Current|
|--|--|
|image|image|

2. I think this needs some letter spacing (page 6)

|Designs|Current|
|--|--|
|image|image|

**Comment by maxyinger** [comment]
@samwhale ahh good catches. Will update them rn

**Comment by BrittanyIRL** [comment]
> This is dope. Some questions:
> 
> 1. Do these little lines need to be orange?
> 
> Designs	Current
> image	image
> 1. I think this needs some letter spacing (page 6)
> 
> Designs	Current
> image	image

Updated!
Screen Shot 2021-04-12 at 2 12 13 PM
Screen Shot 2021-04-12 at 2 12 03 PM

**Review by BrittanyIRL — APPROVED** [review]
Ran through everything while updating stickers and colors, looks good!

**Comment by BrittanyIRL** [comment]
@googlebot I consent.

**Review by embarks — APPROVED** [review]
🤝

**Comment by ivayloklissarov** [comment]
Small fixes:

Page 1
- Remove logo animation
Screen Shot 2021-04-14 at 3 37 28 PM

Page 2
- Change "Anonymous" text delay to 400ms
Screen Shot 2021-04-14 at 3 38 50 PM

Page 3
- Change both text duration to 1400ms and delay to 200ms
Screen Shot 2021-04-14 at 3 40 41 PM

Page 4
- Change all text duration to 1400ms
Screen Shot 2021-04-14 at 3 42 38 PM

Page 5
- Change all text duration to 1400ms
Screen Shot 2021-04-14 at 3 43 30 PM

Page 6
- Change title text (top 8 & recipes with persimmon) animation to Fade In 3000ms
- Change duration of the other text below to 1400ms
Screen Shot 2021-04-14 at 3 45 44 PM

Page 7
- Change all text duration to 1400ms
Screen Shot 2021-04-14 at 3 47 56 PM

Page 8
- Change all text duration to 1400ms
Screen Shot 2021-04-14 at 3 48 57 PM

Page 9 
- Change title animation to Fade In 3000ms
- Change duration of images to 1400ms
- Change position coming from left and duration to 1400ms for the other text
Screen Shot 2021-04-14 at 3 52 10 PM

**Comment by BrittanyIRL** [comment]
Updated! thanks!

Ignored the orange border since it's specified as "remove frame shape" in figma, we can add it back in if you want 

> Page 1
> 
> * Remove logo animation

cooking 1


> Page 2
> 
> * Change "Anonymous" text delay to 400ms
 
cooking page 2


> Page 3
> 
> * Change both text duration to 1400ms and delay to 200ms

cooking page 3

> Page 4
> 
> * Change all text duration to 1400ms

cooking page 4


> Page 5
> 
> * Change all text duration to 1400ms
> 

cooking page 5


> Page 6
> 
> * Change title text (top 8 & recipes with persimmon) animation to Fade In 3000ms
> * Change duration of the other text below to 1400ms

cooking page 6

> Page 7
> 
> * Change all text duration to 1400ms

cooking page 7


> Page 8
> 
> * Change all text duration to 1400ms

cooking page 8


> Page 9
> 
> * Change title animation to Fade In 3000ms
> * Change duration of images to 1400ms
> * Change position coming from left and duration to 1400ms for the other text

cooking page 9

**Pull request merged**
