### PR TITLE
Disable `react/jsx-no-target-blank` rule

### LINKED ISSUE #10827: ESLint: Disable `react/jsx-no-target-blank` rule
## Task Description

The `react/jsx-no-target-blank` rule is obsolete, since all the browsers we currently support automatically imply `rel="noopener"` when using `target="_blank`.

Also, `rel="noreferrer"` was only needed originally for browser that didn't support `noopener`.

### Acceptance Criteria

* [ ] `react/jsx-no-target-blank` ESLint rule is disabled
* [ ] No `rel="noreferrer"` `rel="noopener"` anymore in the JS code base
* [ ] Remove `noopener` and `noreferrer` from `PluginRowMeta` as well

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Remove noreferrer / noreferrer attributes from links. These are not needed as browsers do this out of the box. Disable the lint rule and remove all references in code, tests and in php. 

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10827

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@swissspidy Any thought on lgtm warning? 

> 4 for Potentially unsafe external link

Should I disable these warning and fix them.

**Comment by swissspidy** [comment]
Yes suppressing is what I had in mind here. But it looks like this also triggers some code scanning warnings in GitHub (you cannot see them as you are not an admin) and I'd need to find a way to suppress those globally instead of individually.

Looks like not all the tooling has fully updated yet with what browsers do these days.

**Comment by swissspidy** [comment]
Marking as draft again because I need to find a way to suppress the GitHub code scanning warnings, as per previous comment.

If I cannot find a way for that, I am afraid this might need to go back to the backlog.

**Comment by spacedmonkey** [comment]
@swissspidy I marked it as ready for review believed I fixed the issues with lgtm.

**Comment by swissspidy** [comment]
This also triggers some code scanning warnings in GitHub.

You cannot see them as you are not an admin.

These are the warnings I need to figure out a solution for.

**Comment by swissspidy** [comment]
Closing this one for now as per the above comment. We'll need to revisit this later.

**Pull request closed without merging**
