### PR TITLE
Video in Media Library 

### LINKED ISSUE #39: Video in Media Library
## Feature description

Find elegant way to display video in the media gallery when you need it.

**[Epic: Media upload and management](https://docs.google.com/document/d/1aZH_TI_be2t5Ywyqx4jcPTPdhFGEt7xh-uLzBp2AV4A/edit#heading=h.2d83f6r6hu5x)**
---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

1. Show poster image
2. List Duration
2. Play icon (is just autoplay on hover)
3. Autoplay on hover (muted?) See #26 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by spacedmonkey**
Fix styling video styling in media library.

Fixes #39

### CODE REVIEW

**Comment by miina** [comment]
Looks good, one minor note: currently, the length of the video is displayed also when dragging (e.g. when dragging to a shape) -- is that intended or is there a way to avoid that?

(Can also discuss later, not that big of a deal, I suppose)

**Comment by spacedmonkey** [comment]
Good question @miina 

I don't know, there is nothing in the figma about it. I have hidden the duration over hover for now, which fixes the issue. I will bring it up to Sam next time I speak to her.

**Comment by miina** [comment]
>  I have hidden the duration over hover for now, which fixes the issue.

Which change is that, can still see it locally, perhaps you forgot to push?

**Comment by spacedmonkey** [comment]
> Which change is that, can still see it locally, perhaps you forgot to push?

Git hook stopped the push 🤦‍♂

**Review by miina — APPROVED** [review]

**Pull request merged**
