### PR TITLE
Story Locking: Change interval to 60 seconds

### LINKED ISSUE #12435: Story Locking - delay in notification allows for concurrent editing by more than one user
## Bug Description

If someone takes over your story, you are not informed immediately. But you are allowed to make changes and save them (thus effectively still being in control) for a few minutes. I get that we can’t push the take over message instantly to the client, but we should at least not allow saving and display the message as an error if you do try to save.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Now that the internal of when post locking is checked, down to 60 seconds over 150 seconds. This will improve when take over dialog is shown. 

60 seconds brings this inline with WordPress cores heartbeat api. 

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Enable post locking take over. 
2. Create a story. 
3. Add title. 
4. Save draft. 
5. In another window. Login as another user. 
6. Edit draft story. 
7. Take over story. 
8. return to original Window. 
9. Wait 60 seconds for dialog to show. 

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12435

### CODE REVIEW

**Comment by swissspidy** [comment]
> 60 seconds brings this inline with WordPress cores heartbeat api.

Where is that defined in core btw?

**Comment by swissspidy** [comment]
Also, @kkalarickal does this resolve the time discrepancy you've seen between story editor and post editor? Looks like now both should be checking the lock every 60s

**Comment by spacedmonkey** [comment]
> > 60 seconds brings this inline with WordPress cores heartbeat api.
> 
> Where is that defined in core btw?

Good question. This took me a while to find. [Here](https://github.com/WordPress/wordpress-develop/blob/a7a9e7602c51785de5261c15d8a720c535e829bf/src/js/_enqueues/wp/heartbeat.js#L62-L63). But you can change with a filter like [this](https://github.com/wp-media/heartbeat-control/blob/17ad6264e165766d4b792d73481b807219016001/Heartbeat.php#L122).

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
Confirmed that without the fix, the call to lock happens at a 2-3-2-3-2-3 min interval

After loading `12510 branch` the story locking is happening at 1 min intervals

@swissspidy .. as regards the discrepancy between story editor and post editor, this definitely makes it more snappy repose when someone takes over and the original author tries to edit. I feel this is a good improvement in how the user would expect the story locking to work.

**Pull request merged**
