### PR TITLE
Story Details Modal: Remove Experiment 

### LINKED ISSUE #10594: Remove Updated Publish Story Modal Experiment
After 1.18 release we should remove experiment for new publish story modal and remove old flow. 

See #10115 for work related to new publish story modal

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Removing experiment code now that feature has been enabled for a release cycle. 

## To-do

Looks like some tests need updating, will tend to that here when I get a chance.

Will clean up the checkpoint provider separately here: #10470  (old dialog, names of state that control if that exclamation mark shows up on buttons)

## User-facing changes

None. 

## Testing Instructions

When 'publish' in header is selected should still se story details modal. Experiment should be gone from list of experiments. 

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10594

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
Seeing the modal with every role. All roles except contributor can publish 👍

**Review by maxyinger — APPROVED** [review]

**Review by BrookeGraham — APPROVED** [review]
🌵

**Comment by swissspidy** [comment]
Some Karma tests for the review checklist are failing now

**Comment by BrittanyIRL** [comment]
> Some Karma tests for the review checklist are failing now

Thanks yeah, that's why i moved it back to in progress. I've been busy with sidebar/floating menu priorities. it's on my list to get back to.

**Comment by swissspidy** [comment]
@BrittanyIRL FYI this needs a rebase now

**Comment by BrittanyIRL** [comment]
Just going to close this for now as i just haven't had time to come back to it.

**Pull request closed without merging**
