### PR TITLE
Include `fonts.json` in `fonts` package dist folders

### LINKED ISSUE #10537: Fonts package doesn't have font list
fonts package currently only releasing javascript files, and don't have `packages/fonts/src/fonts.json` file and this is feature request not bug.

### PR DESCRIPTION
**Pull request by mohdsayed**
## Context

Copy `fonts.json` to fonts pacakge dist folders. See https://github.com/GoogleForCreators/web-stories-wp/issues/10537

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes https://github.com/GoogleForCreators/web-stories-wp/issues/10537

### CODE REVIEW

**Comment by mohdsayed** [comment]
Tested with a consumer project and I was able to import using 

```js
import fonts from '@googleforcreators/fonts/dist-module/fonts.json';
```

**Comment by swissspidy** [comment]
Hmm I wonder how we can best make this work as just `import fonts from '@googleforcreators/fonts/fonts.json';`

Maybe with a custom `exports` definition in `package.json`?

I've experimented with that in the past.

**Comment by mohdsayed** [comment]
`import fonts from '@googleforcreators/fonts/fonts.json';` working now on consumer project.

**Comment by swissspidy** [comment]
> `import fonts from '@googleforcreators/fonts/fonts.json';` working now on consumer project.

That's awesome 🚀 

Curious, can we adapt https://github.com/GoogleForCreators/web-stories-wp/blob/2010a9b3f6a43596b8eff792f6ac3dbca9add3b8/.storybook/stories/playground/story-editor/api/fonts.js#L18-L20 now too because of that?

**Comment by mohdsayed** [comment]
Hmm, we should be able to adapt however since our custom `exports` tries to read from `dist-module` it wouldn't be available until we run `workflow:bundle-packages` to create those folders. I tried to bundle packages and ran storybook ( even on `main` branch ), but then both the dashboard and storybook looked broken already with errors like these

image

image

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
