### PR TITLE
remove cors on loadStylesheet

### PR DESCRIPTION
**Pull request by BrookeGraham**
## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
AFAIK this is needed for html-to-image. And probably for when video optimization is enabled as well.

**Comment by BrookeGraham** [comment]
Oh I’m Sorry @swissspidy I should have added more context. We are trying to debug why the story editor karma suite is failing. We’ve narrowed it down to the new font provider. It seems that before we had a mocked font provider for the Karma tests, but now that it has been removed the test suite is getting stuck when trying to get the fonts for any tests in the editor. Typically this would be the Roboto font as that is the default one used.

**Comment by BrookeGraham** [comment]
Now that we have a little more insight as to what is happening, I think it’ll be a matter of mocking the font provider and I shouldn’t need to remove the crossorigin

**Comment by BrookeGraham** [comment]
See [10052](https://github.com/google/web-stories-wp/issues/10052) for more information.

**Pull request closed without merging**
