### PR TITLE
Allows edit text as soon as user type while selecting a text element

### LINKED ISSUE #830: Enable Editing Text as soon as Text Box is in Focus
## Bug Description

The default rules for selecting and editing text are not applied as specified in [figma](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2625%3A7057)

When a user adds text, they see the hint within the text box (fine):
image
But when they click within, they have to manually delete or overwrite this tip ("Double-click..."). Should the tip automatically "clear" when user clicks within the field?

Note: This issue does not deal with automatically enabling edit-mode when a new text field is added. This is only about being able to type while text box is in focus to edit content.

Reported by Claudio on #576
## Expected Behaviour

1. You should be able to just start typing once the text box is in focus

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### Alphanumeric: Replace with new content
1. Add a text field
1. Unselect and reselect the text field using the mouse to make sure it has keyboard focus
1. Type any alphanumeric character and observe text field going into edit mode with only the typed character (NB: this only supports a-z and 0-9)

### Enter: Select content
1. Add a text field
1. Unselect and reselect the text field using the mouse to make sure it has keyboard focus
1. Press <kbd>enter</kbd> and observe text field going into edit mode with all the currently present content selected and ready to be replaced by whatever is typed next. Also observe, that no actual newline is inserted despite pressing <kbd>enter</kbd>

### LINKED ISSUE #1608: Typing while having single text field selected does not work
## Bug Description

When you have a single text field selected, you can enter edit mode in a number of ways:

* By clicking enter (enters edit mode with entire content selected)
* By clicking with the mouse (enters edit mode with cursor placed at click)
* By typing any (printable) character (enters edit mode, clears the text field and replaces it with the character pressed).

However this latter method is broken since #1323. Now typing a single character does enter edit mode and does delete the contents, but does not insert the pressed character.

## Expected Behaviour

* When typing a single character while having a text field selected but not in edit mode, the element should enter edit mode with the entire contents of the text field replaced by the character pressed and the cursor located after the character.

## Steps to Reproduce

1. Add a text field and make sure it's selected, but not in edit mode
2. Press W on the keyboard
3. Observe that edit mode is entered, content is cleared, but W is not inserted into text field.

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## QA Instructions

1. Add a text field
1. Unselect the text field by clicking the background
1. Select the text field using the mouse by clicking on it a single time
1. Type any alphanumeric character and observe text field going into edit mode with only the typed character (NB: this only supports a-z and 0-9)

### PR DESCRIPTION
**Pull request by obetomuniz**
## Summary

This PR fixes text element edit mode to allows insert content when user select text element and press some character 

## Relevant Technical Choices

After some debug work, I noticed that we have some similar expected behavior on the already working implementation of <kbd>Enter</kbd> action, so I just improve the method to allow both scenarios.
 
---

Solving #830 
Fixes #1608

### CODE REVIEW

**Review by barklund — APPROVED** [review]
This works great. And this also fixes #1608 btw!

**Review by barklund — CHANGES_REQUESTED** [review]
Now that we have the new integration test setup, could we add a test for this too? Both entering edit mode by clicking, pressing enter and typing a key? And of course validate selection and text field contents afterwards?

**Comment by barklund** [comment]
@googlebot I consent.

**Review by barklund — APPROVED** [review]
Tests are good, progressing to QA

**Comment by merapi** [comment]
@obetomuniz I found 3 issues (2 in gif), should we handle them here?
- Pressing Enter or typing text doesn't work as expected for a newly inserted text element (in tests we click on the canvas first, so maybe it's related to focus issues?).
- After editing the text and then exiting (Escape) - Enter or typing doesn't work as expected.
- ^Same when the text is lasso selected.

texttype

**Comment by obetomuniz** [comment]
Hey @merapi, I already mapped them for a follow-up PR on #1808 and #1830 since it is not happening only with Text Element.

**Comment by merapi** [comment]
> Hey @merapi, I already mapped them for a follow-up PR on #1808 and #1830 since it is not happening only with Text Element.

Ok, I guess it's the same case with lasso selection.

**Comment by barklund** [comment]
@obetomuniz, are you following up on this after QA failed?

**Comment by obetomuniz** [comment]
Hey @barklund, the QA failing on #830 is related to PR#2183, not this one, or should I consider something else from that report? Likewise, the QA reported on #1608 is related to #1808, which will be fixed by the global focus issue PR. Should I block this one until we get global focus issue solved?

**Pull request merged**
