### PR TITLE
Fixes crashes when selecting items

### PR DESCRIPTION
**Pull request by wassgha**
### Changes
- Fixes loop in size/position panel caused by unnecessary effect

### CODE REVIEW

**Review by dvoytenko — APPROVED** [review]

**Comment by dvoytenko** [comment]
We need to merge this to unblock. But can we discuss what was the purpose of this code and if there's a right way to do this?

**Comment by miina** [comment]
This just means that now clicking on the Fill toggle won't trigger right away but only `onBlur`. I guess that's something that will get fixed within #432 separately, @obetomuniz?

**Comment by miina** [comment]
@dvoytenko @wassgha It looks like the endless loop happens due to the text element having `isFill` `undefined`, while media having it set. This basically causes the state to switch between `undefined` and whatever the Media element has assigned, causing an endless loop.

Perhaps it would make sense to make `isFill` an uncontrolled component to manage its own state so that only the shared values would all be handled together. WDYT?

**Comment by miina** [comment]
Perhaps also the flip controls should manage their own state since these are also not displayed for the Text element currently.

**Comment by miina** [comment]
E.g. this PR should work OK and also apply the flip/fill toggle instantly instead of waiting for `onBlur`: https://github.com/google/web-stories-wp/pull/534

**Pull request merged**
