### PR TITLE
Dashboard: Allow dashboard filters on both grid and list view

### LINKED ISSUE #11767: Dashboard: Add All Filters to List View
## Feature Description

As a part of our Filters improvement and enhancement work, we should have the filters that are on the grid view of the Dashboard also be visible in the List view.

This work was originally scoped to part of #11665, but was separated to accommodate UX resourcing needs.

## Acceptance Criteria

- All filters that exist within the Dashboard Grid View should also exist as filters for the list view of the Dashboard
- This should be built in a way that adding filters in the future should work in both the List and Grid views of the Dashboard.

## Additional Context

This feedback was requested as a part of https://github.com/GoogleForCreators/web-stories-wp/pull/11625#discussion_r892222772

It may be easier to accomplish this after the core work is done with #11620
This work was originally scoped to part of #11665, but was separated to accommodate UX resourcing needs.

### PR DESCRIPTION
**Pull request by mwritter**
## Context

Added gird view dashboard filters to dashboard list view
## Summary

Removes the exclusion of the gird view filters from the list view
## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Go to the Dashboard
2. Use Dashboard filters and sort on both the 'grid view' and the 'list view'

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11767

### CODE REVIEW

**Review by sblinde — APPROVED** [review]
🐝

Well done! Thanks for adding tests too.

**Review by mflorida — APPROVED** [review]

**Comment by mflorida** [comment]
Should the issue number be at the beginning of the branch name (after feature/)?

**Comment by mwritter** [comment]
> Should the issue number be at the beginning of the branch name (after feature/)?

🤔 Im not sure if theres a standard used for branch names in this project, I believe all the branches eventually get deleted, and the actual title is how we keep track of the changes - so I dont think the branch name matters.

**Review by spacedmonkey — APPROVED** [review]

**Comment by sblinde** [comment]
Looks like this PR has enough approval to get merged and ready to go, but we'd like to merge https://github.com/GoogleForCreators/web-stories-wp/pull/11736 in first prior to this.

**Pull request merged**
