### PR TITLE
Reorganize packages

### LINKED ISSUE #4737: Package Reorganization
## Task Description

Our current repository structure has organically grown over the past year to a point where we have multiple different "packages" spread across different folders. Some of them are pretty self-contained and could be easily published standalone (e.g. all the Karma packages), others are a bit more intertwined with other packages. Some are used for build tooling, others for the WordPress integration or the actual editor.

At the same time, they all share the same `package.json` file, making it difficult to know which packages actually use a certain dependency. That's why I propose adopting [npm workspaces](https://github.com/npm/rfcs/blob/latest/accepted/0026-workspaces.md) using the newly released npm v7 version.

This would make maintenance a lot easier.

To get there we need to get our directory structure in shape to make working with our "packages" more straightforward.

### Packages

I propose making `/packages` the root for all our packages, containing the following directories (incomplete list):

| Package                        	| Status 	| Ticket / PR 	| Description                                                                                   	|
|--------------------------------	|--------	|-------------	|-----------------------------------------------------------------------------------------------	|
| `animation`                    	| ✅   	| #6042        	| Animations library.                                                                           	|
| `commander`                    	| ✅    	| #4853       	| build/release tool for the plugin                                                             	|
| `dashboard`                    	| ✅   	| #6052        	| Web Stories dashboard                                                                         	|
| `date`                         	| ✅  	| #6043        	| Date time library (based on date-fns)                                                         	|
| `design-system`                	| ✅  	| #6051        	| New design system with shared components for editor and dashboard                             	|
| `story-editor`                  	| ✅   	| #6050        	| Web Stories editor                                                                            	|
| `fonts`                        	| ✅      	| #4853       	| Provides fonts (system + Google Fonts) and their font metrics                                 	|
| `i18n`                         	| ✅  	| #6049        	| I18N library, providing helper functions                                                      	|
| `templates`                     	| ✅  	| #6044        	| Templates                                                                             	
| `text-sets`                     	| ✅  	| #6046        	| Text Sets                                                                             	
| `tracking`                     	| ✅  	| #6047        	| Telemetry library                                                                             	|
| **Jest**                       	|        	|             	|                                                                                               	|
| `jest-amp`                     	| ✅      	| #4853       	| Contains custom Jest matchers for AMP validation                                              	|
| `jest-puppeteer-amp`           	| ✅      	| #4853       	| Contains custom Jest matchers for AMP validation in Puppeteer context (depends on `jest-amp`) 	|
| **Karma**                      	|        	|             	|                                                                                               	|
| `karma-cuj-reporter`           	| ✅      	| #4853       	| (moved from `/karma`) - Our custom Karma CUJ reporter                                         	|
| `karma-failed-tests-reporter`  	| ✅      	| #4853       	| (moved from `/karma`) - Our custom Karma reporter to retry failed tests                       	|
| `karma-fixture`  	                | ✅      	|        	| (moved from `/assets/src`) - Fixtures to use in Karma tests                       	|
| `karma-puppeteer-client`       	| ✅      	| #4853       	| (moved from `/karma`) - Our custom Karma <-> Puppeteer client                                 	|
| `karma-puppeteer-launcher`     	| ✅      	| #4853       	| (moved from `/karma`) - Our custom Karma <-> Puppeteer launcher                               	|
| **WordPress**                  	|        	|             	|                                                                                               	|
| `activation-notice`            	| ✅  	| #6041        	| WordPress plugin activation notice.                                                           	|
| `e2e-test-utils`              	| ✅  	| #6048        	| Custom test utils to use in E2E tests.                                                 	|
| `e2e-tests`          		      	| ✅  	| #6290        	| The E2E tests themselves.                                                 	|
| `story-embed-block`            	| ✅   	|             	| Gutenberg block for embedding single stories.                                                 	|

More can be added as identified

### Anatomy of a package

Each package has its own README and and package-specific config files.

The repository root contains base config files that can be shared with packages.

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Reorganizes packages in `/assets/src` as outlined in #4737.

* `activation-notice` (unchanged)
* `animation` (unchanged)
* `commander` (moved from `/bin`)
* `dashboard` (unchanged)
* `date` (unchanged)
* `edit-story` (unchanged)
* `fonts` (**new**, split out from `/bin`) - contains `fonts.json` and the script to update it
* `karma-fixture` (moved from `/karma/fixture`)
* `karma-cuj-reporter` (moved from `/karma`)
* `karma-puppeteer-client` (moved from `/karma`)
* `migration` (moved from `edit-story/migration`) - used also by `dashboard` and CI, now also contains the CLI script to run migrations
* `karma-failed-tests-reporter` (moved from `/karma`)
* `karma-puppeteer-launcher` (moved from `/karma`)
* `story-embed-block` (unchanged)
* `tracking` (unchanged)

## Relevant Technical Choices

See #4737 for details

## To-do

N/A

## User-facing changes

N/A

## Testing Instructions

N/A

---

Fixes #4737

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@swissspidy Build and JS Unit tests are failing.

**Comment by swissspidy** [comment]
@spacedmonkey Yes, I am aware and working on it right now

**Comment by swissspidy** [comment]
@dvoytenko @barklund @carlos-kelly Friendly ping; any objections to moving files around like this? Basically moves all our JS "packages" to `/assets/src`

**Comment by dvoytenko** [comment]
@swissspidy I think this is definitely an improvement. But TBH I think some sort of `/packages/` or `/modules/` structure, anchored closer to the root, would work better long-term. E.g.

```
/packages
    /editor
        /src
        /docs
        config.x.js
    /dashboard
        /src
        /docs
        config.x.js
```

**Comment by swissspidy** [comment]
@dvoytenko Agreed. I think a move from `/assets/src` to `/packages` is the next step. As mentioned in #4737, my hope here is to eventually use npm workspaces to achieve such a structure in a clean way. Each package/module can then declare its dependencies, config files, etc. while some parts (like the testing infrastructure) stay global

**Comment by dvoytenko** [comment]
@swissspidy Sure. The staggered path to that layout makes sense and I think most of these changes help. But then I'd challenge a bit the move to `assets/src/karma-puppeteer-client/index.cjs`. I think that would slow you down. The `karma` tooling is already close to the root and looks like a mostly independent package. Not sure it helps you to move it to `assets`. It has quite a different configuration.

**Comment by swissspidy** [comment]
This way all the packages will be on the same level already, making the move from `/assets/src` to `/packages` easier in the future by mostly requiring search+replace and not having to deal with different directory levels.

Would you recommend leaving the karma packages as-is for now?

An alternative would be to just move eerything to `/packages` already in this PR, which would be trivial as well.

**Comment by dvoytenko** [comment]
@swissspidy Yeah. My recommendation is to move first some "helper" packages such as karma to `/packages/`, try that out, etc. And then reorg `assets` contents there as well. But that's just my 2c. If you feel like this pr is still a better approach and others agree - I'll be definitely ok with that as well.

**Comment by swissspidy** [comment]
Given that npm 7 is already in RC, it indeed seems wiser to skip this step here and just gradually move over to `/packages` structure

**Comment by swissspidy** [comment]
closing in favor of #4853

**Pull request closed without merging**
