### PR TITLE
E2E Tests: Improve flakey Publishing Flow test

### LINKED ISSUE #6238: E2E Tests: Improve flakey Publishing Flow test
## Task Description

The following test regularly fails:

https://github.com/google/web-stories-wp/blob/08b68ab3879cf33c1d046f881e2adeb0165d7bce/tests/e2e/specs/editor/publishingFlow.js#L58-L115

```
  ● Publishing Flow › should guide me towards creating a new post to embed my story

    TimeoutError: Text not found "Publishing Flow Test"

      waiting for function failed: timeout 500ms exceeded

  ● Publishing Flow › should guide me towards creating a new post to embed my story

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Failed to load resource: the server responded with a status of 404 (Not Found)"]

      at Object.assertExpectedCalls (../../node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

```

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Relevant Technical Choices

The idea, the reason is tests are failing, is because the amp story player is taking a little time to render as it requires to wait for the JS to load. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6238

### CODE REVIEW

**Comment by swissspidy** [comment]
> The idea, the reason is tests are failing, is because the amp story player is taking a little time to render as it requires to wait for the JS to load.

What JS is being loaded? There's some request interception this test that should avoid loading any JS

**Comment by spacedmonkey** [comment]
> What JS is being loaded? There's some request interception this test that should avoid loading any JS

I don't really know why this is happening. I think these waits are needed, as it just needs a little time to block editor to render the `amp-story-player` tag to render. The 500ms is not enough. The waitforselector, seems like a nice workaround. 

This one is a hard one to test locally, as I can't replicate at all and only seem to happen in CI. I have run test 3 times and this doesn't break anything, I think we should merge and look to see if helps.

**Comment by swissspidy** [comment]
> > What JS is being loaded? There's some request interception this test that should avoid loading any JS
> 
> I don't really know why this is happening. I think these waits are needed, as it just needs a little time to block editor to render the `amp-story-player` tag to render. The 500ms is not enough. The waitforselector, seems like a nice workaround.

Well there should be nothing to render in the first place due to the request interception... 🤔

**Review by swissspidy — APPROVED** [review]
Let's give it a try

**Pull request merged**
