### PR TITLE
E2E Tests: Add e2e tests for publisher logo file upload

### LINKED ISSUE #7224: Settings: Add e2e tests for publisher logo file upload
## Feature Description

Spawned from #7215 - we should have an e2e test on publisher logo upload to prevent regression as we witnessed in 7215 where the query stopped recognizing multiple instances of the same key.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

New e2e test for publisher logo file upload

### PR DESCRIPTION
**Pull request by samwhale**
## Context

Publisher logos suffered a regression. This was [fixed](#7215) but we're adding tests for resiliency.

## Summary

Adds an e2e test for publisher logos.

## Relevant Technical Choices

n/a

## To-do

- [ ] Add a way to clear ALL publisher logos after the test runs

## User-facing changes

n/a

## Testing Instructions

tests should pass

### QA

- [x] This is a non-user-facing change and requires no QA

### Does this PR have a security-related impact?

no

### Does this PR change what data or activity we track or use?

no

### Does this PR have a legal-related impact?

Does it matter what gifs we use?

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7224

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]

**Review by BrittanyIRL — APPROVED** [review]
👏 👏 👏

**Comment by spacedmonkey** [comment]
I really wish you are waited for someone from the infra to review this. I am not sure on some of this, including waiting for a second, making rest api requests and naming. 

I will leave to @swissspidy to follow with his feedback.

**Comment by BrittanyIRL** [comment]
> I really wish you are waited for someone from the infra to review this. I am not sure on some of this, including waiting for a second, making rest api requests and naming.
> 
> I will leave to @swissspidy to follow with his feedback.

hey  @spacedmonkey  - totally fair, thanks for speaking up. @samwhale do you mind reverting this change from main and just leaving the PR open so that it can be reviewed by Pascal when he returns? There's no rush to getting this merged and we should make sure it's 100% in line with other tests by those who are more familiar with the structure.

**Comment by samwhale** [comment]
Sure thing, I'm happy to revert. Please comment on anything on the pr that you'd like changed when I reopen - that way I can see what your best practices are.

**Pull request merged**
