### PR TITLE
Pre-Publish Checklist: Enable Pre-Publish Checklist.

### PR DESCRIPTION
**Pull request by carloskelly13**
## Summary

Removes the feature flag and enables the pre-publish checklist.

## Testing Instructions

1. The strings noted in this document can be used as a guideline to behaviour and expected messages presented to the user - https://docs.google.com/spreadsheets/d/1PjaRp4bueQ3Cv14A7I696m0vjGCIX_kN9tIGh-V-Bkc/edit?pli=1#gid=0
2. Please review all active bugs against this issue first so as to understand where know issues exist - https://github.com/google/web-stories-wp#workspaces/web-stories-5e94d3aced449034e1e9b226/board?labels=bug%20bash%3A%201.2,group%3A%20pre-publish%20panel&notFullScreen=false&repos=235435637&showPRs=false&showClosed=false

---

Fixes #

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Seems to be a valid lint error on this.

**Review by maxyinger — APPROVED** [review]
lgtm!

**Comment by csossi** [comment]
Getting these warnings re: "Image missing description":


...but there is one:

**Comment by csossi** [comment]
Story title error specifies a recommendation of less that 40 characters:
u

But the visible title starts cutting off display at 24 characters - shouldn't it show at least 40?


(guessing this may not really be checklist related, but may require a new ticket re: Title field rather than changing message to "23 characters")

**Comment by dreamofabear** [comment]
Percy diffs look fine, approving.

**Review by dreamofabear — APPROVED** [review]

**Comment by carlos-kelly** [comment]
@choumx We've had a problematic karma test for a while now that attempts to test a modal dialog when you publish a story without a title. It fails often but usually a couple re-runs fix it. I have deleted the test since it was a placeholder dialog anyway that is of less use with the pre-publish checklist. I can add this test back if we want, but for some reason I could not get the modal to show up in karma, but it still works in the app.

**Pull request merged**
