### PR TITLE
Calendar: Pass custom formatters to `react-calendar`

### LINKED ISSUE #11734: I18N: Date picker does not respect language settings
## Bug Description

When setting WordPress to another language, the date picker does not respect the langauge WordPress is set on. 

## Steps to Reproduce

1. Go to settings > general.
1. Set language to Spanish.
1. Go to story editor.
1. Go to document panel.
1. Change date of story.
1. Set translated date picker.

## Screenshots
Screenshot 2022-06-17 at 12 54 36

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Passes custom date formatters to `react-calendar` to ensure dates are properly localized according to the WP

## To-do

Maybe make the `F Y` format filterable (wrap in `__()`)

## User-facing changes

Calendar should be translated

Screenshot 2022-06-20 at 18 41 02

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Change your user locale or site locale in the WordPress settigns or your profile
2. Open the story editor and try to change the publish date

**Known limitation**

When you hover over the weekday, the day is not translated yet.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11734

### CODE REVIEW

**Comment by spacedmonkey** [comment]
What about the AM / PM settings?
Screenshot 2022-06-27 at 11 56 18

**Comment by spacedmonkey** [comment]
When you hover over day legend, you still see the english. 
Screenshot 2022-06-27 at 11 57 17

**Comment by spacedmonkey** [comment]
> The words AM / PM are not translated.

interesting. I wonder what is happening in hindi then. 
Screenshot 2022-06-27 at 12 09 27

**Review by spacedmonkey — APPROVED** [review]
This looks good. But should go through QA.

**Review by timarney — APPROVED** [review]

**Comment by felipebochehin87** [comment]
@spacedmonkey @swissspidy hey guys! When I change to the language to Portuguese or French, on Settings > General, I see some weird week days, such as Game, Life, Home, Sec, What, Who...

**Comment by swissspidy** [comment]
@felipebochehin87 I don't see this:

Screenshot 2022-06-27 at 20 34 32
Screenshot 2022-06-27 at 20 33 57

Did you accidentally translate the site using Google Translate? That would explain this. Try disabling Google Translate or use another browser briefly.

**Comment by felipebochehin87** [comment]
Oh that explains the "Game", "Jeu"... Makes sense. Works for me too. Thanks! Approving this PR.

**Pull request merged**
