### PR TITLE
Code Quality: Remove enablePostLocking feature flag code

### LINKED ISSUE #11128: Code Quality: Remove `enablePostLocking` feature flag code
## Task Description

Now that this has been enabled by default in the last release we can remove the relevant code bits.

### PR DESCRIPTION
**Pull request by timarney**
## Context

Enable post locking is on by default as of #10795

## Summary

Removes feature flags for post locking

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

Instructions via #10795
#### Dialog
1. Login as author,
2. Create a story.
3. Publish story
4. In another browser, login as admin.
5. Edit the same story.
6. See dialog.

#### Dashboard
1. Login as author,
2. Create a story.
3. Publish story
4. In another browser, login as admin.
5. Go to dashboard.
6. See story, with lock icon. 

#### All stories
1. Login as author,
2. Create a story.
3. Publish story
4. In another browser, login as admin.
5. Go to All stories.
6. See story, with lock icon. 

For all test, perform with avatars enabled and disabled. 
To do this. 
1. Login as admin
2. Setting > discussion
3. Disable avatar. 
4. Save 

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11128

### CODE REVIEW

**Comment by timarney** [comment]
@spacedmonkey --- I can dig in but given you worked on this feature ... any thoughts on why this one is failing ?

https://github.com/GoogleForCreators/web-stories-wp/runs/5778341309?check_suite_focus=true

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
@timarney Looks like the `CUJ: Creator can view their stories in grid view Creator should be able to perform basic updates to stories from dashboard should Rename a story` dashboard karma test is now failing

**Comment by timarney** [comment]
Adding a temp snapshot to try to debug the Karma test

**Comment by timarney** [comment]
Looks like `Rename` is `disabled`.

84dcc504a33022ea0cfbbb1f031cc912f3a62ddbc427db0a104cca5343e21ff6

Will troubleshoot more later

**Comment by swissspidy** [comment]
Ah! 💡 

It's disabled because the story is "locked" (see lock icon in front of the title).

That's because the story is marked as locked in the fixture set:

https://github.com/GoogleForCreators/web-stories-wp/blob/378322a54284c3bf41b96b8b636985514b49fccc/packages/dashboard/src/dataUtils/formattedStoriesArray.js#L25-L29

In that case I suppose we can update the Karma tests so that we test "Rename" for both locked and unlocked stories.

One test verifying that "Rename" is disabled for a locked story, one test for verifying that renaming works for an unlocked story.

WDYT?

/cc @BrittanyIRL

**Comment by timarney** [comment]
@BrittanyIRL or @swissspidy 

Can you point me in the right direction for updated the Karma test (I haven't really worked with them yet)

I attempted to add the locked story as the second item in the fixture array

https://github.com/GoogleForCreators/web-stories-wp/pull/11140/files#diff-2ad71a84760fdf66941fac46243d3f9bb0ba09839e6039709a2d0af83693fa9aR50

After that tried to add a tested to ensure that context option is disabled

https://github.com/GoogleForCreators/web-stories-wp/pull/11140/files#diff-b34fffa3e835843ea476d0e161da20311ac20477fa909f1df32a3a45f2fc7092R174

Can revert that if it's totally off track

**Comment by swissspidy** [comment]
@timarney Definitely on the right track!

Two things I noticed:

1. The new story was not the second item because it was the one with the newest date, so actually was the first one.
  I changed the date now to address this.
2. `toBeDisabled()` does not exist
  This is a matcher from jest-dom. Karma uses Jasmine, not Jest, so this does not exist. I swapped this for a `hasAttribute()` check now.

I also pushed a minor change 367325a654172f2fd7915887e96e265cda446c88 to address some prop types warnings I was seeing while testing this.

**Comment by swissspidy** [comment]
Looks like that particular test passes now but others need updating 🙃 I'll take another quick peek.

Also, just filed #11187 for a related change we should make for story locking.

**Comment by timarney** [comment]
> Also, just filed https://github.com/GoogleForCreators/web-stories-wp/issues/11187 for a related change we should make for story locking.

👍

**Comment by swissspidy** [comment]
Yay all Dashboard Karma tests are passing now 🎉

**Pull request merged**
