### PR TITLE
Remove Page Layouts feature flag

### LINKED ISSUE #5988: Page Layouts: Remove Feature Flag
Remove Feature Flag and experiment for page layouts as it is an active feature now.

### PR DESCRIPTION
**Pull request by zachhale**
## Summary

Permanently removes feature flag and experiment for page layouts.

## Relevant Technical Choices

Basic stubs for page layouts fetching to make page not crash are in this PR, but better stubs coming in #5945.

## Testing Instructions

Check that page layouts are still there. 📈 

---

Fixes #5988

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
✨

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
@zachhale Have you seen the test failures? https://github.com/google/web-stories-wp/pull/6016/checks?check_run_id=1751227832#step:8:1633

**Review by BrittanyIRL — APPROVED** [review]

**Comment by zachhale** [comment]
@swissspidy should this go to QA first or is this ok to merge?

**Comment by swissspidy** [comment]
Should be fine to merge I think 👍

**Pull request merged**
