### PR TITLE
Block: Remove minimum width from grid items

### LINKED ISSUE #11960: Blocks: Grid layout setting for 4 columns does not apply
## Bug Description

When I set the number of columns to 4, the grid layout remained at 3 columns. 

## Expected Behaviour

Changing the number of columns to 4 should display the grid layout in 4 columns. 

## Steps to Reproduce

1. Add Web Stories block
2. Select Grid Layout
2. Change number of columns to 4
3. Note the number of columns displayed has not changed from 3 to 4

## Screenshots

https://user-images.githubusercontent.com/66372350/179762339-ba1fcccf-4aff-4b73-9702-be611649cd75.mov

## Additional Context

Used default WP theme Twenty Twenty-Two. Also occurred with Twenty Twenty-One. 
Site: https://testsite.cmsdevrel.com/2022/07/19/test-4-columns-grid-layout/

- Plugin Version: 1.23.0
- WordPress Version: 
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Remove min width of story and let flex box do it's own things. 

## Relevant Technical Choices

Removing min width might mean stories look diffferent or other styling issues. 

## User-facing changes

https://user-images.githubusercontent.com/237508/195661136-02de5505-f30b-4a40-92ea-24306d25de9f.mov

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Add Web Stories block
2. Select Grid Layout
3. Change number of columns to 4
4. Verify you see stories in 4 columns
5. Preview post, see 4 columns there too

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11960

### CODE REVIEW

**Comment by swissspidy** [comment]
Does this affect anything on the frontend?

Could you add QA instructions?

**Comment by spacedmonkey** [comment]
@swissspidy Not adding  QA instructions is by design. Want to get thoughts on the PR first. 

In my limited testing, I can't see any effect. QA might be better than me to look. As I don't write the block, it is hard to know why this min width value was required in the first place. I am also not sure if this what the workaround / fix we would want. It may result in different styling than desired.

**Comment by swissspidy** [comment]
I'll check it out, but instructions are helpful for code reviewers too.

**Comment by spacedmonkey** [comment]
> I'll check it out, but instructions are helpful for code reviewers too.

Not sure what instructions I can give. The video shows the new behaviour. It is more about setting it to 4 columns and testing the responsive.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
