### PR TITLE
Remove hotlinking feature flag

### LINKED ISSUE #10232: Code Quality: remove `enableHotlinking` feature flag code
## Task Description

This feature has been enabled by default since 1.15.0.

Let's remove the `enableHotlinking` code completely now.

### PR DESCRIPTION
**Pull request by miina**
## Summary
Removes the feature flag for hotlinking

## User-facing changes
N/A

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10232

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Seems like the lint error is valid and `renderUploadButton` can be removed.

**Comment by miina** [comment]
> Seems like the lint error is valid and renderUploadButton can be removed.

Oops! Thanks, done.

**Comment by spacedmonkey** [comment]
While testing this, I can no longer see the hotlink button. 

### In main
Screenshot 2022-03-16 at 15 28 37

### In this branch
Screenshot 2022-03-16 at 15 27 37

**Comment by swissspidy** [comment]
Odd 🤔 Don't see how that's possible with the current PR, given that the code for that button has been removed.

Are you testing locally or on the QA site?

Works fine here locally:

Screenshot 2022-03-16 at 16 37 17

**Comment by miina** [comment]
@spacedmonkey Hm, I can't really reproduce it.
[Per Percy snapshots](https://percy.io/google/web-stories-wp/builds/16570112/changed/932190542?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600), it shows two icon buttons as expected.
Also, the Upload button with written out text [was fully removed in this PR](https://github.com/GoogleForCreators/web-stories-wp/pull/10944/files#diff-0f37d63c9ac90f48c0495fe965101310fb160575fca357e7264611315773145bL256), not sure why it's still visible for you 🤔 

Also seeing it correctly locally and in QA. 

Can you double check that while testing locally, your code matches with what's in this PR (e.g. the Upload button with text is fully removed)?

**Comment by spacedmonkey** [comment]
Sorry, I am seeing it working now. I rebuilt, stop docker and saw the old upload button. Weird. Working now.

**Review by spacedmonkey — APPROVED** [review]

**Pull request merged**
