### PR TITLE
Remove all poster fallback logic

### LINKED ISSUE #3671: Remove story poster image fallback
## Feature Description

When users don't add a story cover image (poster image), we use the following image as a fallback:

https://github.com/google/web-stories-wp/blob/7fc1c9af6a1e43c0edc2ec57a45f82eccb1d8d08/assets/images/fallback-poster.jpg

This is basically a last resort to ensure the image meets the poster requirements.

**UPDATE 9/10/2020:** We received feedback that setting a fallback cover image on behalf of the user is not a good idea. We should, for now, NOT add a fallback image at all, and encourage users to set a meaningful cover image **[following the guidelines](https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src))**

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

As the title says, this PR removes all logic related to using a fallback poster image if none is provided by the user.

## Relevant Technical Choices

This makes all stories without a poster image invalid AMP documents.

## Testing Instructions

1. Create a new story
1. Publish story
1. View story on frontend
1. See that story is invalid AMP because of a missing poster image.

---

Fixes #3671

### CODE REVIEW

**Comment by spacedmonkey** [comment]
What about these references
https://github.com/google/web-stories-wp/blob/111d3ab39f394b33966b5f548f047dc6e6c7630b/assets/src/dashboard/app/serializers/storyPreview.js#L26
https://github.com/google/web-stories-wp/blob/ecae0a26c52f8641a48673975a39b5b557a8e958/assets/src/dashboard/app/api/useStoryApi.js#L234
https://github.com/google/web-stories-wp/blob/73f248d2f92fa2dce0920d44b57a3b885974794a/assets/src/dashboard/app/views/storyAnimTool/index.js#L245

**Comment by spacedmonkey** [comment]
There are also references to `fallback-poster.png`
https://github.com/google/web-stories-wp/blob/a62e1bc98f0ef0d7c20046b7298263f2e8a1b5b9/tests/phpunit/data/story_post_content.html#L112

And lots of references in `formattedStoriesArray.js`
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L121
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L123
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L411
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L413
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L847
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L849
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L1340
https://github.com/google/web-stories-wp/blob/8eea1900b7d405d4f50960df6f25a17b2858e532/assets/src/dashboard/dataUtils/formattedStoriesArray.js#L1342

**Comment by spacedmonkey** [comment]
Should a generated story have an empty poster attribute?

``` 
<amp-story standalone="" publisher="Web Stories Dev" publisher-logo-src="http://localhost:8899/wp-content/plugins/web-stories/assets/images/fallback-wordpress-publisher-logo.png" title="Test" poster-portrait-src="">
```

**Comment by swissspidy** [comment]
> What about these references

Removed

> There are also references to `fallback-poster.png`

Changed. Exact URLs in test fixures don't matter much though.

>  Should a generated story have an empty poster attribute?

To the AMP validator it doesn't matter whether it's missing or empty.

**Review by spacedmonkey — APPROVED** [review]
Looks good to me!

**Comment by spacedmonkey** [comment]
Tests seem to be failing. Worth checking.

**Comment by spacedmonkey** [comment]
@googlebot I consent.

**Comment by swissspidy** [comment]
One thing I found:

When there is a story without a poster image, the `amp-story` element obviously won't have a `poster-portrait-src` attribute (or simply an empty one). This causes AMP invalidation. So far, so clear.

Now, when using the AMP plugin, the AMP plugin completely removes the `amp-story` element because it is invalid. This will be very confusing.

@westonruter How could I prevent this element from being removed? Removing the `amp` attribute on `<html>` tag? Turning on dev mode? Disabling AMP using some filter when there is no poster image?

**Comment by westonruter** [comment]
This is closely related to https://github.com/ampproject/amp-wp/issues/3393.

Indeed, sanitization of stories is pretty draconian.

As opposed to forcing dev mode, how about registering a sanitizer specific for stories? It can then make sure that these attributes  are supplied so that the final sanitizer doesn't remove it. 

The AMP plugin had such a sanitizer in the past which should probably be resurrected to prevent the poster image issue and the aforementioned issue from occurring: https://github.com/ampproject/amp-wp/blob/1.4/includes/sanitizers/class-amp-story-sanitizer.php

The sanitizer can be conditionally included when serving a `web-story` post type:

https://github.com/ampproject/amp-wp/blob/756d24dc61aa5fb513e554ea6c64c6cdb34ccc2e/includes/class-amp-story-post-type.php#L327-L341

**Comment by swissspidy** [comment]
@westonruter I was indeed looking into adding back this sanitizer.

>  It can then make sure that these attributes are supplied so that the final sanitizer doesn't remove it.

Is there a way to prevent removal without adding the attributes? Our plan was to basically not supply `poster-portrait-src` if we don't have a good poster. But it seems like I _need_ to provide _some_ value. Leaving it empty doesn't work, the validator will complain.

**Comment by westonruter** [comment]
I've worked out what I think will be the best solution for now: https://github.com/google/web-stories-wp/pull/4521

This depends on a corresponding update to the AMP plugin which we can include in 2.0.2: https://github.com/ampproject/amp-wp/pull/5388

**Pull request merged**
