### PR TITLE
Block: Use `getUsers` with capability query

### LINKED ISSUE #9240: Block: `getAuthors()` deprecation notice
## Feature Description

When using the story picker in the web stories gutenberg block, the following noticed is displayed. 

```
react_devtools_backend.js:4049 select( 'core' ).getAuthors() is deprecated since version 5.9. Please use select( 'core' ).getUsers({ who: 'authors' }) instead. 
    at SelectStories 
```

See screenshot for full details. 
Screenshot 2021-10-04 at 16 45 49

This change happened upstream here https://github.com/WordPress/gutenberg/pull/33725

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Replace `getAuthors` with `getUsers`. 

Followed this example - https://github.com/WordPress/gutenberg/pull/33695

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a post. 
2. Insert a web story block. 
3. Select "selected stories". 
4. Select a template. 
5. Click select stories. 
6. Click author dropdown. See that dropdown still works.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9240

### CODE REVIEW

**Comment by swissspidy** [comment]
So IIUC this replaces the deprecated `getAuthors` function with `getUsers()`, which in itself makes sense.

But in WP 5.9 `who: 'authors'` was also replaced by using `capabilities: 'edit_web-stories'`, so ideally we use that as well.

Because then we can get rid of the workaround in `\Google\Web_Stories\REST_API\Stories_Users_Controller::filter_user_query()`


So something like

```js
  const { authors } = useSelect(
    (select) => {
      const { getUsers, getPostType } = select(coreStore);

      const capabilities = getPostType('web-story')?.capabilities['edit_posts'];

      const query = {
        search: authorKeyword,
        capabilities,
      };
      return {
        authors: getUsers(query),
      };
    },
    [authorKeyword]
  );
```

Uses optional chaining for the `getPostType()` call because it first returns `undefined` when the data is not available yet.

Because of that, probably actually better to do this:

```js
  const { authors } = useSelect(
    (select) => {
      const { getUsers, getPostType } = select(coreStore);

      const capabilities = getPostType('web-story')?.capabilities['edit_posts'];

      const query = {
        search: authorKeyword,
        capabilities,
      };
      return {
        // Only load users when capability has been fetched already.
        authors: capabilities ? getUsers(query) : [],
      };
    },
    [authorKeyword]
  );
```

**Comment by spacedmonkey** [comment]
@swissspidy Your fix seems to work. 

Should I remove this `\Google\Web_Stories\REST_API\Stories_Users_Controller::filter_user_query()` then?

**Comment by swissspidy** [comment]
Yes

**Comment by spacedmonkey** [comment]
> Yes

Done

**Review by swissspidy — APPROVED** [review]
Just needs QA instructions for regression testing

**Comment by kkalarickal** [comment]
ReCreated this issue on stories-QA using `main branch`

Confirmed the fix via `12615 branch` - there is no longer a message in the console related to getAuthors().

QA Note: When the author drop down is pressed, the cover image seems to hide the authors list

@swissspidy @spacedmonkey - is it within scope of this ticket to ensure that the select-story :: drop down of the authors list should be visible ?

**Comment by swissspidy** [comment]
No, not at all. Styling fixes are in progress at #12649

**Pull request merged**
