### PR TITLE
Local Media Panel: Loading State Component Swap

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

We're reusing the loading bar that was done for local media uploads in the new checklist card thumbnails (#7976 ), figure we should update this to that shared component to avoid redundancy. 

## Summary

Swap out loading bar in mediaElement to use the new version of it in the design system. 
Add an aria status alert. 

## Relevant Technical Choices

Added the missing `CanvasProvider` to the media element stories so that they work again. 

## User-facing changes

Shouldn't see any changes! There should be the same loading bar on local uploads that are dragged into the media panel. 

## Testing Instructions

Drag uploads into the media panel, you might have to throttle your network to slow it down for the bar to have time to be needed. 
loading bar in media panel

You can also test storybook locally now too! edit-story/components/mediaElement/  - just swap the `"local": false` to be true. 
image local loading

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

See #7976

### CODE REVIEW

**Review by miina — APPROVED** [review]
Thanks for this, LGTM!

**Review by samwhale — APPROVED** [review]
🔥

**Comment by BrittanyIRL** [comment]
@csossi this is just clean up from something we're doing with the prepublish checklist - swapping out the blue loading bar that is used in the local media panel when you drag a new media file to upload for the shared version. It just needs regression testing that the loading bar works the same way in this branch as it does in staging for the local media panel.

**Comment by csossi** [comment]
Verified in QA

**Pull request merged**
