### PR TITLE
Fix Background Overlay on flipped background videos

### LINKED ISSUE #1028: Overlay not working for flipped background media
## Bug Description

When background video is flipped, overlay is not applied.

## Expected Behaviour

The overlay should be applied independent of flipping.

## Steps to Reproduce
1. Add a video and set it as background
2. Try applying Overlay
3. See nothing happening.

## Screenshots

flipped-overlay

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by obetomuniz**
## Summary

This PR fix overlay while flipping videos.

## Relevant Technical Choices

While overlaying videos, 3d context should be present to sync the z-index contexts while using transform/z-index. `transform-style: preserve-3d` even works on this case, but I preferred to use `scale3d` since it already has built-in support to `preserve-3d`.

---

Solving #1028

### CODE REVIEW

**Review by miina — CHANGES_REQUESTED** [review]
Let's add a test as well, otherwise looks good.

**Comment by barklund** [comment]
I'm not completely sure how the proposed solution solves the actual issue. Is the problem, that the overlay is z-wise "flipped" to lie below the element? If so, why the eff does that happen?

**Comment by miina** [comment]
>  Is the problem, that the overlay is z-wise "flipped" to lie below the element? If so, why the eff does that happen?

Thought it would be due to `transform` creating its own stacking context. I might be wrong though, @obetomuniz to confirm?

Note: Looking at the order of the elements now then this doesn't seem to be relevant here.

**Comment by obetomuniz** [comment]
@miina Correct. Since we are using `transform`, we are dealing with 2 stacking contexts (Safari does not deal very well with this). The normal `z-index` and the `transform` context. Using the 3d style on transform ensures that we sync both in the same context. More about the z-index/transform stacking context aspects can be read [here](https://www.freecodecamp.org/news/4-reasons-your-z-index-isnt-working-and-how-to-fix-it-coder-coder-6bc05f103e6c#3-setting-some-css-properties-like-opacity-or-transform-will-put-the-element-in-a-new-stacking-context-) and [here](https://css-tricks.com/things-watch-working-css-3d/).

**Review by miina — APPROVED** [review]
LGTM

**Pull request merged**
