### PR TITLE
Move processing and processed from media context state to a ref scoped to uploadVideoPoster

### LINKED ISSUE #2070: Move processing and processed from media context state to a MediaProvider ref
Move processing and processed from media context state to a ref scoped to uploadVideoPoster.

This is a simple cleanup that was recommended by Dima in #1729 and prevents unnecessary re-renders.

### PR DESCRIPTION
**Pull request by cvolzke4**
## Summary

Move processing and processed from media context state to a ref scoped to uploadVideoPoster.

This is a simple cleanup that was recommended by Dima in https://github.com/google/web-stories-wp/pull/1729 and prevents unnecessary re-renders.

Fixes #2070

### CODE REVIEW

**Review by spacedmonkey — APPROVED** [review]
Looks good. 

One question, would this effect our ability to do this - https://github.com/google/web-stories-wp/issues/969 ?

**Comment by cvolzke4** [comment]
> Looks good.
> 
> One question, would this effect our ability to do this - #969 ?

That may be a case for keeping the 'processing' list in global state.
Dima, WDYT?

**Comment by dvoytenko** [comment]
> > Looks good.
> > One question, would this effect our ability to do this - #969 ?
> 
> That may be a case for keeping the 'processing' list in global state.
> Dima, WDYT?

I think upload, backfill, etc - all should be in global state. Even a set of recently uploaded and local resources can be in the global state. I just don't like the idea of list/search nuances to be in the global state. The way I think about it is this: for instance if I were doing a native app for something like this, I'd probably have a smaller local database of resources, e.g. if they were just recently created or used a lot or recently modified, or used, etc. But I'd not necessary try to put there all resources that a user searches or lists through.

**Comment by cvolzke4** [comment]
> > > Looks good.
> > > One question, would this effect our ability to do this - #969 ?
> > 
> > 
> > That may be a case for keeping the 'processing' list in global state.
> > Dima, WDYT?
> 
> I think upload, backfill, etc - all should be in global state. Even a set of recently uploaded and local resources can be in the global state. I just don't like the idea of list/search nuances to be in the global state. The way I think about it is this: for instance if I were doing a native app for something like this, I'd probably have a smaller local database of resources, e.g. if they were just recently created or used a lot or recently modified, or used, etc. But I'd not necessary try to put there all resources that a user searches or lists through.

This PR addresses your suggestion in https://github.com/google/web-stories-wp/pull/1729: "What's the value of processed and processing being in the reducer state? These vars are both naturally look like refs to me."

Jonny has raised a case for keeping these (or a similar thing) in global state. I can think of 2 ways forward:
1. Keep these in refs as per this PR, and as a part of https://github.com/google/web-stories-wp/issues/969 add 'processing' to global state (with a better name, 'processing' is kind of meaningless).
2. Revert this PR, and leave processing / processed as global state. Note that with selectors, these don't necessarily re-render components when they change.

How should we proceed?

**Comment by spacedmonkey** [comment]
> Keep these in refs as per this PR, and as a part of #969 add 'processing' to global state (with a better name, 'processing' is kind of meaningless).
Revert this PR, and leave processing / processed as global state. Note that with selectors, these don't necessarily re-render components when they change.

IMO, in 2 is the better option becuase of #969. But I am not strongly for it if someone can think of a better reason to remove it.

**Comment by dvoytenko** [comment]
@cvolzke4 @spacedmonkey I see. Some notion of state would have to remain then. But it's a bit wasteful though to do so much refresh when only targeted refresh is needed instead. However, @cvolzke4 at this point it's a balance of all other performance improvements you're adding. And upload is relative rare and slow by nature. So, I'm ok if you leave it as is for now. But mostly it's up to you. Eventually, perhaps, our selector contexts can grow into taking care of such problems.

**Comment by cvolzke4** [comment]
Discarding, as the 'processing' var is useful in global state for https://github.com/google/web-stories-wp/issues/969.

**Pull request closed without merging**
