### PR TITLE
`ServiceBasedPlugin`: Don't resolve service IDs as callables

### LINKED ISSUE #9292: `ServiceBasedPlugin` tries to resolve service ID as callable
## Bug Description

Our services have IDs like `svg`.

In `ServiceBasedPlugin` not only the class names are tried to resolve as callables, but also the IDs.

So if a function like `svg` actually exists as a callable, there's gonna be an error because it tries to actually call that function.

## Expected Behaviour

Service IDs should not be used as callables.

## Steps to Reproduce

1. Try to install [Call Now Button](https://wordpress.org/plugins/call-now-button/) plugin, which declares a global `svg` function
2. See error

## Additional Context

- Plugin Version: 1.12.0
- WordPress Version: 5.8
- Operating System: macOS
- Browser: Chrome

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

If the service ID is the same as a public function in the global namespace, `ServiceBasedPlugin` tried to call it.

## Summary

Don't resolve service IDs as callables.

## Relevant Technical Choices

--

## To-do

--

## User-facing changes

None

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Activate Web Stories plugin
2. Activate [Call Now Button](https://wordpress.org/plugins/call-now-button/) plugin
3. Don't see error

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9292

### CODE REVIEW

**Comment by swissspidy** [comment]
FYI @schlessera @westonruter since the AMP plugin contains the same code.

**Comment by schlessera** [comment]
Another approach would be to fix the `maybe_resolve()` method to not accept function strings.

Suggestion based on the experiment here: https://3v4l.org/e1ja6#v8.1rc3:
```php
	protected function maybe_resolve( $value ) {
		if ( is_callable( $value ) && ! ( is_string( $value ) && function_exists( $value ) ) {
			$value = $value( $this->injector, $this->service_container );
		}

		return $value;
	}
```

This would ensure this resolution cannot break in other places where it is being used either.

**Comment by swissspidy** [comment]
I suppose both could work for extra hardening?

**Comment by schlessera** [comment]
Yes, but not resolving the IDs means you can never have dynamically computed IDs, of course.

**Comment by spacedmonkey** [comment]
@swissspidy Can you provide more details on this PR. I can not sure I understand the issue here.

**Comment by swissspidy** [comment]
@spacedmonkey it's explained in the ticket description #9292

Our services have IDs like `svg`.

In `ServiceBasedPlugin` not only the class names are tried to resolve as callables, but also the IDs.

So if a function like `svg` actually exists as a callable, there's gonna be an error because it tries to actually call that function.

**Review by spacedmonkey — APPROVED** [review]

**Pull request merged**
