### PR TITLE
Templates: Update Some Images to Shapes

### LINKED ISSUE #5873: Replace rogue images with shapes in templates/page layouts
## Feature Description

There are a few image assets in templates/page layouts that should be shapes. These are just overlooked images that have had no negative impact to usability - now with page layouts and removing the bulk of the image assets, we have realized these should be updated to be shapes to create continuity. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

Images that should be shapes: 
(round 1)
- DIY socials 
- Travel socials 
- Entertainment stars 

(round 2, added on review) 
- Arrow on trends 
- Music note on entertainment 

(round 3) 
- trends: hearts on "i woke up like this" 
- fashion: arrow on the handbag page that is next to "learn more" 
- wellness: arrow on left of learn more of yoga page

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
This PR just goes through some templates that were using images for icons we can use shapes for and updates those images to shapes.

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
social icons in DIY & travel and star icons in Entertainment should now all be shapes instead of images

## Testing Instructions
Go to explore templates
-> Create from template for DIY
-> Go to the page with the social icons and see that you can change their color
-> Verify that there aren't any regressions in the template (just quick scroll through all pages and see that no images are missing or anything glaring like that. Should be fine tho)

Repeat these steps for the social icons in the travel template and the star Icons in the entertainment template.

---

Partially addresses #5873

### CODE REVIEW

**Comment by swissspidy** [comment]
@littlemilkstudio Could you perhaps assemble a list of images that have been removed? Need to drop them from our CDN as well :-)

**Comment by zachhale** [comment]
The social icons and rating stars look good. Are there any more to check for? Some missing still:

The arrow here:
image

The new music music note circle here:
image

**Comment by maxyinger** [comment]
@swissspidy 
> @littlemilkstudio Could you perhaps assemble a list of images that have been removed? Need to drop them from our CDN as well :-)

Yea absolutely!
https://replaceme.com/images/templates/diy/diy_icon_fb.png
https://replaceme.com/images/templates/diy/diy_icon_insta.png
https://replaceme.com/images/templates/diy/diy_icon_yt.png
https://replaceme.com/images/templates/diy/diy_icon_tw.png
https://replaceme.com/images/templates/entertainment/ent_icon_white_star.png
https://replaceme.com/images/templates/travel/travel_icon_fb.png
https://replaceme.com/images/templates/travel/travel_icon_insta.png
https://replaceme.com/images/templates/travel/travel_icon_yt.png
https://replaceme.com/images/templates/travel/travel_icon_tw.png

**Comment by maxyinger** [comment]
> The social icons and rating stars look good. Are there any more to check for? Some missing still:

Awesome. These ones might take a sec cus I'd have to generate the icon and add it to our hidden shapes. We could always do these in a separate PR too. Shouldn't be a blocker for adding placeholder image for layouts tho

**Comment by BrittanyIRL** [comment]
> > The social icons and rating stars look good. Are there any more to check for? Some missing still:
> 
> Awesome. These ones might take a sec cus I'd have to generate the icon and add it to our hidden shapes. We could always do these in a separate PR too. Shouldn't be a blocker for adding placeholder image for layouts tho

Ah, I knew I would miss some when I made this. Let's do those as a separate PR but part of the same ticket for sprint tracking.

**Review by BrittanyIRL — APPROVED** [review]
Looks great! Thanks for jumping on this.  

(there's some conflicts, but i'm sure you know that :) )

**Comment by zachhale** [comment]
More missing:
* Hearts in bottom page here 
image
* Arrow next to learn more 
image
* End of arrows on sleep series 
image 
image

**Comment by BrittanyIRL** [comment]
> More missing:

@zachhale thanks! I added these to the ticket tracking updates #5873 - we'll just do these updates in batches since they aren't doing any harm by grouping them in different PRs to not block what we have.

**Comment by swissspidy** [comment]
> @swissspidy
> 
> > @littlemilkstudio Could you perhaps assemble a list of images that have been removed? Need to drop them from our CDN as well :-)
> 
> Yea absolutely!
> [replaceme.com/images/templates/diy/diy_icon_fb.png](https://replaceme.com/images/templates/diy/diy_icon_fb.png)
> [replaceme.com/images/templates/diy/diy_icon_insta.png](https://replaceme.com/images/templates/diy/diy_icon_insta.png)
> [replaceme.com/images/templates/diy/diy_icon_yt.png](https://replaceme.com/images/templates/diy/diy_icon_yt.png)
> [replaceme.com/images/templates/diy/diy_icon_tw.png](https://replaceme.com/images/templates/diy/diy_icon_tw.png)
> [replaceme.com/images/templates/entertainment/ent_icon_white_star.png](https://replaceme.com/images/templates/entertainment/ent_icon_white_star.png)
> [replaceme.com/images/templates/travel/travel_icon_fb.png](https://replaceme.com/images/templates/travel/travel_icon_fb.png)
> [replaceme.com/images/templates/travel/travel_icon_insta.png](https://replaceme.com/images/templates/travel/travel_icon_insta.png)
> [replaceme.com/images/templates/travel/travel_icon_yt.png](https://replaceme.com/images/templates/travel/travel_icon_yt.png)
> [replaceme.com/images/templates/travel/travel_icon_tw.png](https://replaceme.com/images/templates/travel/travel_icon_tw.png)

Thanks! Opened #5931 to remove them

**Comment by maxyinger** [comment]
Should now have all the images @zachhale  pointed out as shapes. Just did it in this PR cus it hasn't gone through QA yet so figured I'd just tack it on and make QA a little easier. 

@swissspidy Here are the additional removed images:
https://replaceme.com/images/templates/beauty/beauty_page_4_heart.png
https://replaceme.com/images/templates/entertainment/ent_icon_wraparound.png
https://replaceme.com/images/templates/entertainment/ent_icon_musicnote.png
https://replaceme.com/images/templates/fashion/fashion_page2_arrow.png
https://replaceme.com/images/templates/fashion/fashion_page5_arrow.png
https://replaceme.com/images/templates/wellbeing/wellbeing_icon_arrow_head_light.png
https://replaceme.com/images/templates/wellbeing/wellbeing_icon_arrow_head_dark.png

**Comment by swissspidy** [comment]
@littlemilkstudio Sweet thanks!

I see that the Wellbeing template also has some Facebook and Twitter icons. Could they also be replaced or is that not possible? Just curious if they were missed.

**Review by BrittanyIRL — APPROVED** [review]
LGTM!

**Comment by maxyinger** [comment]
@swissspidy Yea I can absolutely replace them. I'm not seeing them in the template tho. If you could point me to which page they're on I'd be happy to add them to this PR

**Comment by zachhale** [comment]
I just merged #5917 so you should be able to browse page layouts to see what's missing now

**Comment by swissspidy** [comment]
> @swissspidy Yea I can absolutely replace them. I'm not seeing them in the template tho. If you could point me to which page they're on I'd be happy to add them to this PR

@littlemilkstudio No idea where they are, but I see that we host them currently. So apparently safe to delete.

See list of images here:

https://github.com/google/web-stories-wp/tree/ac68604af8be07207e41fbebfed886e3641f26ec/public/static/main/images/templates/wellbeing

**Comment by maxyinger** [comment]
@swissspidy Must be from a former design iteration and we got rid of them. should be safe to delete then

**Pull request merged**
