### PR TITLE
Dashboard: Update dialogs to use new one from design system

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Summary
Updates dialogs that occur in dashboard to use new structure from design system. These are: Delete story dialog, preview story, delete publisher logo

## Relevant Technical Choices

- Swap existing dialog/modal and button/text elements used in dashboard for those in the design system
- Gut the dialog and modal components in dashboard
- Moved the titleFormatted function found in cardTitle and the story list to utils so i can use it in the delete story dialog without duplicating it (again). 
- Adds the background color used by story preview amp output as a theme value so that the backgrounds match in the dialog version of preview.

## User-facing changes

- Dialogs in dashboard have been updated to implement new designs. 

## Testing Instructions

In the dashboard see the following: 

1. On "My stories": Click "Delete story" from the story menu in both grid and list view. See that dialog is visually updated (old on left).
Screen Shot 2020-11-09 at 11 48 48 AM

2. On "My stories": Click "Preview story" when hovering over a story (center action). See that dialog is visually updated (this one is a little unique since it's basically a glorified story preview that would open in a new tab as a modal instead. The biggest change here is the close icon is swapped for the new set. I didn't want to have to come back for it, made more sense to swap out at once). 
Screen Shot 2020-11-09 at 11 50 18 AM

3. On "Editor settings": click the pencil on a publisher logo (must have more than 1 logo uploaded) and then click "delete". See that the dialog is visually updated. 
Screen Shot 2020-11-09 at 11 51 13 AM

4. If a story has no title and you click the 'delete story' action, you'll get the matching "no title" title that displays in the grid or list view as the replacement title. 
Screen Shot 2020-11-09 at 11 52 31 AM

5. You can check story preview dialog views in storybook (dashboard/views/previewStory) to see loading and error states 
preview states

---

Addresses #4968

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
Looks great!

**Comment by carlos-kelly** [comment]
Screen Shot 2020-11-17 at 10 50 43 AM

It looks like we are missing the border radii on the buttons

**Comment by BrittanyIRL** [comment]
Converting to draft while button focus is sorted out

**Review by spacedmonkey — APPROVED** [review]
SGTM

**Review by embarks — APPROVED** [review]

**Comment by BrittanyIRL** [comment]
Waiting to merge this until Sam has had time to review the new dialog in storybook

**Pull request merged**
