### PR TITLE
Adjust Action buttons + add Publish/Schedule button

### LINKED ISSUE #521: Save
This is a followup from #221 to make it specific to save only. (no autosave)

As an author I want to be able to save my progress so I don't lose my work. 

[Feature Brief - Epic: Document Workflow](https://docs.google.com/document/d/1GJZljicdXcP7oRdywsF3EGUaCVpCHsDrK2gUMubnrbk/edit?pli=1#heading=h.omxvhkxr4hgd)

**Acceptance Criteria**
1. Saving & updating works similar to regular posts in WordPress, with some special casing (see below)
3. If a story is unpublished, save by triggering the Save button
5. If a story is published, Save by triggering the Update button
6. After the author navigates away(e.g. refresh) from the page without saving, a notification is shown. 

Note:  Save/update does not save the undo/redo stack. Undo/redo is tied to the current client state.

### PR DESCRIPTION
**Pull request by miina**
Fixes #521

### CODE REVIEW

**Comment by miina** [comment]
@spacedmonkey Mind checking if the button switching & amount of buttons seems about right in comparison with regular WP posts?

**Comment by spacedmonkey** [comment]
@miina One thing I noticed is that, if a story is published and you change published date to the future, the button doesnt change to the scheduled. Only thing I noticed so far, otherwise we are looking good.

**Comment by miina** [comment]
> One thing I noticed is that, if a story is published and you change published date to the future, the button doesnt change to the scheduled. 

@spacedmonkey It seems to be the same in WP default posts so I purposefully didn't look into that.
E.g. publish a post -> set the date, it'll still stay "Update" and after updating will change to "Schedule". (As far as I tested at least.)

Wanted to keep the logic similar for now. Thoughts?

**Comment by spacedmonkey** [comment]
> Wanted to keep the logic similar for now. Thoughts?

Keep it the same. Worry about it later if it is a problem.

**Review by spacedmonkey — APPROVED** [review]
👍

**Pull request merged**
