### PR TITLE
Performance: Reduce bundle sizes

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

The dashboard bundle in particular is quite big, which has been bugging me for quite some time now. It's also difficult to analyze and optimize because it so heavily depends on the editor bundle. And of course the editor bundle to some degree also depends on the dashboard. **Yikes!**

And webpack's tree shaking only works to a certain degree as well. Time to do some digging!

I took some time today to analyze the dashboard bundle using tools like [Statoscope](https://statoscope.tech/) and tried to find and eliminate causes for the big bundle size.

First off, I looked at things that were included twice—once from the design system, and once from the editor. This allowed me to move quite a few things from the editor to  the design system and delete duplicate code.

Next, I tried to spot things that clearly didn't not make sense to be in the bundle. First candidate: the `big.js` module. This is only used in one small React component used in the editor design panel. So why was this included..?

I realized that since components are often times living next to the context providers imported by the dashboard, it all got included at once. So I tried to separate those as good as possible, until `big.js` was finally not included anymore.

This way, I could also prevent the text set chunks from being included from the dashboard bundle.

All in all, some great wins simply thanks to some refactoring!

## Relevant Technical Choices

See individual commits for details

## User-facing changes

N/A

## Testing Instructions

Everything should still run as expected, with tests passing.

---

Related:

#868 
#4853

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Did you think about using code splitting? Maybe move a shared dependencies like the date package into an file.

**Comment by swissspidy** [comment]
> Did you think about using code splitting? Maybe move a shared dependencies like the date package into an file.

One step at a time :-)

This PR focuses on improving imports and the possibility to do tree shaking.

Better dependency management will naturally come up with work on design system and move to npm workspaces (#4853).

**Review by BrittanyIRL — APPROVED** [review]
Love seeing the deleted code here! Thanks for tackling this. 

One minor thing that's more of a discussion point - you added `gridview` to the design-system/components, to me this feels like something that should be nested in /keyboard as it is just functionality. As someone who has had to poke around to find the various keyboard utils it would make sense on this re-organization to place them somewhere central? 

It wouldn't impact the imports throughout the code, just the initial export. 

Thoughts?

**Review by spacedmonkey — APPROVED** [review]
For what is worth, this looks good to me 👍

**Pull request merged**
