### PR TITLE
Templates: Fitness Base Animations

### LINKED ISSUE #2208: Animations: Add animations to FITNESS template to match designs
The animation process for a template is as follows:
- Applying animations in the animation editor `/story-anim-tool`
- Alter its static layout if needed to accommodate the animation
- If template requires a new animation part that doesn't already exist
  - Create ticket for missing animation part
  - Add animation part to code base
  - Go back to template and apply newly created animation part
  - Continue with template animations

Reference the figma designs:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=1%3A8

And reference the movie clips from this folder:
https://drive.google.com/drive/folders/1E0nLATcplhGNzgteOymx3s2SyA-cc7_M

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Base animations for fitness template using our current primitives.

## Relevant Technical Choices
NA

## To-do
https://docs.google.com/spreadsheets/d/1iJ8Adqs4zGWteMoxVCZ2MM4LAza0LQmtPUX6I9qdshY/edit#gid=21496487

## User-facing changes
None

## Testing Instructions
set `enableAnimation` flag in `includes/Dashboard.php` to `true` & hover over the fitness template in the templates page.

## Screenshots
(exported at small size and frame rate so not so big. view in app for higher fidelity)
Kapture 2020-07-09 at 12 38 41

---

Fixes #2208

### CODE REVIEW

**Comment by pbakaus** [comment]
Looks great in the gif!

**Comment by carloskelly13** [comment]
This looks great and runs smooth, the only thing I see is a tad jittering on this circle animation. Perhaps it needs a new svg. Unsure.

Screen Shot 2020-07-09 at 2 56 47 PM

**Comment by maxyinger** [comment]
@carlos-kelly 

> This looks great and runs smooth, the only thing I see is a tad jittering on this circle animation. Perhaps it needs a new svg. Unsure.
> 
> Screen Shot 2020-07-09 at 2 56 47 PM

Yup also saw this in the fashion template on the links page. I think there's a small edge case bug on animation parts that use scale, `BOUNCE` & `ZOOM`, and it's noticeable when the stacked dots are animating in.

Here's an issue I created for it:
https://app.zenhub.com/workspaces/web-stories-5e94d3aced449034e1e9b226/issues/google/web-stories-wp/3115

**Review by BrittanyIRL — APPROVED** [review]
animations work as you specify! very cool

**Review by mariano-formidable — APPROVED** [review]
Fantastic!  I applied the template to a new story using "Use Template" and then played each page's animation in our story-anim-tool, and they look great! 🎉

**Comment by mariano-formidable** [comment]
@littlemilkstudio I believe this PR is ready to merge 😎

**Comment by mariano-formidable** [comment]
@googlebot I consent.

**Pull request merged**
