### PR TITLE
Dashboard: hide admin notices

### LINKED ISSUE #6330: Dashboard: admin notices not hidden
## Bug Description

If a WP core update is present, a message shows on all pages in the admin. However, the dashboard title covers this. See screenshot. 

## Expected Behaviour

Admin notices should be hidden on the dashboard

## Screenshots

title

## Additional Context

- Plugin Version: 1.4.0
- WordPress Version: 5.6
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Hide all notices on dashboard. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6330

### CODE REVIEW

**Comment by swissspidy** [comment]
The editor doesn't have any `.notice` selector to specifically hide notices there, yet it works. So why is this needed here?

I'd want as much parity between the too stylesheets as possible.

**Comment by spacedmonkey** [comment]
> The editor doesn't have any .notice selector to specifically hide notices there, yet it works. So why is this needed here?

Here is css for the editor 
```
#screen-meta,
#screen-meta-links,
#screen-meta-links ~ :not(.web-stories-wp):not(.clear) {
  display: none;
}
```

The reason this work, is `.notice` is a sibling of `#screen-meta-links`. 

However in the dashboard have a `screen-meta-links` div. 

Screenshot 2021-03-04 at 18 16 21

To make it work generic to work for both

```
#screen-meta,
#screen-meta-links,
#screen-meta ~ :not(.web-stories-wp):not(.clear)
#screen-meta-links ~ :not(.web-stories-wp):not(.clear) {
  display: none;
}
```

Or I just added notice to hidden. It can't be generic as the markup is different.

**Review by BrittanyIRL — APPROVED** [review]

**Comment by swissspidy** [comment]
> > The editor doesn't have any .notice selector to specifically hide notices there, yet it works. So why is this needed here?
> 
> Here is css for the editor
> 
> ```
> #screen-meta,
> #screen-meta-links,
> #screen-meta-links ~ :not(.web-stories-wp):not(.clear) {
>   display: none;
> }
> ```
> 
> The reason this work, is `.notice` is a sibling of `#screen-meta-links`.
> 
> However in the dashboard have a `screen-meta-links` div.
> 
> Screenshot 2021-03-04 at 18 16 21
> 
> To make it work generic to work for both
> 
> ```
> #screen-meta,
> #screen-meta-links,
> #screen-meta ~ :not(.web-stories-wp):not(.clear)
> #screen-meta-links ~ :not(.web-stories-wp):not(.clear) {
>   display: none;
> }
> ```
> 
> Or I just added notice to hidden. It can't be generic as the markup is different.

Thanks for the insight!

Given that the current solution [also hides the no-js notice](https://percy.io/google/web-stories-wp-e2e/builds/9176401/changed/519517194?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600), let's try

```css
#screen-meta,
#screen-meta-links,
#screen-meta ~ :not(.web-stories-wp):not(.clear)
#screen-meta-links ~ :not(.web-stories-wp):not(.clear) {
  display: none;
}
```

as you suggested

**Review by swissspidy — CHANGES_REQUESTED** [review]
Percy regression [here](https://percy.io/google/web-stories-wp-e2e/builds/9176401/changed/519517194?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600)

**Comment by spacedmonkey** [comment]
Here is a cleaner solution I think. https://github.com/google/web-stories-wp/pull/6614/commits/4f0a5aebe257051a7ab3d80a746421647845b3bd

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
