### PR TITLE
Template Updates: Fitness

### LINKED ISSUE #6974: Template Updates: Fitness
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 | Headline should change to Pulse; remove animation on logo and background image.   | N/A |
| 2 | Quote should update to Fly In since move is custom; remove animation on blocked images in background. **By line to fly in** | N/A |
| 3 |  change 'Run' to pulse animations; like you mean it and other text should be fly in; remove animation on image.  |  N/A  |
| 4 |  Update '5' to pulse; remove animation on image; text updated to fly in instead of move.   | N/A |
| 5 | Headline and text update to fly in; '3' updated to pulse; remove background image animation on shoe.  **Buy Now Button to Fade in at 3000ms** | N/A |
| 6 | Headline, watch, and text area should all fly in instead of move; remove background animation. | N/A |
| 7 | Headline should update to fly in; little circles should change to pulse; background animation removed.  | Combine circle shapes; increase radius of tappable shape.  |
| 8 | Headline should fly in instead of move; **Blocks to whoosh 2000ms**  | N/A |

See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- No more custom animations

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Part of 1.7 release is updating existing templates to avoid custom animations and unnecessary prepublish checklist suggestions.

## Summary

Fitness Template revisions 
- Remove custom animations and replace with effects available in editor 
- Add CTA as sticker on page 7

## Relevant Technical Choices

Used my own judgement for which direction animations should come from. 

## To-do

- [x] Design Review

## User-facing changes

See figma for revised template: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7357%3A546501
List of changes can be found here: #6974 

**Before**
https://user-images.githubusercontent.com/10720454/114282115-d46f4a80-99f6-11eb-8952-91e41bac6356.mp4

**After**
https://user-images.githubusercontent.com/10720454/114281378-e8b14880-99f2-11eb-943d-a0dec4a90162.mp4

## Testing Instructions

- use template from dashboard / explore templates (fitness template) and see that there are no more custom animations on any elements and that the little circle on page 7 is a sticker. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6974

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]

**Review by samwhale — COMMENTED** [review]
Also amazing, a few things, lmk if I'm wrong:

1. I think the background animations are supposed to be removed on these pages:

||||
|--|--|--|
|||page-4|
|page-5|page-6|page-7|



2. These animations should be fly in

|||
|--|--|
|image|image|
|image|image|
|image|image|
|image|image|
|image|image|
|image||
|image||


3. Should this be a different image?

|Designs|Current|
|--|--|
|image|image|

**Comment by samwhale** [comment]
I can't delete my previous review lmao so I'm going to update here:

> Also amazing, a few things, lmk if I'm wrong:
> 
> 1. I think the background animations are supposed to be removed on these pages:
> 
> 2. These animations should be fly in

I was on the wrong branch, all of this looks good 🤦 

> 3. Should this be a different image?

Just wondering about this one!

**Review by samwhale — APPROVED** [review]
DISREGARD MY GIFS

**Comment by BrittanyIRL** [comment]
> DISREGARD MY GIFS

Thanks for noticing the watch asset! Updated here: https://github.com/google/web-stories-wp/pull/7191 it'll replace once that's merged.

**Comment by ivayloklissarov** [comment]
I had a look at it, all good! Nothing to change for this template.

**Review by embarks — APPROVED** [review]
perfecto ✨

**Pull request merged**
