### PR TITLE
Added the pageTemplate to the libraryLayout

### LINKED ISSUE #10698: Keyboard focus doesn't shift focus correctly for Empty State contextual menu
## Bug Description

Originally reported by @BrittanyIRL 

Keyboard focus doesn’t shift to the selected pane when I click on Browse Page Templates but it does for other panes. 

Additionally @spacedmonkey found that "if I select page template once. Change tab and then why to go to page template again, nothing happens" and @BrookeGraham found that "similar with moving away from images tab and then selecting Choose Image or Video from right click menu" 
image10

@merapi flagged that these are all likely the same issue.

## Steps to Reproduce

1. Open a new Story
2. right click within the canvas of the first page to trigger the "Empty State" contextual menu
3. Select "Browse Page Templates" and note that focus isn't changed as expected.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by mwritter**
## Context

Add focus to the selected pane when 'Browse Page Templates' is selected.

## Summary

Adds the page template reference information to the library layout to determine which element should get focus. 

## Relevant Technical Choices

`libraryLayout.js` only uses `MEDIA, MEDIA3P, TEXT` reference information currently, we need to also use the `PAGE_TEMPLATES` reference information to properly update the tab reference and add focus.

## User-facing changes

Before/After:
https://user-images.githubusercontent.com/14057928/165990000-37949091-764f-4c02-8de9-c68bbf4fffcd.mp4

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Go to Dashboard
2. Create a new Story
3. Right click the 'Canvas'
4. Click 'Browse Page Templates'
- Notice design panel changes to the 'Page Templates' tab

On Staging:
- Notice the 'Page Templates' tab is 'highlighted' (blue bar under tab) but the arrow keys and TAB keys do nothing

On Branch:
- Notice the 'Page Templates' tab is 'highlighted' (blue bar under tab) and the design panel / tab is now in focus so the arrow keys and TAB keys now navigate in the design panel 

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #10698

### CODE REVIEW

**Review by sblinde — APPROVED** [review]
🐝 
Simple fix, quick win! Very nice!

**Review by barklund — COMMENTED** [review]
@merapi, this probably overlaps with some of the work you did. Can you confirm this looks good?

**Comment by sblinde** [comment]
@merapi  Do you have an opportunity to check this out? Want to ensure it looks good with your work as well per @barklund's comment. Thanks!

**Review by maxyinger — APPROVED** [review]

**Comment by merapi** [comment]
> @merapi Do you have an opportunity to check this out? Want to ensure it looks good with your work as well per @barklund's comment. Thanks!

Sorry, I missed it. All good here 👍🏻

**Pull request merged**
