### PR TITLE
Layer grouping

### LINKED ISSUE #9244: Layer grouping
Discussed and requested by design in conjunction with #8983 but isolated to make sure details are attended to accordingly. 

https://www.figma.com/file/dc9xrVlRhQq4KTE9WQzU1R/_Editor-Sprint-Feature-Level-Designs_?node-id=9935%3A421370

## Acceptance Criteria

- [ ] Group should be moved as one element.
- [ ] Group should be aligned as one element.
- [ ] You can enter the group by double-clicking.
- [ ] Grouping/Ungrouping should be possible from the Canvas RCM and Layers Panel context menu.
- [ ] Visual representation of the group in the Layers Panel.
- [ ] You can collapse/expand the group in the Layers Panel.
- [ ] TBD: Nested groups.
- [ ] TBD: Locking the whole group.
- [ ] TBD: Locked element inside group vs group selection bounding box.

## Other notes 

Grouping layers is going to impact keyboard users because right now the layers panel is hidden for keyboards as all functionality is mirrored in keyboard shortcuts. The accessibility of the layers panel will need to be reconsidered ahead of this functionality getting added to the layers panel.

### PR DESCRIPTION
**Pull request by merapi**
## Summary

This PR gives you the option to group layers which enables you to (main goals of layer grouping):
- select and move multiple elements at once
- align a group of elements as one element (instead of aligning each of them individually)

## To-do

- [ ] Tests (will change in the future so there is little point to do them now?)
- [ ] In V2:
- [ ] Agree on/implement default group naming: "Group 1 Copy" style or "Group 2" (best effort to increment the number)

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9244

### CODE REVIEW

**Review by barklund — COMMENTED** [review]
So far this seems to work really well. It doesn't do a whole lot yet, but it's a great start!

**Review by barklund — DISMISSED** [review]
Let's get this merged so we can start planning next steps!

**Comment by spacedmonkey** [comment]
There is something weird happening with this PR.

**Comment by merapi** [comment]
> 

Indeed, at one point I reverted the main branch merge because of this missing class issue (composer install), now it's up to date with the main branch, but changes are incorrectly detected by GH? Should be only from this PR.

**Comment by merapi** [comment]
PR/tests fixed, needs re-approval.

**Review by barklund — APPROVED** [review]

**Pull request merged**
