### PR TITLE
Code quality: Refactor media reducer to reduce complexity

### LINKED ISSUE #9646: Code quality: Refactor media reducer to reduce complexity
## Feature Description

The  media reducer currently [has a complexity of 30](https://github.com/google/web-stories-wp/blob/ed06c490cd86bb2d46f69ccecbdfe4006deb084b/packages/story-editor/src/app/media/local/reducer.js#L17). This is very high, we should refactor this logic to reduce this complexity.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Refactor code in reducer so the logic it's in their own functions, in own files. 

Stop circular dependencies by breaking state in a constant file.   

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9646

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]
LGTM

We should have some tests for these reducers

**Comment by spacedmonkey** [comment]
> We should have some tests for these reducers

Should I add unit tests in this PR? I looked at it, but other reducers do not have tests. Wasn't sure it was needed here?

**Comment by swissspidy** [comment]
If you've got some time, sure.

It's just a general wish though. Something that could also be done in a new PR.

We do have test coverage for reducers in other providers, e.g. story provider or the media upload queue hook.

No reason why we shouldn't have test coverage here as well.

**Comment by spacedmonkey** [comment]
I am going to merge this for now and add tests in another PR.

**Pull request merged**
