### PR TITLE
Video optimization: Change ffmpeg config to 720p@24fps

### LINKED ISSUE #7333: Video optimization: Use Storytime recs (720p @ 24fps)
## Feature Description

Current Storytime recommendation for videos is 720p @ 24fps.

## Alternatives Considered

We could keep status quo (1080p @ original framerate) and rely on Google video CDN to reduce bandwidth costs on origin, but the end result will be users consuming 720p for the most part anyways (plus more expensive cache misses). Might reduce marginally compression artifacts however.

## Additional Context

N/A

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by dreamofabear**
## Context

#7333 

## Summary

Changes ffmpeg config from 1080p@original to 720p@24fps to match Storytime rec.

Tested this locally with a 4K@60fps video shot on iPhone XS.

## To-do

N/A

## User-facing changes

N/A

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a video with a large resolution and/or high frame rate and drag it onto the editor
2. Once video optimization completes, preview the story
3. Download the optimized video and compare it to the original video (binary size, resolution, and frame rate)
4. The optimized video should have a max resolution of 720x1280 and a max frame rate of 24fps, and generally a much smaller file size

### UAT

- [x] UAT should use the same steps as above.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7333

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@choumx Just out interest, there documentation on amp spec on what video quality should be? I believe this has been mentioned a couple of times, but I have never seen the official guide lines.

**Comment by spacedmonkey** [comment]
In my testing, this seems to make the transcoding processes slower for longer videos. Did you notice this in your testing @choumx ?

**Comment by dreamofabear** [comment]
> Just out interest, there documentation on amp spec on what video quality should be?

There's some guidance here: https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/#video

> In my testing, this seems to make the transcoding processes slower for longer videos.

Tried this on a 100MB 4K@60fps video and I've noticed the opposite. Transcoding to 1080p without frame rate change takes about twice as long (8m vs. 4m) and results in double the file size.

**Review by swissspidy — APPROVED** [review]

**Comment by spacedmonkey** [comment]
Currently testing.

**Review by spacedmonkey — APPROVED** [review]
I tested this. Seems like one of the videos I tested at the start, it didn't like it slower but all others it was a little faster. Must be a weird things with ffmpeg.

**Pull request merged**
