### PR TITLE
Add back 'auto-draft' status

### PR DESCRIPTION
**Pull request by miina**
## Context
See https://github.com/GoogleForCreators/web-stories-wp/pull/12129#discussion_r948792595

## Summary
This PR removes rewriting `auto-draft` to `draft` when loading the story and updates the status checks where necessary.

## Testing Instructions
1. Create a new story
2. Add some title, modify content, add some pages, etc. but **do not save**
3. Wait a minute or so for autosave to kick in
4. Go back to the "All Stories" page and ignore the warning about unsaved content
5. You should not see your story in the list (**<- this is new**)
6. Open the editor again
7. You should see a message about the version in your browser being newer than what you have, and that you can restore that version
8. Restore the backup and you should see the content again that you've added in step (2)

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
This is a user-facing QA-able change in the following way:

1. Create a new story
2. Add some title, modify content, add some pages, etc. but **do not save**
3. Wait a minute or so for autosave to kick in
4. Go back to the "All Stories" page and ignore the warning about unsaved content
5. You should not see your story in the list (**<- this is new**)
6. Open the editor again
7. You should see a message about the version in your browser being newer than what you have, and that you can restore that version
8. Restore the backup and you should see the content again that you've added in step (2)

However, in my testing step (8) did not work. I did see the local autosave message, but when I clicked on "Restore backup", nothing happened (even though there definitely is data in sessionStorage). Is this a known issue? I would have expected this to restore my content.

**Comment by miina** [comment]
> However, in my testing step (8) did not work. I did see the local autosave message, but when I clicked on "Restore backup", nothing happened (even though there definitely is data in sessionStorage). Is this a known issue? I would have expected this to restore my content.

Hm, it did work before this PR. Unless the DB `autosave` ran meanwhile and saved the story? But then it shouldn't display the message 🤔 
I'll check tomorrow, thanks for the testing notes!

**Review by barklund — APPROVED** [review]
Seems to work correctly.

**Review by swissspidy — APPROVED** [review]
It works! 🎉 🎉

**Comment by felipebochehin87** [comment]
1. Autosaved story is not listed
2. Message is displayed
3. Restored backup is displayed

**Pull request merged**
