### PR TITLE
Fix entering edit mode via click for Safari

### LINKED ISSUE #7745: Safari: Text edit mode selection not possible
## Bug Description
It looks like the text edit mode in Safari has broken meanwhile. Selecting part of the text doesn't seem to be possible, the cursor does not show up at all. 
Additionally, in display mode, the cursor is also different compared to other browsers (`text` in Safari vs `default` in others)

## Expected Behaviour
The user should be able to select part of the text in edit mode and style it.

## Steps to Reproduce
1. Open the editor in Safari
2. Add text
3. Try to select part of the text and mark it bold.

## Screenshots
sfari

## Additional Context

- Browser: Safari Version 14.0 (14610.1.28.1.10) (will test with the latest version shortly, too)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Entering edit mode for Safari was using `Document.caretRangeFromPoint()` that seems to be deprecated (according to the `lib.dom.d.ts` file my IDE is using) or at least not recommended for use in production due to potential issues. It is currently failing to work correctly in our editor and causing unexpected behaviour.

This PR stops using this method and enters the edit mode by setting the cursor to index `0` for Safari (and any browser that does not support `caretPositionFromPoint`).

## To-do

- [x] Investigate if there's an alternative for setting the cursor where the user clicked. -> @merapi found an alternative

## Testing Instructions
In Safari:
- Add a Text.
- Enter edit mode
- Verify you can select part of the text and mark it bold (or italic, etc.)

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. See the instructions above.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7745

### CODE REVIEW

**Comment by merapi** [comment]
> This PR stops using this method and enters the edit mode by setting the cursor to index `0` for Safari (and any browser that does not support `caretPositionFromPoint`).

`caretPositionFromPoint` is supported only in Firefox, which means other browsers will not be able to place the cursor at the desired location (on edit start) - isn't that a little downgrade for Chrome users?
image

For me, we should still use `caretRangeFromPoint` to support Chrome (Brainstorm's IDE is using word deprecated, but for me, it's more like _"This feature is non-standard and should not be used without careful consideration."_ - we thought it out).
image

I tinkered with it a bit and was able to get the cursor in the right place on Safari with something like double setEditingElementWithState invocation (first is changing the HTML, so the second run can read the cursor text properly). Will give more info on that.

**Review by merapi — COMMENTED** [review]
_Testing the ZH review status update._

**Comment by merapi** [comment]
I was able to get it working by changing the user-select (nobody [docs] told us about it ;)), please check https://github.com/google/web-stories-wp/tree/try/safari-text-edit-click

Didn't check the consequences of that change.

**Comment by miina** [comment]
@merapi I've updated this PR to keep `caretRangeFromPoint` in and set the offset to `0` only if the found `offset` is obviously incorrect.

If removing `user-select` as in your PR doesn't cause issues, and we can fix the incorrect cursor issue in it, too, then I think that we might still want to keep both changes from this PR as well.

**Comment by miina** [comment]
35bfdda -> Props @merapi

**Review by merapi — APPROVED** [review]

**Pull request merged**
