### PR TITLE
Add WordPress.org assets to repository

### PR DESCRIPTION
**Pull request by swissspidy**
* Plugin Icon (#4119)
* Plugin Banner (#4118)

From here we'll copy them to plugins.svn.wordpress.org upon release.

### CODE REVIEW

**Comment by spacedmonkey** [comment]
banner-1544x500-rtl.png has english text in it. What is the point of this banner?

**Comment by spacedmonkey** [comment]
Yoast seems to be a good [example](https://github.com/Yoast/wordpress-seo/tree/trunk/svn-assets) or [bbpress](https://plugins.trac.wordpress.org/browser/bbpress/assets?order=name). 

If so we are missing the following files 
- icon-256x256.png
- icon-128x128.png
- banner-772x250.png
- banner-772x250-rtl.png

**Comment by swissspidy** [comment]
@spacedmonkey English text is not a problem. The whole point of the RTL variant is to be flipped. Exactly like Yoast's banner are flipped too. We're not doing localized banners at the moment. Citing the recommendations:

> Design your banner such that the title can be in either position. As this may not work with all designs, you should create a different image for RTL pages with -rtl in the name.

If you have any feedback about the design of the banner, please provide it to Sam in #4118. This PR is just adding the pre-designed banners.

**Comment by swissspidy** [comment]
> If so we are missing the following files
> 
> icon-256x256.png
> icon-128x128.png

We don't need PNGs because we use an SVG icon.

> banner-772x250.png
> banner-772x250-rtl.png

I don't think we'll need the smaller versions as long as we have the large one. But I'll check again.

**Comment by spacedmonkey** [comment]
This [How Your Plugin Assets Work](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/) documentation.

>  If you chose to use SVGs, you must also use a PNG icon as a fallback, otherwise your plugin icon will not display properly in older browsers or on Facebook.

As for the banner, you need one size of normal screens and a double sized image for retina screens. That is why there is two banner sizes. 

> You cannot use the retina image alone, it only works as an “add-on” to the 772×250 image. The larger ‘retina’ image is only used on displays that can show the higher detail.

Another good [example](https://github.com/xwp/wp-foo-bar/tree/develop/wp-assets) is XWP's foo-bar plugin.

**Comment by swissspidy** [comment]
Well then, thanks for the pointer! I'll update the images accordingly.

**Comment by swissspidy** [comment]
Added the missing sizes now

**Review by spacedmonkey — APPROVED** [review]
👍

**Pull request merged**
