### PR TITLE
Fix shifted Moveable in RTL mode with scrollbar

### LINKED ISSUE #7638: RTL: Frame and display layer not in sync when zoomed
## Bug Description
The selection frame and the displayed element are not in sync. This can be seen especially well when setting the zoom level to 200%, however, some styling oddities can be noticed in the default zoom level, too.

Edit:
Additionally, horizontal scrolling while in Zoom only moves the frame layer but not the display layer.

## Expected Behaviour
The display and frame layer should be in sync and look as expected in RTL mode.

## Steps to Reproduce
1. Set the mode to RTL
2. Add an element, select it
3. Set the zoom level to 200%
4. See the display and frame difference
5. Resize the window so that horizontal scrollbar would appear, too.
6. Scroll horizontally -- see the frame moving but not the display.

## Screenshots
Out of sync frame / display
Screenshot 2021-05-20 at 17 10 24

zoom

Incorrect selection styling (a bit shifted):
Screenshot 2021-05-21 at 12 21 17

## Additional Context
From Morten:
> Looks like the padding for the lack of scrollbar is added to the wrong side of the container in the display layer - the display layer does not have a scrollbar, but most still reserve the space to align the elmeents correctly with the frames layer.

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Considers the scrollbar when in RTL mode and the user has zoomed in enough for the vertical scrollbar to be visible.

## User-facing changes
|Before|After|
|------|-----|
| Screenshot 2021-06-17 at 12 56 20 | Screenshot 2021-06-17 at 12 55 03 |

## Testing Instructions
1. Switch to RTL mode
2. Add any element
3. Zoom to 200% (or enough for the vertical scrollbar to appear)
4. Select the element
5. Verify that the selection box matches the element borders and is not out of sync with it.

### QA
See above.
## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7638

### CODE REVIEW

**Review by merapi — COMMENTED** [review]
Chrome looks good, but can you check Safari? Looks like this for me (is ok on main):
image

**Comment by merapi** [comment]
I've noticed some RTL+zoom oddities, can you also see all of them?

https://user-images.githubusercontent.com/21036224/122475022-59ad4780-cfc4-11eb-9687-a8c9c53a614f.mov

**Comment by miina** [comment]
> I've noticed some RTL+zoom oddities, can you also see all of them?

Hm, didn't see it before but yes, now I can see that the horizontal scrolling doesn't seem to be working.

And yes, looks like it was working as expected before in Safari and now is not. It's also not working as expected in Firefox anymore so looks like this fix should be for Chrome only.

I'll move this back to the backlog and expand the scope to generally fixing the issues with Zoom.

**Comment by swissspidy** [comment]
@miina is this one still relevant?

**Comment by miina** [comment]
I think we can close, thanks for checking.

**Pull request closed without merging**
