### PR TITLE
Pre-Publish Checklist: Remove page icon

### LINKED ISSUE #5652: Weird ghost rectangle in Checklist > Recommendation
## Bug Description

Originally reported by @kkalarickal and also by @bmattb , @spacedmonkey , @swissspidy 

Within the Checklist > Recommendation section, in front of each Page reference, there is a weird rectangle. Perhaps it is some indicator of severity or a link to the page or something. But it's confusing.

## Expected Behaviour

Said rectangle should be removed or its inclusion be made clear to the user.

## Steps to Reproduce

Create a web story which is imperfect ;)
Checklist recommendation will have the page reference and the said rectangle

## Screenshots

image1

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by samwhale**
## Summary

Remove the rectangle svg from the checklist in the editor.

## Relevant Technical Choices

none

## To-do

none

## User-facing changes

Removes the rectangle that preceded the page title

## Testing Instructions

1. run the editor
2. make an incomplete page
3. open the checklist
4. scroll to the bottom to see the suggested page fixes. There should be no rectangle

|Before|After|
|--|--|
|image|image|

---

Fixes #5652

### CODE REVIEW

**Comment by swissspidy** [comment]
is there now a good reason to have this indentation?

**Comment by BrittanyIRL** [comment]
> is there now a good reason to have this indentation?

There's not - and it aligns better with the designs that way. @samwhale do you mind adding that? I know it wasn't in the ticket.

**Comment by samwhale** [comment]
Can do @BrittanyIRL!

**Comment by samwhale** [comment]
@BrittanyIRL @swissspidy The page indicator now has 16px of left margin: 

<image src="https://user-images.githubusercontent.com/22185279/104513284-a2dc1400-55ac-11eb-8469-28f3db7a1ffe.png" width="400" />

This shows a clearer separation between the document and page checklist items

**Review by BrittanyIRL — APPROVED** [review]
Looks great! Thanks for also fixing the left white space. This will be great to get in to our next release.

**Comment by swissspidy** [comment]
> > is there now a good reason to have this indentation?
> 
> There's not - and it aligns better with the designs that way. @samwhale do you mind adding that? I know it wasn't in the ticket.

I actually meant the other way around, removing the left margin everywhere.

Now there's more whitespace everywhere :-) But I suppose it's fine if the icon is supposed to make a comeback soon.

**Comment by spacedmonkey** [comment]
YES!

**Comment by BrittanyIRL** [comment]
> > > is there now a good reason to have this indentation?
> > 
> > 
> > There's not - and it aligns better with the designs that way. @samwhale do you mind adding that? I know it wasn't in the ticket.
> 
> I actually meant the other way around, removing the left margin everywhere.
> 
> Now there's more whitespace everywhere :-) But I suppose it's fine if the icon is supposed to make a comeback soon.

There's supposed to be a new icon in v2. Let's leave this as is, everything's lined up. If we want to change the padding of the whole pre publish panel we can make a new ticket.

**Review by embarks — APPROVED** [review]
ya killin it samwhale!

**Pull request merged**
