### PR TITLE
Dashboard: Applied design updates to DIY template

### LINKED ISSUE #2470: Templates: Update DIY template to 9:16
Use this Figma doc to apply 9:16 updates to the existing `DIY` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR applies the new design updates to the DIY template.

## User-facing changes

Layout and text sizes have been update on the DIY template based off the recommendations found in this [figma design doc](https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61).

## Testing Instructions

1.) Go to "Explore Templates".
2.) Hover over the DIY template and click on "View".
3.) Take a look at each template page in the detail view for DIY.  Make sure images are showing up and the layout appears as shown in the figma updates.

---

Fixes #2470

### CODE REVIEW

**Review by carloskelly13 — APPROVED** [review]
This loads and looks good

**Review by maxyinger — APPROVED** [review]
lgtm!

**Review by dmmulroy — APPROVED** [review]
Works as described 👍

**Review by BrittanyIRL — APPROVED** [review]
👍 🎉

**Pull request merged**
