### PR TITLE
Bug Fix: Move floating menu in front of popups so that functionality is fixed

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Miina pointed out here: https://github.com/GoogleForCreators/web-stories-wp/pull/10861#discussion_r824902184 and here https://github.com/GoogleForCreators/web-stories-wp/pull/10875#issuecomment-1065285614 that fixing the layering visually actually makes features completely unusable. 
 
## Summary

move popups behind floating menu so that things can be edited.

## To-do

Getting the layering right here is going to be a much bigger lift than fixing the z index, we need to restructure the HTML. Ticket created here: #10892 but for now, the floating menus are just going to need to be on top. 

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Review by miina — APPROVED** [review]
Thanks for the temp fix!

Maybe let's enable this test here, too, it should be working now with the floating menu being available in text edit mode: https://github.com/GoogleForCreators/web-stories-wp/pull/10861/files#diff-8b48e6a473c1a371bc199f0cdd4fb91e2b49420347116552ec193a5ee1c6ccedR102

**Review by samwhale — APPROVED** [review]
💭 the temp fix works, so in the future do you think that opening those menus should de-select the elements?

**Comment by BrittanyIRL** [comment]
> Thanks for the temp fix!
> 
> Maybe let's enable this test here, too, it should be working now with the floating menu being available in text edit mode: https://github.com/GoogleForCreators/web-stories-wp/pull/10861/files#diff-8b48e6a473c1a371bc199f0cdd4fb91e2b49420347116552ec193a5ee1c6ccedR102

sure, just wanted to get this fix up for you in case it was blocking you before I got in for the day.

**Comment by BrittanyIRL** [comment]
> 💭 the temp fix works, so in the future do you think that opening those menus should de-select the elements?

Whatever the real fix is it needs to keep the element selected so that the popups work. I was honestly caught off guard by the side effects of fixing the z index to be isolated. Where I'm at without digging deeper is that we either need to rework the entire "layer" that holds alllllll of these things so that they have independence or maybe the popups can get a higher z index? That to me feels like just pushing the root problem further along. 

All to say, I am unsure right now but fixing this will be easier now that the entire floating menu is in. 

I'm hoping this can be a really short term fix, but at least now the tests and functionality are all intact.

**Pull request merged**
