### PR TITLE
Editor: Text Library: Update presets to have default of none for bg mode

### LINKED ISSUE #6097: Default font preset should not be defaulted with hilite bg styling
## Bug Description

Default text presets are added to the page with bg hilite style. They should not contain any bg styles at all.

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by maxyinger**
## Context
We previously updated the text presets to include a bg mode as well as set other defaults. We've recently gotten a request to update the presets to have a bg mode of none, this PR does that and updates the hidden padding defaults associated with it too

## Summary
Update text presets to have bg mode of none

## Relevant Technical Choices
NA

## To-do
NA

## User-facing changes
Text presets should now not have any bg highlight or fill when initially selected

## Testing Instructions
-> Go to Editor
-> Add all text presets to a page & see that they don't have any bg on them & when you add a bg too them they appear nice and don't cause the text to wrap at all.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Follow testing instructions above

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6097

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
Nice, no wrapping unless I click `Highlight`
<image src="https://user-images.githubusercontent.com/22185279/107274890-44208380-6a0e-11eb-9746-46ba45c89e55.png" width="250px" />

**Review by BrittanyIRL — APPROVED** [review]
Thanks for updating this. It looks like there's a karma test that will need to be updated here. 

just to confirm, we should expect text to not wrap when "fill" is used but if "highlight"
Screen Shot 2021-02-08 at 1 17 24 PM
 is then it should wrap, like this screenshot:

**Comment by maxyinger** [comment]
Eh it probably shouldn't wrap with either fill or highlight. thanks for catching. will make the widths a little larger so it doesn't wrap on highlight

**Comment by BrittanyIRL** [comment]
> Eh it probably shouldn't wrap with either fill or highlight. thanks for catching. will make the widths a little larger so it doesn't wrap on highlight

just pulled the latest, no wrapping text! ✅

**Comment by swissspidy** [comment]
@littlemilkstudio the test failure seems legit: https://github.com/google/web-stories-wp/pull/6253/checks?check_run_id=1874124053#step:8:3602

does it pass locally?

**Comment by maxyinger** [comment]
@swissspidy ahh yeaup I remember having to fix this last time the defaults changed height (cus of the hidden padding on bg fill). I'll fix it

**Pull request merged**
