### PR TITLE
Media: Better prepend uploading items to library

### LINKED ISSUE #9964: Media: Filtering media does not work with uploading assets
## Bug Description

If you filter the media library by image, videos that are uploading still displayed. 

## Steps to Reproduce

1. Open editor
2. Upload video. 
3. Filter by image. 

## Screenshots

https://user-images.githubusercontent.com/237508/145632762-da883e22-021b-4a44-b000-92c85523ef74.mov

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Changes the way in-progress (uploading) items are displayed in the media library to ensure they're never lost when e.g. filtering the library afterwards.

## User-facing changes

Uploading items are still being displayed, even when changing filters in the library:

https://user-images.githubusercontent.com/841956/185426575-ef16adb3-7aff-49ae-a9b3-8932b9e10b69.mov

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Upload media to the media library
2. See uploading items in the library
3. Filter media library by type
4. Still see uploading items in the library
5. Verify the uploaded items remain in library after upload finishes

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #9964

### CODE REVIEW

**Comment by timarney** [comment]
This PR seems to works as described however noticing some odd behavior --- when filtering.

Sometimes seems to double or triple (duplicated) results

https://www.youtube.com/watch?v=ysXRQlGF1a0

**Comment by swissspidy** [comment]
OK I think I have fixed it now:

https://user-images.githubusercontent.com/841956/185426575-ef16adb3-7aff-49ae-a9b3-8932b9e10b69.mov

As you can see I was able to keep the nice benefit of keeping existing items in there when filtering by type. Improves UX a little.

**Comment by timarney** [comment]
Nice ya --- re-tested and working as fully working as expected now.

**Review by timarney — APPROVED** [review]

**Comment by swissspidy** [comment]
Hmm weird, I'll try to reproduce again with these steps.

Thanks for testing!

> while the other images are still loading, it shows only that one uploading image, I wonder if we could wait until we have the images request response and only then display all the images? Maybe it's not that important though :)

That's a good point. It's definitely confusing. I like this suggestion.

**Comment by swissspidy** [comment]
@miina I implemented your suggestion with hiding the uploading items, but I was not able to get items to show up twice. Still happening for you?

**Comment by miina** [comment]
> @miina I implemented your suggestion with hiding the uploading items, but I was not able to get items to show up twice. Still happening for you?

Unfortunately yes, seeing this error, too:
Screenshot 2022-08-25 at 16 47 55

Maybe it depends on the image size, perhaps if you try with throttling? The image has to be still uploading when switching the filter back to "Image" for it to happen.

**Comment by swissspidy** [comment]
Strange. I tried with large and small images as well as network and CPU throttling without luck.

Still added some safeguards now, just in case.

Don't see how this would still happen with those in place.

**Review by miina — APPROVED** [review]
Seems to work now without duplicates!

**Pull request merged**
