### PR TITLE
Set default bg mode and color for new texts

### LINKED ISSUE #673: Opacity Default on Text Box Colouring
## Bug Description

The opacity is defaulted to 0% for the text box colouring. This means when you select a colour you don't see any changes right away as you might expect to and think that the feature is broken. You actually have to change the opacity from 0% AND select a colour to see any change. Having the default set at 0% makes this harder to use and figure out. 

image

## Screenshots

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by barklund**
Fixes #673 by adding default bg mode and color to new text fields.

Note that this is a PR towards #684, which hasn't been merged yet, as it uses features introduced in the PR.

### CODE REVIEW

**Comment by miina** [comment]
I wonder if instead (or perhaps additionally?), it would make sense to modify `showColorPickerAt` so that if `color` is `null` then a default color is assigned. Thoughts?

**Comment by barklund** [comment]
> I wonder if instead (or perhaps additionally?), it would make sense to modify `showColorPickerAt` so that if `color` is `null` then a default color is assigned. Thoughts?

Then simply opening the color picker will change the color from transparent to something else. That might be a bit weird. And the color input would still show `null`. I'd rather we make sure to default the right items in the right places.

**Comment by miina** [comment]
> Then simply opening the color picker will change the color from transparent to something else.

Hmm, curious why would it change with opening, doesn't it change only `onChange`?

Just tested it out and when I open the color picker without doing anything else, it doesn't seem to change the value of the input.

The thought was to have a default non-transparent value in the color picker which shouldn't do anything unless the user changes the value.

**Comment by barklund** [comment]
> > Then simply opening the color picker will change the color from transparent to something else.
> 
> Hmm, curious why would it change with opening, doesn't it change only `onChange`?
>
> Just tested it out and when I open the color picker without doing anything else, it doesn't seem to change the value of the input.

It might work like that actually.
 
> The thought was to have a default non-transparent value in the color picker which shouldn't do anything unless the user changes the value.

I think this PR covers the main case of a non-initialized color default'ing to transparent.

The only other case I can think of is multi-selection of different colored items. How that should be handled is best left in a ticket dealing specifically with that IMO rather than universally picking a random color that they should default to.

**Comment by miina** [comment]
> The only other case I can think of is multi-selection of different colored items. How that should be handled is best left in a ticket dealing specifically with that IMO rather than universally picking a random color that they should default to.

Having a default color in the color picker wouldn't prevent having a default color on each field as well! It would just ensure that if the default color is missing, it wouldn't feel broken.

Feel free to ignore this if you think otherwise :)

**Comment by miina** [comment]
> The only other case I can think of is multi-selection of different colored items.

We could combine all the colors into one for multi-selection 😂

I misread your previous comment and realized just now that it was for multi-selection only, sorry! Yes, agreed that for multi-selection, picking a default color is for discussing separately.

**Review by dvoytenko — APPROVED** [review]

**Comment by barklund** [comment]
Awaiting #684 to be merged, then this will be rebased and merged.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
