### PR TITLE
Code Quality: Use `noop` in more places

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Use noop utils in more places. 

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by miina** [comment]
There are also a bunch of `() => undefined` in the code that can be replaced.

**Comment by miina** [comment]
Search in the `story-editor` package shows still some places with `() => {}`, e.g. in `useDeleteColor` and `useReordering` and a few more.

**Comment by spacedmonkey** [comment]
> Search in the `story-editor` package shows still some places with `() => {}`, e.g. in `useDeleteColor` and `useReordering` and a few more.

Done

**Review by miina — APPROVED** [review]
Needs rebase now, otherwise LGTM

**Pull request merged**
