### PR TITLE
Removed button titles where irrelevant (which is everywhere)

### LINKED ISSUE #12252: Floating toolbar menu item uses non-standard tooltip
## Bug Description

the More button on the floating toolbar has a non-standard tooltip presentation that is different than all others:

image10

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by barklund**
## Context

Removed button titles from floating menu buttons (both text and icon buttons) and one other instance (lock toggle in style panel).

I watched `document.querySelectorAll("button[title]")` while navigating around the app, and didn't find anything else, so I think we're good.

## User-facing changes

| Before | After |
|-|-|
| Screen Shot 2022-12-21 at 09 56 38 | Screen Shot 2022-12-21 at 09 48 48 |
| Screen Shot 2022-12-21 at 09 48 16 | Screen Shot 2022-12-21 at 09 48 35 |

## Testing Instructions

This PR can be tested by following these steps:

1. Long-hover any button in the editor (most importantly in the design menu)
2. Observe that the browser-native tooltip does not show up

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12252

### CODE REVIEW

**Review by miina — APPROVED** [review]

**Comment by swissspidy** [comment]
There are a lot of failing Karma tests because they use `getAttribute('title')`

**Comment by kkalarickal** [comment]
Recreated the problem on `main_branch`



Verified the fix in `12870_branch`



@swissspidy @barklund - I clicked around all over the editor but could not find a duplication of the button tiles where I looked.

**Comment by swissspidy** [comment]
@kkalarickal Thanks for testing!

@barklund Looks like there are some more tests in need of an update. Examples:

https://github.com/GoogleForCreators/web-stories-wp/actions/runs/3799283389/jobs/6461663491#step:9:104

https://github.com/GoogleForCreators/web-stories-wp/actions/runs/3799283389/jobs/6461663825#step:9:106

https://github.com/GoogleForCreators/web-stories-wp/actions/runs/3799283389/jobs/6461663937#step:9:105

https://github.com/GoogleForCreators/web-stories-wp/actions/runs/3799283389/jobs/6461664162#step:9:91

**Comment by barklund** [comment]
> @barklund Looks like there are some more tests in need of an update.

Yeah, I noticed. I'm just deep in the design-system conversion currently, so will only be dealing with this one once I get that one shipped for review.

**Pull request merged**
