### PR TITLE
Editor: Contact Text Set

### PR DESCRIPTION
**Pull request by dmmulroy**
## Summary

This adds the Contact Text Set (https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=837%3A2564)

## User-facing changes

N/A
## Testing Instructions

Enable the text sets flag in experiments and see the new text sets in the story editor.

Partial for #4078

### CODE REVIEW

**Review by miina — CHANGES_REQUESTED** [review]
Thanks for adding the sets, some noticed details:
- The first contact set: could we change it so that it would show on the left in the preview as well? Currently, it seems centered in the preview. For that we would need to extend the text elements longer so that even if it's centered in the preview, it would still show the text on the left. It's actually the same way in Figma: the element itself is full-width while having 40px margin from both sides:
Screenshot 2020-09-30 at 10 26 18

Screenshot 2020-09-30 at 10 24 36


- Might be good to confirm with Sam to understand how much room should be left from the bottom of the Page. Currently, it seems that the contact details are exactly on the limit of the safe-zone already -- these should probably always be inside the safe-zone and perhaps leave some additional margin as well. In most cases it looks fine but in some cases it seems a bit too close to the bottom. Thoughts?
Screenshot 2020-09-30 at 10 28 24

- For this text set, the "Contact Us" has capital letters and size 19px in Figma (camel + 14px in the set):
Screenshot 2020-09-30 at 10 31 46

- For this text set, let's use Text with Fill background for the first block (instead of shape + text) -- this way the user can just change the text without having to center and change the shape's width separately. And for the second text, we could use one black rectangle shape below the text and on top a Text with white Fill background -- this way the user can change the color of the button and wouldn't need to change the 4 border shapes but just 1 shape
Screenshot 2020-09-30 at 10 34 34

- The first text should have letter-spacing 5% perhaps? Currently 1%. Also, in another text set, 16.61px is set as 17px for the font size but in this one it's set to 16px -- should it be 17px everywhere in this case?
Screenshot 2020-09-30 at 10 39 39

**Comment by samitron7** [comment]
@miina Thanks for flagging all this.

1. In regards to contact sets being centered versus left align, please do ensure that it's left aligned. For the optimal aspect ratio, I have the text box stretched out to 332px (when possible) giving the overall layout a 40px left and right buffer on the page. 332px is also the same width of the design safe zone (which we'll implement soon). So what Minna is suggest is perfect!

2. For how much room should we leave between text sets and the bottom of the page, I created bounding boxes for each text element and we should use those to place the text sets on the page. This should ensure that the set is within the safe zone. 
Frame 5489

3. Use box fill where possible and don't use a separate rectangle shape as minna suggested 

4. In general, ensure we follow the harmonic type scale. This is what makes the type layout look nice :)

**Comment by dmmulroy** [comment]
@miina All of the above should have been addressed!

**Review by miina — APPROVED** [review]
Thanks for the changes! Otherwise looks good but there are still some text sets that seem to be too close to the bottom compared to what's in Figma, for example:
- Editor:
Screenshot 2020-10-01 at 11 55 43

- Figma:
Screenshot 2020-10-01 at 11 55 31

Approving pending that -- if you could review the sets to ensure the text sets are positioned assuming the "invisible box" around them that's in Figma is docked to the bottom, not the text itself.

**Comment by dmmulroy** [comment]
@miina I forgot to push my changes on Thursday 🤦 Spacing should be correct now

**Comment by miina** [comment]
@dmmulroy Good to go from my side. 👍

**Review by BrittanyIRL — CHANGES_REQUESTED** [review]
These look great! Noticed a few tiny discrepancies to figma

**Set 1:** 
- I'm thinking it's intentional to round the font size to 22px? 

(editor)
Screen Shot 2020-10-05 at 9 31 15 AM

(figma)
Screen Shot 2020-10-05 at 9 31 04 AM

**Set 2:** 
- Top line should be black like other 2 lines 

(editor)
Screen Shot 2020-10-05 at 9 36 20 AM

(figma)
Screen Shot 2020-10-05 at 9 36 25 AM




**Set 3:** 
- email address should be 18px not 16px

(editor)
Screen Shot 2020-10-05 at 9 37 52 AM

(figma)
Screen Shot 2020-10-05 at 9 37 47 AM


**Set 5:** 
- I think that the font weight should be "medium" to be a 500 weight here on the oswald headline
- The horizontal line separating "contact" from the address should be white

(editor)
Screen Shot 2020-10-05 at 9 40 31 AM

(figma)
Screen Shot 2020-10-05 at 9 40 26 AM

**Set 8:** 
- the top and bottom border should be black 
(editor)
Screen Shot 2020-10-05 at 9 50 06 AM
(figma)
Screen Shot 2020-10-05 at 9 50 11 AM

**Review by BrittanyIRL — APPROVED** [review]
Per discussion with Dillon, who filled me in a little bit more on the scope here -the only change to make pertaining to this PR is the one font size that was wrong. Otherwise, the issues with things like borders are due to something external with loading 1px heights, and yes we're rounding fonts. 

Contact text sets work as expected and look v. good.

**Pull request merged**
