### PR TITLE
Add thumbnail to media snackbar messages.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

While working on another PR, I noticed there are a number of places where poster image / image source could be used for the snackbar message.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
Would you mind adding screenshots & testing instructions? And generally fill out the template. Makes reviewing a bit easier :)

**Comment by spacedmonkey** [comment]
> Would you mind adding screenshots & testing instructions? And generally fill out the template. Makes reviewing a bit easier :)

That is going to be hard, as these changes only effect error states and those are hard to trigger. I think I may close this change for now, as it impossible to test without manually trigger error.

**Comment by timarney** [comment]
> That is going to be hard, as these changes only effect error states and those are hard to trigger. I think I may close this change for now, as it impossible to test without manually trigger error.

Are you closing this one?

**Comment by Angelia64** [comment]
Yes

Angelia's

**Pull request closed without merging**
