### PR TITLE
Unlock stylelint version

### PR DESCRIPTION
**Pull request by dvoytenko**
This fails for some internal stylelint reason. The message is:

"result.apply is not a function"

Stack:
```
    at node_modules/@stylelint/postcss-css-in-js/extract.js:267:13
    at Array.some (<anonymous>)
    at isStylePath (node_modules/@stylelint/postcss-css-in-js/extract.js:257:33)
    at CallExpression (node_modules/@stylelint/postcss-css-in-js/extract.js:347:41)
    at NodePath._call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
```

### CODE REVIEW

**Comment by swissspidy** [comment]
That's why I closed the Dependabot PRs, e.g. #1833, #1862. Was hoping they'd fix this upstream

**Comment by dvoytenko** [comment]
> That's why I closed the Dependabot PRs, e.g. #1833, #1862. Was hoping they'd fix this upstream

@swissspidy , yep, understood. But maybe that's not happening and we need to file a bug?

**Comment by swissspidy** [comment]
Yeah sounds like it

**Comment by swissspidy** [comment]
Upstream issue: https://github.com/stylelint/stylelint/issues/4793

One suggested workaround there is to use `stylelint --syntax "css-in-js"`

Let's try that?

**Review by swissspidy — APPROVED** [review]

**Review by spacedmonkey — APPROVED** [review]

**Pull request merged**
