### PR TITLE
[TEMPLATE] Fitness

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Adds initial static fitness template. This one was a little more of a challenge for the editor from just a layout with the new aspect ratio as well as being heavily reliant on some currently unsupported features.

Unsupported features needed were marked in the missing editor features document.

### Screenshots
Screen Shot 2020-05-01 at 3 20 17 PM

### CODE REVIEW

**Comment by pbakaus** [comment]
Nice! Haven't looked at the actual code closely, but I noticed that the text is cut off at the top in the screenshot...any idea why?

**Review by BrittanyIRL — APPROVED** [review]
Looks great!

**Comment by carloskelly13** [comment]
To @pbakaus's point some fonts have strange line heights. The text box is fine, but unless we give it a full 1.0 line height the tops do get cut off. Unfortunately a 1.0 line height makes the gaps really big. What I've seen in cases where fonts have strange tracking is separate boxes for each line, or custom padding applied to the text box when _this specific_ font is used. Neither are great options, but this is a font-thing.

Screen Shot 2020-05-04 at 10 25 36 AM

**Comment by maxyinger** [comment]
> To @pbakaus's point some fonts have strange line heights. The text box is fine, but unless we give it a full 1.0 line height the tops do get cut off. Unfortunately a 1.0 line height makes the gaps really big. What I've seen in cases where fonts have strange tracking is separate boxes for each line, or custom padding applied to the text box when _this specific_ font is used. Neither are great options, but this is a font-thing.

Yea, I made note of this in the missing features doc. Left it with the < 1 line height since it was more "correct" and figured once this bug is fixed, all the stories would look nice and not need as much refactoring. Happy to just make it work tho for this with the separate lines manually spaced knowing that we'll probably have to come back to it and reset to what it's currently now

**Comment by carloskelly13** [comment]
Awesome. I think since it is noted then we can merge this in.

**Review by carloskelly13 — APPROVED** [review]

**Pull request merged**
