### PR TITLE
[TEMPLATE] Beauty 

### LINKED ISSUE #1479: Template: Beauty
Create template for Beauty
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
Adds static beauty template

## Screenshots
Screen Shot 2020-05-06 at 2 16 06 PM

### CODE REVIEW

**Review by carloskelly13 — CHANGES_REQUESTED** [review]
Everything looks good but on the last page it appears as if some text is leaking through in the middle. Actually that might be a missing image.

Screen Shot 2020-05-06 at 3 58 11 PM

**Review by BrittanyIRL — COMMENTED** [review]
This looks really good!  Few nits but overall this is great! 

Page 1: Looks like the pink at the bottom isn't up against the edges completely 
Screen Shot 2020-05-06 at 3 05 50 PM

Page 2: Some of the hearts have straight edges on their shadow: 
Screen Shot 2020-05-06 at 3 06 40 PM

Page 3: It looks like this is supposed to have a background color that's white, where the 'see full story' is but as seen in the branch that sage background is under the text. 
Screen Shot 2020-05-06 at 3 10 11 PM

Page 8 has misalignment on the 'trend :)' border:
Screen Shot 2020-05-06 at 3 15 04 PM

**Comment by swissspidy** [comment]
@littlemilkstudio Heads up! I merged the master branch to resolve conflicts. Image URLs are now a bit different, e.g. `${imageBaseUrl}images/templates/beauty/beauty_page1_bg.png` (dropping `assets/`, and renaming `pluginDir` to `imageBaseUrl`)

**Comment by maxyinger** [comment]
> @littlemilkstudio Heads up! I merged the master branch to resolve conflicts. Image URLs are now a bit different, e.g. `${imageBaseUrl}images/templates/beauty/beauty_page1_bg.png` (dropping `assets/`, and renaming `pluginDir` to `imageBaseUrl`)

Awesome thanks for the heads up! I'll update now

**Review by BrittanyIRL — APPROVED** [review]
Discussed the nit differences I found vs figma with Max and none of them are really things that can be addressed here. We'll need a design pass on these templates with the updated ratios anyway. This looks great and I think it definitely achieves its goal.

**Review by carloskelly13 — APPROVED** [review]

**Pull request merged**
