### PR TITLE
Page Layouts: Keyboard Navigation

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Summary

Gives users the ability to use keyboard arrows to navigate through page layouts.

## Relevant Technical Choices

- forwards ref to pageLayout to control focus with arrows in pageLayouts
- added prop `isFocused` in pageLayout tells us if the keyboard is in use and if it is we stop propagation on events that need to not bubble up to pageLayouts (keyUp, focus, blur). 
- Reference isRTL from useConfig to decide which way arrow nav should go. 
- PageLayouts gets 2 new refs - pageRefs (object) of refs holding all available pages to focus on and `containerRef` which is used for the useFocusOut hook to reset keyboard nav state.
- This doesn't look as similar to other places hijacking the nav for arrows because we're using a virtualized list.

## To-do

- [ ] I'm having trouble figuring out how to get the dialog to focus from keyboard - i can't add a ref anywhere to the dialog that is set up in time for a hook to grab it and focus and the button does not have the ability to forward a ref. Has anyone had to do this with the editor and want to lend a hand?

There's also an issue of if you tab out of the page layouts and you're focused on the actual story page, if you don't first hit 'escape' before 'shift+ tab' focus isn't released from the story page - this feels entirely out of the wheelhouse of this ticket but I wanted to mention it as an edge case just incase there's something I'm unaware of that can prevent this given all of the focus control that occurs in the editor. 

## User-facing changes

Only visible if page layouts experiment is true. 

If it is true, then this gives users the ability to navigate through page layouts with arrow keys. You can tab into the page layouts like media and then use arrows to go through them, hitting tab again will move you out of the page layouts. 

## Testing Instructions

You can tab into the page layouts like media and then use arrows to go through them, hitting tab again will move you out of the page layouts.  (If you hit 'enter' the focus doesn't shift to the dialog, I've been trying to get that to work for the better part of the afternoon.)

---

Addresses #5876

### CODE REVIEW

**Comment by BrittanyIRL** [comment]
@googlebot I consent.

**Comment by BrittanyIRL** [comment]
@zachhale when you get a sec - will you consent for the google bot so that when this is good to go we're not blocked by the bot?

**Comment by zachhale** [comment]
@googlebot I consent.

**Comment by BrittanyIRL** [comment]
Figured out why this is weird - react virtualized + our grid set up for the panel nests the actual focusable content making the existing utils to handle focus of keyboard impossible to use. Closing in favor of a cleaner solution that prevents us having to track a bunch of refs by just fixing the grid.

**Pull request closed without merging**
