### PR TITLE
Fix Karma tests related to dropdown

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Some failing tests have snuck into main. This fixes the ones related to the new dropdown used by font weight, as seen here #6937 

## Summary

adjust karma tests for fontWeight that were failing because of the new dropdown structure. We need to wait until the dropdown is expanded to be able to see the list items now that we are using portals (so that we only have 1 version of the dropdown) so adding awaits and timeouts.

## User-facing changes

None

## Testing Instructions

See that karma tests no longer have the 5 failing tests identified in #6937  

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
Still seeing some failing tests here on CI:

* `should correctly copy pattern background to page with image`
* `should correctly copy image to page without image`
* `should correctly copy image to page with existing image`
* `should open the edit/delete menu`
* `should display the link tooltip correctly`
* `should correctly show focus border only when using keyboard`
* `should not render an overlay when there is none`
* `should render panel when there is an image in the background`
* `should render correct overlay when clicking "solid"`
* `should render correct overlay when clicking "linear"`
* `should render correct overlay when clicking "radial"`
* `should replace top image when bg image is set and another one is on top`

do any of these ring a bell to anyone? any recent changes to those areas?

**Comment by BrittanyIRL** [comment]
> Still seeing some failing tests here on CI:
> 
> * `should correctly copy pattern background to page with image`
> * `should correctly copy image to page without image`
> * `should correctly copy image to page with existing image`
> * `should open the edit/delete menu`
> * `should display the link tooltip correctly`
> * `should correctly show focus border only when using keyboard`
> * `should not render an overlay when there is none`
> * `should render panel when there is an image in the background`
> * `should render correct overlay when clicking "solid"`
> * `should render correct overlay when clicking "linear"`
> * `should render correct overlay when clicking "radial"`
> * `should replace top image when bg image is set and another one is on top`
> 
> do any of these ring a bell to anyone? any recent changes to those areas?

yeah, i was focusing on the dropdown ones. @miina  is taking a look at the ones related to the Filter panel right now.

**Comment by BrittanyIRL** [comment]
@swissspidy - do you want me to make separate issues for all of these groups and turn these tests to `xit` to silence them while we work on fixes? 

Pretty sure that the `should display the link tooltip correctly` has been failing for a while now.

**Comment by swissspidy** [comment]
> @swissspidy - do you want me to make separate issues for all of these groups and turn these tests to `xit` to silence them while we work on fixes?

That would be great yes. This otherwise blocks a lot of work.

They should be looked at very soon though and not forgotten about :-) So I'd say P1.

> Pretty sure that the `should display the link tooltip correctly` has been failing for a while now.

😞

**Comment by miina** [comment]
All the tests related to the Filter panel (e.g. `should render correct overlay when clicking "solid"`) seem to come from no element being selected when the testing happens so this means no filter panel being found either. The only problem is that this does not happen locally so a bit hard to debug 😞 

-> It looks like dragging media to the background is not working as expected and is not creating an element -- trying some different numbers for the dragging position to see if that might help (I think there was a slight shift/change in the Zoom PR that might have influenced the canvas node).

**Comment by BrittanyIRL** [comment]
#6948 
#6949
#6950
#6951
#6952
#6953 
#6954 
#6955

**Comment by swissspidy** [comment]
Thanks @BrittanyIRL!

If you and @barklund could assign those tickets to the most suitable pod/person that would be awesome.

In the meantime I'll try to think about how this can be better prevented in the futurre.

----

As a reminder, we currently don't have required status checks due to https://xwp.slack.com/archives/CCCAUAH6F/p1615565503065600?thread_ts=1615479664.056100&cid=CCCAUAH6F

**Comment by swissspidy** [comment]
Very interesting diff on Percy: https://percy.io/google/web-stories-wp/builds/9628584?utm_campaign=google&utm_content=web-stories-wp&utm_source=github_status_public

Not caused by this PR, but might warrant some bugfix tickets.

**Comment by BrittanyIRL** [comment]
> Very interesting diff on Percy: https://percy.io/google/web-stories-wp/builds/9628584?utm_campaign=google&utm_content=web-stories-wp&utm_source=github_status_public
> 
> Not caused by this PR, but might warrant some bugfix tickets.

yeah that is a weird one. should just monitor it to see if that change persists.

**Review by samwhale — APPROVED** [review]

**Review by embarks — APPROVED** [review]
Nice! Thank you for the #references in the comments

**Comment by miina** [comment]
> Very interesting diff on Percy: https://percy.io/google/web-stories-wp/builds/9628584?utm_campaign=google&utm_content=web-stories-wp&utm_source=github_status_public
>
> Not caused by this PR, but might warrant some bugfix tickets.

Seems to be working as expected in the editor. It looks like there's a difference between what's happening in the CI and locally/in the editor.

**Pull request merged**
