### PR TITLE
Template Updates: Travel

### LINKED ISSUE #6975: Template Updates: Travel
## Description 

**Bolded** text are updates from April 6, 2021: https://docs.google.com/spreadsheets/d/1MFtHj7Xwdol9jSk80PXrxWNz_0h1tSfyEe3K7Bn2yZs/edit#gid=0

| Page | Animations | Cosmetics |
| --- | --- | --- |
| 1 | Remove headline animation. **Logo to fly in; Background image to fade in 3000ms**  | N/A |
| 2 | Remove image animation; headline updated to Fly in. **Byline to fly in** | N/A |
| 3 |  Headline and text updated to fly in; remove animation on image.  |  Change background of 'learn more' shape.   |
| 4 |  Says to make it the same as the animation on page 10, so fly in?  | N/A |
| 5 | Remove animation on headline and text. **Background image fade in 3000ms**  | N/A |
| 6 | Headline updated to fly in; map shape updated to fade in; remove background animation. | combine map shape.  |
| 7 | Remove animation on image; headline and text updated to fly in.  **image to fade in 3000ms** | Update background of learn more shape.  |
| 8 | Headline and text updated to fly in; remove background animation. **Learn more to fade in 3000ms**  | update background color of learn more shape; update font color.  |
| 9 | **Images to whoosh in 2000ms** | N/A |
| 10 | Headline to fly in; remove animation on social icons. **images to whoosh in 2000ms** | combine social media shapes. |
 
See Figma for specifications: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7216%3A549493 

If design requests have updated please make note in a comment here so that testing is aware of updated specs. 

## Acceptance 
- Template is updated 
- Relevant stickers are created 
- assistive text is updated so that prepublish checklist is happy

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Part of 1.7 release is updating existing templates to avoid custom animations and unnecessary prepublish checklist suggestions. 

## Summary

Travel Template revisions: 
- remove custom animations and replace them with effects available in editor
- update svgs to stickers (socials and map)
- swap square colors to be black, some text color updates
- add assistive text to images.

## Relevant Technical Choices

When Ivo and I were revising the custom animations neither of us remembered that fade in is only available on foreground elements, so I chose to either zoom in or pan in for relevant background images:
- Elephant bg image will zoom in on page 1 (was supposed to fade in)
- Photographer bg will pan in from left on page 5 (was supposed to fly in)

## To-do

- [x] Design Review

## User-facing changes

Travel template has been updated. 

**Before**
https://user-images.githubusercontent.com/10720454/114075533-7c034600-985a-11eb-81c6-28cca2317580.mp4

**After**
https://user-images.githubusercontent.com/10720454/114075559-845b8100-985a-11eb-899c-b15db3dadee0.mp4

## Testing Instructions

Use the travel template from dashboard/explore templates and see that template has been updated in line with Figma: https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=7357%3A546039 and as specified here: https://github.com/google/web-stories-wp/issues/6975 
There should be no more custom animations, all images should have assistive text.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6975

### CODE REVIEW

**Review by maxyinger — APPROVED** [review]
lgtm!

**Review by samwhale — APPROVED** [review]
Also looks amazing

One question:
The map does not have any animation on it. Should the map fade in like it says here? 
image

**Comment by BrittanyIRL** [comment]
> One question:
> The map does not have any animation on it. Should the map fade in like it says here?

🤦‍♀️  yuppp it absolutely should, i updated stickers this am and forgot to restore that map. Should be fixed!

**Comment by ivayloklissarov** [comment]
Small fixes:

Page 1:
- Remove logo & background rectangle animation
Screen Shot 2021-04-13 at 5 35 32 PM

Page 5
- Change background image aimation to the exact same settings at the animal image on Page 1 
Screen Shot 2021-04-13 at 5 38 14 PM

Page 8
- Remove animation on the blue rectangle
Screen Shot 2021-04-13 at 5 39 49 PM

**Comment by BrittanyIRL** [comment]
Thanks @ivayloklissarov ! 

Updates:

Page 1:
- Remove logo & background rectangle animation

travel page 1

Page 5
- Change background image animation to the exact same settings at the animal image on Page 1

travel page 5

Page 8
- Remove animation on the blue rectangle
travel page 8

**Pull request merged**
