### PR TITLE
Dashboard: Color and Categories Filters UI for Templates Gallery

### PR DESCRIPTION
**Pull request by carloskelly13**
## Summary

- Adds the ability to filter and sort colors and categories
- Adds support to clear multiple-selected choices and show a color dot for colors
- Adds constants for currently-defined template filter choices

## Relevant Technical Choices

- Create a hook to separate out the set, update, and clear logic so the main template page does not get cluttered and it can be reused. 

Addresses #776 

Screen Shot 2020-04-28 at 11 24 32 AM
Screen Shot 2020-04-28 at 11 24 39 AM

### CODE REVIEW

**Review by BrittanyIRL — CHANGES_REQUESTED** [review]
Nice! 

So, the UI works well, but I think something goofy happened with the many rebases and merges that have been going on because the entire panel is very narrow now: 
Screen Shot 2020-04-28 at 2 21 13 PM

I was looking at this video: https://drive.google.com/drive/u/0/folders/1onGbNRFVAalJXtbYYFigSbdG-nHUE7As and noticed that the 'x' that shows up to clear filters is no longer blue, and the colors aren't labeled. And that when more than 1 filter is selected a `+X` shows up to designate it. 

I know I am about to update the filters so if we want to do this update with that it's fine by me. 
Screen Shot 2020-04-28 at 2 19 18 PM
Screen Shot 2020-04-28 at 2 19 02 PM

Could you also add a storybook example of the color version of the panel since it adds some new props to the dropdown set up?

**Comment by carloskelly13** [comment]
@BrittanyIRL I do need to fix that, I think a rebase did break it. Also I am dropping the text as Sam mentioned but I do think we will need to add the close in a follow up PR.

**Comment by carloskelly13** [comment]
@BrittanyIRL I sorted out the merge conflicts and updated the styles to be closer to the new UI.

Screen Shot 2020-04-28 at 4 36 05 PM

Screen Shot 2020-04-28 at 4 34 58 PM

**Review by BrittanyIRL — APPROVED** [review]

**Comment by BrittanyIRL** [comment]
Awesome! Thanks for those changes!

**Pull request merged**
