### PR TITLE
Stickers: Update Radish and Sunburst 

### LINKED ISSUE #7372: Update Radish Sticker
Previously, the radish was cut off at the page end, the asset now includes the hidden bit of the radish that is used on cooking template page 2.

Acceptance Criteria: 
- Update radish sticker
- Update template to use new sticker

### LINKED ISSUE #7373: Update Starburst Sticker
Previously, the starburst used in the fashion template page 2 was cut off as an asset on page end, we should update the asset to use the whole starburst now that it is available .

Acceptance criteria: 
- Update sticker to use full starburst 
- Update Page 2 Fashion Template to use new asset

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Figma was exporting assets for me according to what's visible in the frame, I assumed that this was intentional. Turns out it's just because I have view only permissions. 

## Summary

Updates radish and sunburst stickers to not be cut off as stickers even if part of the sticker is not exposed in the page.

## Testing Instructions

Look at Cooking page 2 and Fashion page 2 - move the radish and the sunburst and see that they are not partial images.

| Fashion page 2 (Starburst) | Cooking page 2 (Radish) |
| --- | --- |
| sunburst | radish |

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #7372 
Fixes #7373

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
noice

**Comment by swissspidy** [comment]
Random question: do we have human readable names for these stickers in the stickers panel (like we do for masks)? For accessibility :-)
If not, would be good to track & fix this

**Comment by samwhale** [comment]
> Random question: do we have human readable names for these stickers in the stickers panel (like we do for masks)? For accessibility :-)
> If not, would be good to track & fix this

I don't think we do. ~I can make a ticket for this~ Added here :#7425

**Review by embarks — APPROVED** [review]

**Comment by embarks** [comment]
@googlebot I consent

**Review by maxyinger — APPROVED** [review]

**Pull request merged**
