### PR TITLE
Code Quality: Dynamically import mediainfo.js

### PR DESCRIPTION
**Pull request by swissspidy**
## User-facing changes

N/A

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Ensure that media uploads are still working as expected

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Review by spacedmonkey — APPROVED** [review]
Change looks good, but was unable to test locally.

**Comment by spacedmonkey** [comment]
This is good to merge. Are we merging before the next release?

**Comment by swissspidy** [comment]
@spacedmonkey waiting for QA

**Comment by swissspidy** [comment]
cc @kkalarickal

**Comment by kkalarickal** [comment]
@swissspidy @spacedmonkey - I tested media upload on using `12954-branch` on https://stories-qa-wordpress-amp.pantheonsite.io/

- all supported file types
- linking to files from external URL
- recording and embedding video/audio
- background audio/closed captions
- poster image
- publisher logo

The basic workflows all seem to work as expected.

I did run into a crash on the video recording workflow though:


Trying to recrate it consistently.

**Comment by swissspidy** [comment]
That might be a new issue, but not sure. Would need to try to recreate myself to see the exact cause of error.

**Comment by swissspidy** [comment]
Don't see any issues with video trimming. Warrants a new issue if it persists.

**Comment by kkalarickal** [comment]
I could not recreate the crash again after multiple attempts. It needs a new ticket if it occurs again after merge on `main branch`.

**Pull request merged**
