### PR TITLE
Add additional sorting value to ensure the same order of found posts

### LINKED ISSUE #1726: Dashboard not getting returned all stories when sorting by author
## Bug Description
In the dashboard (https://stories-new-wordpress-amp.pantheonsite.io/wp-admin/edit.php?post_type=web-story&page=stories-dashboard#/) if you switch the sort to 'created by' you don't get all of the results. I count 69 results out of the 90 at the time of this writing on stories-new-wordpress-amp and locally, out of my 23 stories i'm only getting 12.
It's only when I sort by created by that this is occurring. 

The API getting looked at is: `wp/v2/web-story?context=edit&order=asc&orderby=story_author&page=1&per_page=10&status=publish%2Cdraft&_locale=user` where the orderby is `story_author` 

## Expected Behaviour
sorting by story_author to return the same amount of results as sorting by any other sort method, say `orderby=date` 

## Steps to Reproduce

Navigate to dashboard in browser, take note of total stories (this is from the API header and what we've considered the source of truth for the count). Now sort by `created by` and see that you never actually get the total amount of stories returned despite paging.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by miina**
## Summary
Adds additional sorting value to ensure the same order of found posts. Otherwise, there could be duplicate entries on different pages.

## To-do

---

Fixes #1726

### CODE REVIEW

**Comment by miina** [comment]
@BrittanyIRL Could you test to confirm if it fixes #1726 locally for you?

**Review by spacedmonkey — APPROVED** [review]
I didn't manage to replicate the issue locally. But this change look valid and tests are passing so I will approve.

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Could you test to confirm if it fixes #1726 locally for you?

Wow, thank you for getting to this so fast! It works great for descending (alpha a to z) but it looks like there's no option to set it to ascending? If you toggle over to the 'list' view, there's the added option to swap and go z - a. Any chance implementing that here is a quick win? Otherwise it can be its own ticket since i think it's something i overlooked in my initial request for this functionality. 

author sort list

**Comment by miina** [comment]
@BrittanyIRL Just to confirm -- in case of ascending, should the current author be the last independent of the name, and the rest of the authors come first?

`story_author` has the enforced logic of displaying the current author as the first. If the goal is to display authors just by the name (independent of the current author) then just `author` can be used for `orderby`.

Thoughts?

**Comment by BrittanyIRL** [comment]
> @BrittanyIRL Just to confirm -- in case of ascending, should the current author be the last independent of the name, and the rest of the authors come first?
> 
> `story_author` has the enforced logic of displaying the current author as the first. If the goal is to display authors just by the name (independent of the current author) then just `author` can be used for `orderby`.
> 
> Thoughts?

@miina - 
OH that's a _great_ point. I think we need Sam or Paul's help on this - thoughts on doing that separately? I know you're on a different pod now and I think that your PR solves the bug.

**Review by BrittanyIRL — APPROVED** [review]
Changes work great! Thank you for the quick fix on this.

**Pull request merged**
