### PR TITLE
Fix checklist karma tests

### PR DESCRIPTION
**Pull request by swissspidy**
Updates fixture data I missed in #8346

### CODE REVIEW

**Comment by swissspidy** [comment]
@samwhale Would appreciate your help here, I won't have time today to fix the test.

**Review by BrittanyIRL — APPROVED** [review]
❤️  Thanks, Pascal.

**Comment by BrittanyIRL** [comment]
whoops, it looks like it's still failing `expected null to not be null` - i can take a quick look under the hood.

**Comment by BrittanyIRL** [comment]
Ok, so I see what happened here. Here's to Karma tests actually catching helpful updates! 😂  

So the image dimension check got moved to be inside of the priority section, however it's still getting listed as a design issue. 

(Issue is working just fine, but the title doesn't match)
Screen Shot 2021-08-11 at 8 54 10 AM

`DESIGN_COPY.imageResolutionTooLow.title` getting used in the design issues. 
Screen Shot 2021-08-11 at 8 55 51 AM

@swissspidy can I add to this PR, do you mind?

**Comment by BrittanyIRL** [comment]
Pushed up a fix. It looks like the old constant for `posterTooSmall` was getting used as one of the checks for `posterIssuesRequiringMediaUploadPermissions` which was causing the `null to not be null` error above. This check isn't actually used anywhere else now, we're using `videoMissingPoster` or `imageResolutionTooLow` so it's obsolete. Just removing the old constant and updating the array used to check that the appropriate checks are showing up.

**Comment by BrittanyIRL** [comment]
@googlebot I consent.

**Review by maxyinger — APPROVED** [review]

**Pull request merged**
