### PR TITLE
Fix SVGO config

### LINKED ISSUE #6357: Bundler: SVG stroke/fill is not removed as expected
## Bug Description

Storybook build does not replace fill/stroke with `currentColor` as the primary build does. This makes the Storybook build less reliable as a reference.

However, width/height **is** removed, so some SVGO plugins are running.

This SVG:

```svg
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M21 8.5V23.5" stroke="green" stroke-linecap="round" stroke-linejoin="round"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M12 14C11.1716 14 10.5 14.6716 10.5 15.5V16.5C10.5 17.3284 11.1716 18 12 18H17C17.8284 18 18.5 17.3284 18.5 16.5V15.5C18.5 14.6716 17.8284 14 17 14H12Z" fill="hotpink"/>
</svg>
```

Results in this list of icons:
Screen Shot 2021-02-11 at 20 09 37

With this source in place of the SVG:
```svg
<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M21 8.5v15" stroke="green" stroke-linecap="round" stroke-linejoin="round"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M12 14a1.5 1.5 0 00-1.5 1.5v1A1.5 1.5 0 0012 18h5a1.5 1.5 0 001.5-1.5v-1A1.5 1.5 0 0017 14h-5z" fill="#ff69b4"></path></svg>
```

Also, notice how the fill color name is normalized to a hex value, but the stroke is not.

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by swissspidy**
## Context

The SVGO configuration wasn't working as expected.

## Summary

This fixes the SVG configuration so that the desired options are again applied as desired.

## User-facing changes

There shouldn't be any user-facing changes here.

### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #6357

### CODE REVIEW

**Review by spacedmonkey — DISMISSED** [review]
There seems to be some SVGs that are broken after this change. 

https://percy.io/google/web-stories-wp-e2e/builds/8829493/changed/501037793?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600

https://percy.io/google/web-stories-wp/builds/8829665/changed/501047420?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600

I believe this is related to removal of colors encoding to the SVG. Before we merge this change, we will need to give these issues first

**Comment by spacedmonkey** [comment]
We might also want to wait until #6272 is merged / test this change against this PR as it so svg icon heavy.

**Comment by swissspidy** [comment]
Gotta love visual regression tests! 😻 

> [percy.io/google/web-stories-wp-e2e/builds/8829493/changed/501037793?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600](https://percy.io/google/web-stories-wp-e2e/builds/8829493/changed/501037793?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600)

Ah, the logo! That one's tough. We basically need to exclude that from any transformation to preserve the colors.

> [percy.io/google/web-stories-wp/builds/8829665/changed/501047420?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600](https://percy.io/google/web-stories-wp/builds/8829665/changed/501047420?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600)

That one should just get the correct colors via the styled components.

**Comment by spacedmonkey** [comment]
> Gotta love visual regression tests! 😻

 Prove there value, yet again!

> That one should just get the correct colors via the styled components.

Agreed. Should this be in it's own ticket.

**Comment by barklund** [comment]
> > [percy.io/google/web-stories-wp-e2e/builds/8829493/changed/501037793?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600](https://percy.io/google/web-stories-wp-e2e/builds/8829493/changed/501037793?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600)
> 
> Ah, the logo! That one's tough. We basically need to exclude that from any transformation to preserve the colors.

Could we add a class to the SVG's, that shouldn't undergo this conversion? Maybe something like `<svg class="keep-colors" ...></svg>`? Thought [I don't really see](https://npmdoc.github.io/node-npmdoc-svgo/build/apidoc.html#apidoc.element.svgo.convertColors.fn) how that could work...

Maybe two different rules for svg's based on folder name? So svg's that should not undergo this transition have to be in a specifically named folder? Or have a file name suffix: `logo.keepColor.svg`?

**Comment by swissspidy** [comment]
> Maybe two different rules for svg's based on folder name? So svg's that should not undergo this transition have to be in a specifically named folder? Or have a file name suffix: `logo.keepColor.svg`?

Either would work and could be done at the webpack config level. I'll give it shot.

**Comment by swissspidy** [comment]
> > Maybe two different rules for svg's based on folder name? So svg's that should not undergo this transition have to be in a specifically named folder? Or have a file name suffix: `logo.keepColor.svg`?
> 
> Either would work and could be done at the webpack config level. I'll give it shot.

Looks like it works!

Only a couple of icons left that need to be fixed:

https://percy.io/google/web-stories-wp/builds/8872169/changed/503330568?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1600&widths=1600

**Comment by spacedmonkey** [comment]
There are 5 screenshots with differs. It seems like it only two places. 

Screenshot 2021-02-16 at 13 53 51
Screenshot 2021-02-16 at 13 54 10

Should be simple to fix...

**Comment by swissspidy** [comment]
There were only a couple of _legit_ changes in the last Percy run. 

Looks all good to me know.

**Review by spacedmonkey — APPROVED** [review]
Change looks good to me, if visual changes are expected.

**Pull request merged**
