### PR TITLE
Update Web Stories icon

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Updates the WordPress admin menu icon with the new one (white).

Updates the Web Story embed block icon with the new one (color).

## User-facing changes

**Admin Menu**

Screenshot 2020-09-09 at 10 04 03

Screenshot 2020-09-09 at 10 04 10

**Block**

Screenshot 2020-09-09 at 13 59 14
Screenshot 2020-09-09 at 13 59 00

## Testing Instructions

---

See #4408

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@swissspidy Don't we also have to update the icon the embed block. 

Screenshot 2020-09-09 at 11 51 27

**Comment by swissspidy** [comment]
@spacedmonkey Ah, good point! Let me add that.

**Review by spacedmonkey — APPROVED** [review]

**Comment by westonruter** [comment]
@swissspidy This may not be an issue anymore with this PR but I noticed on `main` that the icon shows with a black color for a split second while waiting for the JS to initialize:

image

The AMP plugin had the same issue in the past. I fixed it by making the icon be initially gray instead of black: https://github.com/ampproject/amp-wp/pull/2417

**Review by crypt096 — APPROVED** [review]

**Comment by swissspidy** [comment]
@westonruter Good call! With this PR the initial flash is white, not black, as that's the SVG's default fill color. I replaced it with the same grey as you used for the AMP plugin and it works like a charm.

**Pull request merged**
