### PR TITLE
Code Quality: Move StoryAnimation components to root

### LINKED ISSUE #3670: Move StoryAnimation components into edit-story codebase & update to useContextSelector pattern
Move all story animation code (provider, wrappers & animations) into edit-story code base. edit-story code should be a dependency of dashboard and not the other way around which it currently is.

Update useStoryAnimation hook to follow useContextSelector pattern used in edit-story codebase.

### PR DESCRIPTION
**Pull request by maxyinger**
## Summary
- Moves animation code closer together and into `/edit-story`.
- Updates `useStoryAnimationContext()` to follow `useContextSelector()` pattern.
- Fixes some PropType warnings around the animation prop types in the dashboard

## Relevant Technical Choices
Just went with all named imports with everything exported from the root `/edit-sotry/animation/index.js` so if anything needs to be imported from the animation module can just be `import { <thing> } from '/edit-story/animation'`. This makes it a little closer to a standalone package, and using all named exports allows for better lookups of source definitions in vs code.

## To-do
NA

## User-facing changes
NA

## Testing Instructions
Nothing should have changed. If there are errors they would be build errors that CI should catch. for safe measure can run the following steps if you so please:
- go to experiments. Turn on `enableAnimations` & save.
- Hover over story with animation in dashboard. should work.
- Edit story with animation and play button should work.
- Preview the same story from the editor and the animations should play in amp.
- turn off `enableAnimations` in experiments & save
- run through all major views from above steps and make sure nothing seems broken

---

Fixes #3670

### CODE REVIEW

**Comment by swissspidy** [comment]
Nice reorganization! I would have no issues with directly moving everything to `assets/src/animation` though to make everyone's lives easier

**Review by mariano-formidable — APPROVED** [review]
Everything looks good to me.  I pulled the repo down and navigated to all the pages with animations enabled and disabled, and everything worked as expected (I even double checked storybook).

The only nit I have is that it seems that an empty `animations` folder is left under our `dashboard` folder:
image

**Comment by maxyinger** [comment]
> Nice reorganization! I would have no issues with directly moving everything to `assets/src/animation` though to make everyone's lives easier

Awesome. yea I can totally move it there if that's the preference.

**Comment by maxyinger** [comment]
> Everything looks good to me. I pulled the repo down and navigated to all the pages with animations enabled and disabled, and everything worked as expected (I even double checked storybook).
> 
> The only nit I have is that it seems that an empty `animations` folder is left under our `dashboard` folder:
> image

oo thought I removed this. thanks for the heads up!

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
