### PR TITLE
Templates: use custom heading levels

### LINKED ISSUE #11928: Templates: make use of custom heading levels
## Feature Description

Originally mentioned during bug bash:

Templates should use semantic heading levels to correctly prioritize the different headings. A bad example is the "Plant Based Dyes DIY" template, where the “1” is an h1 and the “Prepare your fabric” is an h3. The latter should be the most important heading on the page or at least as important as the number

image

To address this, we should go through all templates and identify issues like these and manually set the right headings as h1 etc. and the incorrect ones as paragraphs or subheadings

### PR DESCRIPTION
**Pull request by miina**
## Summary
Updates templates to use custom heading levels were necessary

## Relevant Technical Choices
- Following the automated headings rule, texts with less than 3 characters are not assigned headings
- There can be multiple h1 tags per story
- The first page always has a h1 now

## User-facing changes
N/A

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Go to Explore Templates
2. Select "Use Template" for different templates
3. Click through the text elements in the story that opens to see if the heading levels assigned seem ok

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11928

### CODE REVIEW

**Comment by miina** [comment]
Suggestions for the automated heading levels assignment (will edit this comment until the PR is ready):
- the first page should most likely have a H1, look harder for it :D
- Very long texts shouldn't be headings ("very long" to be defined)
- 2,4 was still assigned as Heading 1 and "m" was assigned Heading 2 -- is the 3 characters rule not working?
- ...

**Review by merapi — APPROVED** [review]

**Comment by miina** [comment]
> Suggestions for the automated heading levels assignment (will edit this comment until the PR is ready):
> 
> * The first page should most likely have a H1, look harder for it 😄
> * Very long texts shouldn't be headings ("very long" to be defined)
> * "2,4" was still assigned as Heading 1 and "m" was assigned Heading 2 -- is the 3 characters rule not working?
> * Quotes should most likely not be headings automatically -- at least none made sense as headings in the templates.

@swissspidy These are the things noticed when re-assigning the headings, let me know if you'd like me to create an issue for consideration of all of these.

**Comment by swissspidy** [comment]
Neat, thanks! Yeah an issue would be great 👍

**Comment by miina** [comment]
Follow-up issue: #12070

**Pull request merged**
