### PR TITLE
Fix font loading

### LINKED ISSUE #12043: Some fonts are not loaded/displayed and have the wrong position
## Bug Description

Issue 1)
The font is not loaded/the wrong font is displayed.

Issue 2)
The position/bounding box is wrong.

Original report:
Text is not correctly displayed and takes more room than assigned,some examples:
Screenshot 2022-07-26 at 11 08 52
Screenshot 2022-07-26 at 11 07 32
Screenshot 2022-07-26 at 11 04 53
Screenshot 2022-07-26 at 11 02 31

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by merapi**
## Context

This PR addresses issue 1) (#12043).

Before:
image

After: 
image

## Testing Instructions

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12043

### CODE REVIEW

**Comment by swissspidy** [comment]
Can we add tests for this to prevent regressions?

**Comment by merapi** [comment]
> Can we add tests for this to prevent regressions?

For font loading verification a good candidate can be the Percy diff because the bounding box doesn't change, so we can only detect the regression visually or by checking the font requests.
Unfortunately, we don't always check every Percy diff, so maybe we can do a visual comparison in Karma test for that?
I did a quick test with the Puppeteer `page.screenshot` function (integrated with our Karma Fixture) - it can return a Buffer so we can:
1) Compare that to other predefined Buffer or image (screenshot of an element with Teko font).
2) Check specific coords and their color (which we know will break if the font is not loaded).

WDYT @swissspidy ?

**Comment by miina** [comment]
@merapi Since @swissspidy is out this week and you'll be out next week when he is back, maybe we can merge the fix and create a follow-up issue for the test? WDYT?

**Review by miina — APPROVED** [review]

**Comment by swissspidy** [comment]
I‘m wary of introducing another type of visual regression tests.

Could we perhaps check for font stylesheets being loaded correctly?

**Review by barklund — APPROVED** [review]
Can we just check the height and width of the text field for the test perhaps?

**Comment by merapi** [comment]
> Can we just check the height and width of the text field for the test perhaps?

Based on my testing - no:
> the bounding box doesn't change

---

> Could we perhaps check for font stylesheets being loaded correctly?

I will look at it in a follow-up, doesn't look trivial.

**Pull request merged**
