### PR TITLE
Bugfix: Animation direction tooltips showing for enabled direction

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Found while prepping for bug bash. 

## Summary

Tooltips were showing up for enabled direction.

## Relevant Technical Choices

A prop was getting the wrong name - needed isDisabled not disabled. Also turning cursor to default when direction is disabled.

## User-facing changes

Tooltips on animation direction should now only show up for disabled directions. 

## Testing Instructions

See that only disabled directions in animation panel show tooltips.

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Review by samwhale — APPROVED** [review]
When `disabled` is not a boolean 😭. In the future it may be better to rename this prop 🤷 

Using typescript here would be dope since we'd know immediately that the types don't line up!

**Comment by BrittanyIRL** [comment]
@csossi this is from bugbash today and needs to be done for release, if you could prioritize it that would be super helpful!

**Review by miina — APPROVED** [review]
Thank you!

**Review by embarks — APPROVED** [review]
`disabled` is always an awkward prop name, considering its semantics in HTML as well. 😅 One thing we could probably be better about is being more aware of prop type errors. Feeling what whale is saying, it would be nice to see that on a type check level.

**Review by maxyinger — APPROVED** [review]

**Comment by BrittanyIRL** [comment]
Em, max, samuel and miina all reviewed and tested this bugfix which feels like a pretty thorough qa, since we want it for release I'm going to go ahead and merge.

**Pull request merged**
