### PR TITLE
Design System: Remove out of date border styling 

### PR DESCRIPTION
**Pull request by BrittanyIRL**
## Context

Remove old border style in outline that snuck through a rebase and is making things the wrong size. 

## Summary

This line of code is obsolete now that focus styles are handled properly. Its getting removed in other PRs but those will take longer to merge. This expedites it. 

### QA

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [ ] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testiing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Review by miina — APPROVED** [review]

**Comment by barklund** [comment]
Hm, not sure what to make about [all the diffs in Percy](https://percy.io/google/web-stories-wp-e2e/builds/8784688?utm_campaign=google&utm_content=web-stories-wp-e2e&utm_source=github_status_public), so can't really approve those nor merge this PR. @BrittanyIRL, can you make any sense of it?

**Comment by BrittanyIRL** [comment]
> Hm, not sure what to make about [all the diffs in Percy](https://percy.io/google/web-stories-wp-e2e/builds/8784688?utm_campaign=google&utm_content=web-stories-wp-e2e&utm_source=github_status_public), so can't really approve those nor merge this PR. @BrittanyIRL, can you make any sense of it?

it's just white noise, we get those 'diffs' all the time in percy. went through and double checke.d

**Review by samwhale — APPROVED** [review]
Thank youuuuu

**Review by maxyinger — APPROVED** [review]

**Comment by maxyinger** [comment]
Makes sense that styles made with this before this change might have a bit of a layout jump if they accounted for the border to begin with. I'm guessing that's what's goin on in the percy diffs.

Kinda why it was dangerous to use border in the first place for the focus styles since it effects layout.

I think this is good that we're removing this now tho and can go back and fix any tiny spacing regressions as they come

**Comment by swissspidy** [comment]
> > Hm, not sure what to make about [all the diffs in Percy](https://percy.io/google/web-stories-wp-e2e/builds/8784688?utm_campaign=google&utm_content=web-stories-wp-e2e&utm_source=github_status_public), so can't really approve those nor merge this PR. @BrittanyIRL, can you make any sense of it?
> 
> it's just white noise, we get those 'diffs' all the time in percy. went through and double checke.d

could you please open a ticket for that? :-)
I'd rather fix that flakiness.

**Comment by BrittanyIRL** [comment]
> > > Hm, not sure what to make about [all the diffs in Percy](https://percy.io/google/web-stories-wp-e2e/builds/8784688?utm_campaign=google&utm_content=web-stories-wp-e2e&utm_source=github_status_public), so can't really approve those nor merge this PR. @BrittanyIRL, can you make any sense of it?
> > 
> > 
> > it's just white noise, we get those 'diffs' all the time in percy. went through and double checke.d
> 
> could you please open a ticket for that? :-)
> I'd rather fix that flakiness.

I'm happy to but it's not new? It's a lot the same as the email you sent out a while ago. 
https://github.com/google/web-stories-wp/issues/6317 I'll try to make note of it in future PRs.

**Pull request merged**
