### PR TITLE
Add support for webm

### LINKED ISSUE #980: Video - WebM format not updated in Panel
## Bug Description

Added a WebM video via "upload" option in panel. Took me to the media library, and uploaded a WebM video there. Selected "insert" option to insert into page. On return to the page in the ed, the video is appearing, but the ALL and VIDEOS sections aren't updated

## Expected Behaviour

ALL and Videos categories in media panel should be updated

## Steps to Reproduce

see above

## Screenshots

image

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
Fixes #980

### CODE REVIEW

**Review by miina — APPROVED** [review]
Works as expected.

**Comment by miina** [comment]
@spacedmonkey Note: I'm getting this error in console after uploading but that's a separate issue. Do you know if we already have an issue for that one?
Screenshot 2020-04-06 at 16 22 18

**Comment by swissspidy** [comment]
I assume that's because of poster generation, so #1001 perhaps?

**Comment by spacedmonkey** [comment]
@swissspidy It is related to #1001 .

**Pull request merged**
