### PR TITLE
New aspect ratio 2:3

### PR DESCRIPTION
**Pull request by dvoytenko**
Possibly blocked on https://github.com/google/web-stories-wp/pull/880

### CODE REVIEW

**Review by pbakaus — APPROVED** [review]
very nice! Did not expect a migration script, it's a pleasant surprise. LGTM.

**Comment by swissspidy** [comment]
Odd thing about `v0009_defaultBackground.js`. That should actually be used, but I don't see it in #693. cc @wassgha

**Comment by dvoytenko** [comment]
@swissspidy Reached out to the @wassgha. If we fixes the migration script for default background, I will rebase this code. Will wait for the response.

**Comment by wassgha** [comment]
Hmm that's odd, definitely should be used! Do you mind adding it before your migration script @dvoytenko ?

**Review by wassgha — APPROVED** [review]

**Pull request merged**
