### PR TITLE
Dashboard dropdown filter displayed over stories when user scrolls up/down

### LINKED ISSUE #11582: Dropdowns "Taxonomies" and "Author" are displayed over stories when user scrolls up/down
## Bug Description

Dropdowns "Taxonomies" and "Author" are displayed over stories when user scrolls up/down.
Issues with dropdowns moving and application crashing when resizing window. See screenshots below.

## Expected Behaviour

A few options: 

1. Close dropdown on scrolling
2. Leave it open, but fix it at its position and don't allow it to scroll with the page

## Steps to Reproduce

1. Go to https://stories-qa-wordpress-amp.pantheonsite.io/wp-admin/
2. Go to the Stories Dashboard
3. Click on the "Author" dropdown and scroll down
4. The same happens when user expands "Taxonomies" dropdown

P.S.: by the time that this bug is fixed, dropdown "Taxonomies" may have been renamed to "Categories".

## Screenshots

Dropdowns move over stories on scroll and resize
https://images.zenhubusercontent.com/235435637/ab11a9fd-9930-457e-b102-9083d5f36a13/dropdowns_on_scroll.mp4

Dropdowns stick to browser window border when resizing window
https://user-images.githubusercontent.com/14057928/171865795-7c0e09c9-7a7f-4558-a9f5-f416b09377cf.mp4

Application crashes if the 'sort' dropdown is open and overflows the bottom of the screen
https://user-images.githubusercontent.com/14057928/171873680-4f25db9d-89b0-4b8d-981c-f1b03ee6b374.mp4

Similar issues with other dropdown happen in the story editor
https://user-images.githubusercontent.com/14057928/171909367-fdbcf4a4-1214-4fa7-b618-42346e6f4b08.mp4

## Additional Context

- Plugin Version:
- WordPress Version:
- Operating System: Windows, MacOS
- Browser: Firefox, Chrome, Safari

### PR DESCRIPTION
**Pull request by mwritter**
## Context

Keep dropdown stationary, to keep the dropdown options from moving with user scroll or window resize.

## Summary

Adds a property to the Popup component to use x and y offset based on anchorRect, instead of using max offsets.

## Relevant Technical Choices

The underlying issue comes from the tight integration between the popup component and the dropdown component.  I opted to add a new property here to let the popup component know that this 'popup' does not need move away from the anchorRect while scrolling.  A bigger code change to separate the popup and dropdown components is probably going to be necessary if the functionality continues to differ.

## To-do

✔️  PR #11625 will need to be updated to add this property to the new taxonomy filters.

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Go to Story Dashboard
2. Open the authors filter
3. Scroll through the stories and resize the browser window (vertically and horizontally)

On Staging
- Notice the dropdown options stays on the screen even when the filter is not visible.

On Branch
- Notice the dropdown stays anchored to the filter.

### Does this PR have a security-related impact?
No

### Does this PR change what data or activity we track or use?
No

### Does this PR have a legal-related impact?
No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #11582

### CODE REVIEW

**Review by mflorida — APPROVED** [review]
Changes pulled and fix confirmed. 👍

**Comment by mwritter** [comment]
> Will adding an override prop be a reliable fix? 🤔

It should be for this particular instance, adding more 'override' props will not be sustainable though. I do think if more issues with the dropdown popup combo crop up we will need to refactor the dropdown to work without the popup.

**Comment by mflorida** [comment]
> > Will adding an override prop be a reliable fix? 🤔
> 
> It should be for this particular instance, adding more 'override' props will not be sustainable though. I do think if more issues with the dropdown popup combo crop up we will need to refactor the dropdown to work without the popup.

Makes sense. Although this kind of dropdown needs to 'pop up' on top of all other content, it's a completely different type of component and should be able to live its best life.

**Review by sblinde — APPROVED** [review]
👏

**Pull request merged**
