### PR TITLE
Use new render class in Admin.php 

### LINKED ISSUE #3868: Use new render class in Admin.php
## Feature Description

Follow up ticket #3733 ( #3325 ). 

Use the new `Embed` class in Admin.php to generate markup for embed block. 

Reapply these changes https://github.com/google/web-stories-wp/commit/a1ccdc7a475b514dc2dcab8ab9af5df8963645b8 and add deprecations. 

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Use new render class in Admin.php 

## Testing Instructions

---

Fixes #3868
See #3581

### CODE REVIEW

**Comment by swissspidy** [comment]
Still getting block validation errors:

Screenshot 2020-08-15 at 17 03 38

Screenshot 2020-08-15 at 17 05 33

**Review by crypt096 — APPROVED** [review]

**Comment by spacedmonkey** [comment]
@swissspidy I am not seeing this issue at all. I am not even sure why you would see it. Can you give me steps to replicate? 

I also don't think it is a big issue, as the plugin is in beta so there are likely very limit of these blocks in the wild.

**Comment by spacedmonkey** [comment]
@swissspidy Why close this?

**Comment by swissspidy** [comment]
Closing as per https://github.com/google/web-stories-wp/issues/3868#issuecomment-678624680

#3581 will require a slightly different route and definitely a new PR. So we can just skip this one here in favor of #3581

**Comment by spacedmonkey** [comment]
I really think that they two different things. One is using the php class another is about responsiveness. I am not sure if I see the link here. I think this one should be reopened.

**Comment by swissspidy** [comment]
It's not about the goal of the tickets but about the changes they cause to the markup.

Another reason, which I think I've shared on Slack before, is that the embed render class is really meant to produce an enhanced, complex embed block for the frontend, while here all we need is some basic block markup without any extras. Long term we cannot use the embed render for this.

**Pull request closed without merging**
