### PR TITLE
Fix eyedropper test

### PR DESCRIPTION
**Pull request by merapi**
### QA

- [x] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

### UAT

- [x] UAT should use the same steps as above.

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/google/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This PR contains automated tests (unit, integration, and/or e2e) to verify the code works as intended ([docs](https://github.com/google/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #

### CODE REVIEW

**Comment by swissspidy** [comment]
Does this supersede #8524?

**Comment by merapi** [comment]
Looks like we have two separate issues:
1. Inserting media element - no fix yet? (for me it works locally with `step` option but we need a better fix).
2. Eyedropper - issue caused by dynamic import, can be fixed by waiting. Not sure about "misalignment issue at it's core" - I didn't saw that in my tests.

**Comment by swissspidy** [comment]
> * Inserting media element - no fix yet? (for me it works locally with `step` option but we need a better fix).

See #7481 for that.

Seems like it was introduced in #8320 or at least surfaced by it. See https://github.com/google/web-stories-wp/pull/8320#issuecomment-883629065 and 661451550cb06dfbb87c1b7b5e379ee29425275c for context.

**Comment by maxyinger** [comment]
Yea I just put up #8524 to help out. fine if we scrap the entire PR.

As for the misalignment issue, once I was able to add media to the canvas, I was getting this part of the test failing:
https://github.com/google/web-stories-wp/blob/2e0b822bcd77f1ede25cb34d54b7aac14abdbda7/assets/src/edit-story/components/colorPicker/karma/eyedropper.karma.js#L86

Because of this behavior(notice the zoomed in image bubble isn't pink when the cursor is over the pink image, and it's not until I move the cursor pretty far down on the image that the zoomed in canvas picks up the top of the picture):

https://user-images.githubusercontent.com/35983235/127879687-1015a197-971a-4cb9-9eff-74bf4093ddd9.mp4

**Comment by miina** [comment]
> Seems like it was introduced in #8320 or at least surfaced by it.

Is this happening only with Media btw? It seems to me that it's also happening to other elements that use Moveable (e.g. reload the page, go to the Shapes tab quickly and try inserting one).

I'm guessing that since `Moveable` is now dynamically loading, it's not getting loaded fast enough for the tests (and usage as well when trying to use it right away). We might need to revert the lazy loading for it.

**Comment by merapi** [comment]
This fix is still useful (just the Moveable part was removed), let's merge it (one ✅   needed).

**Comment by swissspidy** [comment]
There's [this one screenshot on Percy](https://percy.io/google/web-stories-wp/builds/11936264/changed/672101805) where the eyedropper hasn't fully loaded yet. Flakey, bug, or expected change?

**Comment by merapi** [comment]
> There's [this one screenshot on Percy](https://percy.io/google/web-stories-wp/builds/11936264/changed/672101805) where the eyedropper hasn't fully loaded yet. Flakey, bug, or expected change?

Fixed (kinda expected because the whole Color Picker is now lazy-loaded).

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
