### PR TITLE
WordPress 6.6 Compatibility

### LINKED ISSUE #13702: WordPress 6.6 Compatibility
## Task Description

Schedule: https://make.wordpress.org/core/6-6/

Important dates:

* Beta 1 on June 4
* RC1 on June 25
* Stable release on July 16

Things that stand out:

* Potential changes to plugin onboarding/configuration flows

**Previously:**

* #13043
* #13259
* #13447
* #13581

**Before release of WordPress 6.6:**

* [x] Manual testing against trunk/Beta/RC releases
* [x] Run E2E tests against 6.6 RC once published
* [x] Update staging environments to use 6.6 RC
* [x] Bump `Tested up to` in `readme.txt`

**After release of WordPress 6.6:**

* [ ] Update `php-stubs/wordpress-stubs` (via `composer update php-stubs/wordpress-stubs`)
* [x] Update `php-stubs/wordpress-tests-stubs`
* [ ] Update `sniccowp/php-scoper-wordpress-excludes`

### PR DESCRIPTION
**Pull request by Swanand01**
## Summary

This PR updates tests to run against WP 6.6-RC1.

## User-facing changes
None.

## Testing Instructions
None.

### Does this PR have a security-related impact?
No.

### Does this PR change what data or activity we track or use?
No.

### Does this PR have a legal-related impact?
No.

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it
- [x] I have tested this code to the best of my abilities
- [x] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [x] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [x] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #13702

### CODE REVIEW

**Comment by swissspidy** [comment]
Those `Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".` warnings are unfortunately a known issue in core. We can ignore those messages in the `bootstrap.js` file.

**Comment by swissspidy** [comment]
@Swanand01 I don't think it's a timeout issue. The selector seems to have changed, `.editor-post-publish-button[aria-disabled="true"]` isn't correct anymore in 6.6

**Comment by Swanand01** [comment]
I'm going to try to revert the changes I made, to at least make the E2E tests pass on a 6.4 and 6.5. 
The issue is I am unable to run the tests locally due to some mariadb problem, so I'm unable to run the tests before committing. Maybe @AnuragVasanwala could help with the problem in 6.6-RC1?

**Comment by Swanand01** [comment]
> I'm going to try to revert the changes I made, to at least make the E2E tests pass on a 6.4 and 6.5. The issue is I am unable to run the tests locally due to some mariadb problem, so I'm unable to run the tests before committing. Maybe @AnuragVasanwala could help with the problem in 6.6-RC1?

Nevermind, only had to add a conditional to check if the button's `textContent` matches "Update" or "Save". No other changes necessary.

**Review by swissspidy — APPROVED** [review]
Glad you were able to figure out the selector issue! 👍

**Pull request merged**
