### PR TITLE
Dashboard: Applied design updates to Wellbeing template

### LINKED ISSUE #2477: Templates: Update Wellbeing template to 9:16
Use this Figma doc to apply 9:16 updates to the existing `Wellness` template:
https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61

### PR DESCRIPTION
**Pull request by mariano-formidable**
## Summary

This PR applies the new design updates to the Wellbeing template.

## User-facing changes

Layout and text sizes have been update on the Wellbeing template based off the recommendations found in this [figma design doc](https://www.figma.com/file/RTzSw47oi6pEZXEfP2JoBo/Templates?node-id=766%3A61).

## Todo
- I couldn't figure out a way to import the outline blob and the editor currently doesn't support outlining shapes so I couldn't place the outlines anywhere.
- I also couldn't figure out a way to import the long narrow arrow SVG either, so I'm gonna get some help to get it imported in another PR.

## Testing Instructions

1.) Go to "Explore Templates".
2.) Hover over the Wellbeing template and click on "View".
3.) Take a look at each template page in the detail view for Wellbeing.  Make sure images are showing up and the layout appears as shown in the figma updates.

---

Fixes #2477

### CODE REVIEW

**Review by BrittanyIRL — APPROVED** [review]
LGTM! 

2 little things: 
It seems like the placeholder logo text is getting cut off on the last o.
Screen Shot 2020-06-23 at 4 14 13 PM

I Know the 9th page got updated to have 4 retreats instead of 5, it would make sense to update the heading to top 4 instead of top 5.

**Comment by mariano-formidable** [comment]
> LGTM!
> 
> 2 little things:
> It seems like the placeholder logo text is getting cut off on the last o.
> Screen Shot 2020-06-23 at 4 14 13 PM
> 
> I Know the 9th page got updated to have 4 retreats instead of 5, it would make sense to update the heading to top 4 instead of top 5.

I don't know.... keeping it at 5 makes it mysterious... :D Joking, I'll fix.

And good eye on the logo, I think I have a better version of it I'm using in the Cooking template that I'll migrate over.

**Review by dmmulroy — APPROVED** [review]
👍 🚀

**Comment by mariano-formidable** [comment]
@googlebot I consent

**Pull request merged**
