### PR TITLE
Design System: Ensure WP toolbar access when dialogs are open

### LINKED ISSUE #12479: Design System: Dialog overlay prevents access to WP toolbar
## Bug Description

This is like #12433, but for the admin toolbar

When a dialog (e.g. the pre-publish modal) is being displayed, its overlay covers the admin toolbar submenu items.

## Screenshots

Screenshot 2022-10-17 at 09 21 04

## Additional Context

- Plugin Version: 1.26.0-alpha
- WordPress Version:
- Operating System:
- Browser:

### PR DESCRIPTION
**Pull request by timarney**
## Context

This is like https://github.com/GoogleForCreators/web-stories-wp/issues/12433, but for the admin toolbar

When a dialog (e.g. the pre-publish modal) is being displayed, its overlay covers the admin toolbar submenu items.

## Summary

Updates css to use `relative` vs `fixed` for `#wpcontent`

Not sure what the previous history of setting this `#wpcontent` to `fixed` was but... with that set admin was sitting under the dialog regardless of the z-index being set.

See change in action here:
👉 https://www.youtube.com/watch?v=BaqO8QjniAs

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1. Create a new story
2. Press publish 
3. Resize the browser to ensure the admin bar / submenu overlaps with the publish dialog
4. Note your able to access the sub menu

### Does this PR have a security-related impact?

No

### Does this PR change what data or activity we track or use?

No

### Does this PR have a legal-related impact?

No

## Checklist

- [x] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [x] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [x] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [x] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12479

### CODE REVIEW

**Comment by swissspidy** [comment]
> Not sure what the previous history of setting this `#wpcontent` to `fixed` was but... with that set admin was sitting under the dialog regardless of the z-index being set.

According to git blame this was added in #11506

> Updated the wpcontent css, ignore tooltip y offset so the tooltips dont move when the admin plugin menu is scrolled 

> Setting the wp content position to fixed allows the content to span the entire page, while still maintaining the correct functionality for the admin plugin menu. The tooltips ignoreMaxOffsetY was set to true so that the tooltips do not scroll with the admin plugin menu

Can you verify that tooltips still work as expected?

**Comment by timarney** [comment]
> Can you verify that tooltips still work as expected?

The tooltips seems fine but there was a very noticeable amount of whitespace at the bottom of the editor.

I updated the selector so it only targets that selector when the React modal is open --- I think that should keep the intention of the original PR fixing that selector in place while also covering the modal case in this PR.

**Review by spacedmonkey — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]

**Comment by kkalarickal** [comment]
@timarney @swissspidy : Confirmed that the fix ensures that WP toolbar is accessible even when the pre-publish modal is open.

QA Note:
1. Below height of 540 px, the publish button is no longer visible

2. Just like the pre-publish modal used to hide the WP toolbar, the calendar selector hides the WP admin menu items

I wanted to point these out in case we plan to do something about them. I can open a separate ticket for the calendar modal preventing access to WP Admin > sub-menus.

**Comment by swissspidy** [comment]
Really appreciate the thorough testing @kkalarickal!

> Below height of 540 px, the publish button is no longer visible

That's OK as we don't officially have proper support for smaller screen sizes like smartphones and tablets (yet). There are tons of usability issues like this on smaller screens.

> Just like the pre-publish modal used to hide the WP toolbar, the calendar selector hides the WP admin menu (effect is more pronounced when it is expanded)

Also negligible because a) the menu is usually collapsed and b) when you open the date picker it seems very unlikely that you want to open the admin menu at the same time and navigate away.

**Comment by kkalarickal** [comment]
Sounds reasonable @swissspidy ... I feel this ticket can be merged now.

**Pull request merged**
